### ISSUE TITLE
PartValidation change for multiple parts with different quantities

### ISSUE THREAD

**Issue by DBT85** [jrossignol/ContractConfigurator#101]
As from the forum

Wondering if in a future release something like the following might be possible where the number represents the quantity needed and would be displayed as

Your vessel must comprise at least
1x Big Orange tank
4x Gigantor solar panels
2x Cupola Module

PARAMETER
{
name = PartValidation
type = PartValidation
title = Your vessel must comprise at least
part = 1, BigOrangeTank
part = 4, GigantorSolarPanel
part = 2, CupolaModule
}

Would it be possible for this?

"part = 1, PartName" to mean It must have 1
"part => 1,PartName" to mean at least 1.

**Comment by jrossignol** [comment]
Try this:

    PARAMETER
    {
        name = PartValidation
        type = PartValidation

        VALIDATE
        {
            part = fuelTank3-2
            minCount = 1
        }

        VALIDATE
        {
            part = largeSolarPanel
            minCount = 4
        }

        VALIDATE
        {
            part = cupola
            minCount = 2
            maxCount = 2
        }
    }

**Comment by DBT85** [comment]
Tried this and got the error while using 0.5.7.0

[Error]: ContractConfigurator.ContractConfigurator.PartValidationFactory: CONTRACT_TYPE 'ScanMohoLoResBiome', PARAMETER 'PartValidation' of type 'PartValidation': unexpected node 'VALIDATE'.

**Comment by jrossignol** [comment]
Yeah, I usually don't change the version number until the end of development (but I suppose I should do it at the start).  0.5.5 is where I forked and started working on the 0.6.0 in parallel with 0.5.x fixes.

In short, watch for stability issues, as you've seen over on issue #106
