### ISSUE TITLE
Restrict amount of offered contracts by "contract group"

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#103]
Define a groupname/type or something else in the contracts body. For example:

"group = SCANSat"

Check the amount of offered contracts while creating a contract and do not create more than X (maybe configured in the CC config.) contracts of the same group.

**Comment by jrossignol** [comment]
Done, see [CONTRACT_GROUP] (https://github.com/jrossignol/ContractConfigurator/wiki/Contract-Group) and additional group attribute on [CONTRACT_TYPE] (https://github.com/jrossignol/ContractConfigurator/wiki/Contract-Type).
