### ISSUE TITLE
Orbit Parameter changes default situation to landing in flight

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#106]
Don' t know what is exactly happening. While accepting the contract everything is fine. After flying into an orbit the orbit situation switched to landing. Not sure why, maybe because situation isn't stored in OrbitParameter onSave/onLoad?

**Comment by jrossignol** [comment]
Yes, landed is most likely the first value in the enumeration. Need to add it to the OnSave / OnLoad.

**Comment by SimonTheSourcerer** [comment]
Tried it, worked, but wont make a pull request for 2 lines :)

**Comment by DBT85** [comment]
No idea of the words you speak, however, I've just had the same issue. Don't recall it happening before in any of my testing though.

**Comment by jrossignol** [comment]
The issue was introduced in development for 0.6.0 - so if you're on 0.5.7 you should be fine.

**Comment by jrossignol** [comment]
Fixed in code, but didn't recompile the .dll.  Also, it'll break existing 0.6.0 saves that use this parameter, since I didn't include a default value.  :wink:
