### ISSUE TITLE
Add "Ignore Requirements" button/radio to Alt F10 window?

### ISSUE THREAD

**Issue by DBT85** [jrossignol/ContractConfigurator#107]
No idea if you can do it, but being able to disable all mission requirements for contracts with a button would be really handy to save people having to comment/cut everything out

**Comment by jrossignol** [comment]
Interesting.... Let me think on this one and see if I can come up with
something useful.

**Comment by jrossignol** [comment]
Not quite ready, but I didn't like the idea of disabling all requirements.... :wink: 
![image](https://cloud.githubusercontent.com/assets/8717685/5846431/cec3ebf6-a180-11e4-9b07-b6caf1b6474c.png)

**Comment by DBT85** [comment]
Looks perfect.
