### ISSUE TITLE
Debug menu is empty

### ISSUE THREAD

**Issue by cherrydev** [jrossignol/ContractConfigurator#117]
All I can see when I bring up the CC debug menu is the header (Contract Configurator 0.5.0.0) and then a single "Reload Contracts" button.  There is no other information on the configurable contracts loaded.  I can confirm that configurable contracts are displayed and working.

**Comment by cherrydev** [comment]
I notice in your screenshot of the debug menu that I'm comparing this to, it says 0.6.0

**Comment by cherrydev** [comment]
It looks like this is just a feature that's not released yet, sorry!

**Comment by jrossignol** [comment]
Yup, usually I mark those as "COMING SOON", although I didn't want to create confusion, since the debug menu itself already exists....

Anyway, 0.6.0 is coming relatively soon - within a week.
