### ISSUE TITLE
"clear" docking ports parameter for station contracts

### ISSUE THREAD

**Issue by FFCJoseEduardo** [jrossignol/ContractConfigurator#132]
the idea is for expanding station contracts, as suggested in here: http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-6-6-2015-02-18/page42?p=1755472#post1755472

and here: http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-6-6-2015-02-18/page43?p=1755705#post1755705

**Comment by jrossignol** [comment]
Fixed for 0.7.0
