### ISSUE TITLE
Kerbal Construction Time support

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#133]
KCT supports the idea of a flight simulation, where a vessel is tested before launch (because launches in KCT require game-time to set up).  It would be good to find a way in Contract Configurator to not allow contract parameters to be met when running a KCT simulation.

**Comment by GraemeCTaylor** [comment]
I don't think this needs to be addressed. I may be wrong but the way KCT works for simulation is it quicksaves at the start of the simulation, you can do whatever you want, then as soon as you exit the simulation, it reverts to the quicksave, and any contract you have comleted is reverts along with it. At least that is how it works for me at the moment, haven't had any problems. In fact is it useful to be able to 'complete' them in a simulation to make sure you craft is designed right (haven't forgottone a Solar panel or antenna for example.)

**Comment by jrossignol** [comment]
Had a peek at their code, confirmed.  This can be closed.
