### ISSUE TITLE
Controlling which contracts are shown? Dynamic contract parameters?

### ISSUE THREAD

**Issue by jwvanderbeck** [jrossignol/ContractConfigurator#134]
Two questions here but they are related really.  My understanding for contracts is you make up a bunch of config files that define contracts and then something randomly chooses from them to offer to the player.

1. Is there a way to control which contracts are chosen from when randomizing? IE hiding certain contracts unless conditions are met, or even making certain ones bubble up to the top and be more likely to be chosen based on parameters.

2. Is there a way to fill in a parameter dynamically?  Like say I want to ask the player to gather X amounts of Flight Data for part Y in Scope Z.  But i'd like those values to be determined at runtime based on game state.

**Comment by jwvanderbeck** [comment]
Actually point 2 is a bad example, because I'm sure if its my own custom parameter I can just do the dynamic bit inside it.  But what if it isn't my own custom parameter?

**Comment by jrossignol** [comment]
For point 1, see the [Requirement](https://github.com/jrossignol/ContractConfigurator/wiki/Requirements) node for part of the answer.  Requirements determine what a player needs to do/acheive before the contract can be offered.  The other way to make something bubble up to the top is to set the weight attribute in CONTRACT_TYPE - which is a weight relative to other contracts (where the default is one).  So a contract type with weight 0.1 is 10 times less likely to be selected and 10.0 is 10 times more likely.  Also keep in mind the maxCompletions and maxSimultaneous as that can limit the number of contracts of a given type on offer.

Best answer for point 2 in 0.6.x is as you said - put the customization in your own parameter.  The main feature of 0.7.0 solves the problem by introducing expressions across the board.  There's really no documentation at the moment, but you can see the early version in the dev branch.  Right now you can do something like:

```
minAltitude = 100
maxAltitude = @minAltitude * 10

title = This is the contract title that says you should go to @targetBody.
```

The unimplemented stuff is going to allow you to do stuff like:

````
minAltitude = Random() * 1000 + 1000
targetBody = [Mun, Minmus].Random()
````

Planning on it being _very_ flexible, but still in the early stages.

**Comment by jwvanderbeck** [comment]
For point 2, in my own contract parameters, where would I hook into dynamically decide on values so that they will be displayed to the player when browsing contracts?  Obviously I can't do it in OnContractAccepted() because that's too late.

Do I do it in OnRegister()?

**Comment by jrossignol** [comment]
You should look at the ParameterFactory for that.  The ParameterFactory has two methods that can/should be overriden:

```
bool Load(ConfigNode) - Called when Contract Configurator config is loaded (on the main menu).  Responsible for loading from the config node.

ContractParameter Generate(Contract contract) - Called when a new contract is being generated, this creates an instance of your ContractParameter.
```

Most of the contract configurator parameters have two constructors, one that is called from the Generate() method, and a parameterless one used by KSP's loading logic.  So you could follow the same idea and have the dynamic stuff generated in the alternate constructor, directly in the factory's Generate() method or in another public method of the parameter's that is called by Generate().

**Comment by jrossignol** [comment]
Closing this, as the original questions have been answered.  Please feel free to reopen or raise a new issue.
