### ISSUE TITLE
Waypoint name is not going into title

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#145]
Per your request in this posting:
http://forum.kerbalspaceprogram.com/threads/107661-Contract-Packs-for-Contract-Configurator-General-Thread?p=1790603&viewfull=1#post1790603

Getting the waypoint name into the title is supposed to work, but because it's in a child config node in this case it doesn't.

**Comment by jrossignol** [comment]
Dev done, have a look in the wiki for the details on how to use it:
https://github.com/jrossignol/ContractConfigurator/wiki/Function-Reference-Guide#contract-configurator-objects
