### ISSUE TITLE
NullReferenceException when using textgen with no specified agent

### ISSUE THREAD

**Issue by ApolloFunghi** [jrossignol/ContractConfigurator#146]
The following causes a null reference exception and bugs out the stock contract system.

The exception only occurs when both the agent is unspecified, and using textgen for the mission description.

	CONTRACT_TYPE
	{
		
		name = testContract
		title = do a thing
	
		// commenting out the following 3 lines and uncommenting description results in no error
		topic = stuff
		subject = orbit	
		motivation = test
		// description = stuff
									  
		synopsis = do a thing
		completedMessage = done
	
		// uncommenting this results in no error
		// agent = Integrated Integrals
	
	
		PARAMETER
		{
		    name = LaunchVessel
		    type = LaunchVessel
		}
	}

Exception trace;

	[Exception]: NullReferenceException: Object reference not set to an instance of an object
	ContractConfigurator.ConfiguredContract.Generate ()
	Contracts.Contract.Generate (System.Type contractType, ContractPrestige difficulty, Int32 seed, State state)
	Contracts.ContractSystem.GenerateContract (Int32 seed, ContractPrestige difficulty, System.Type contractType)
	Contracts.ContractSystem.GenerateContract (System.Int32& seed, ContractPrestige difficulty)
	Contracts.ContractSystem.GenerateContracts (System.Int32& seed, ContractPrestige difficulty, Int32 count)
	Contracts.ContractSystem.RefreshContracts ()
	Contracts.ContractSystem+.MoveNext ()

**Comment by jrossignol** [comment]
Dev done, closing ticket.
