### ISSUE TITLE
dates don't accept expressions

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#148]
As we discussed on the forum - example:

REQUIREMENT
{
    name = Rotation
    type = CompleteContract

    contractType = KerbinCrewRotation
	
	minCount = 0
	cooldownDuration = Random(30, 120)d
}

**Comment by jrossignol** [comment]
Expectation is that duration will get its own "type" in the expressions, so once implemented it should give options like this:

```cooldownDuration = Random(30d, 120d)```
```cooldownDuration = Random(2d 1h 5m, 1y)```

In this distant future this could open open stuff like:
```deadline = TimeUntilTransferWindowCloses(Duna)```

**Comment by jrossignol** [comment]
Dev done, closing issue.
