### ISSUE TITLE
Allow negative rewards/penalties

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#149]
Requested by Arachnidek ([forum post](http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-7-0-2015-03-17?p=1792671&viewfull=1#post1792671))

Try removing the validations on rewards/penalties to see if it works.  Otherwise need to manually account for this.

**Comment by jrossignol** [comment]
Ran some tests, KSP will clamp it to zero, unfortunately.

**Comment by jrossignol** [comment]
Well, guess I put this one off for long enough that is solved itself... KSP no longer clamps the rewards to zero, so all I had to do was remove the validation. :+1:

**Comment by inigmatus** [comment]
looking forward to testing this. if it works, I'll be able to offer a store of sorts! :D

**Comment by inigmatus** [comment]
IT WORKS!  i could hug you. thank you.
