### ISSUE TITLE
PartValidation part = 1.25_Heatshield isn't working

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#181]
Looks like _ is a illegal char but can still be used in names like:  "1.25_Heatshield" (DeadlyReentry). 
Error: "[Exception]: FormatException: Unknown char: _"

There is a problem with - too for example Mark1-2Pod (vanilla) gets his name split.
[Exception]: ArgumentException: 'Mark1' is not a valid Part.

**Comment by jrossignol** [comment]
Ugh, both of these are ugly, but should be fixable.

**Comment by SimonTheSourcerer** [comment]
Both things allready worked in earlier versions. I recently updated to 0.7.x and I got this :)

**Comment by jrossignol** [comment]
Yeah, its because of the introduction of the expressions.  Everything can potentially be parsed as an expression, so some of the parsing got a little tightened up...  there's lots of exceptions already, just need to loosen it a bit for part names.

**Comment by jrossignol** [comment]
Fixed in development version.
