### ISSUE TITLE
Waypoint without icon

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#186]
Would be nice to have a way to have a hidden waypoint.

**Comment by linuxgurugamer** [comment]
As a suggestion, I'd say to do one of the following:

icon = 

or. the following is clearer:

icon = none

**Comment by jrossignol** [comment]
I made it more verbose - it's a new attribute called 'hidden'.  If you specify it, you don't need an icon:
```
WAYPOINT
{
    ...
    hidden = true
}
```

**Comment by jrossignol** [comment]
Will be released in 0.7.12

**Comment by linuxgurugamer** [comment]
Great!  Thanks
