### ISSUE TITLE
Contract groups within contract groups

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#187]
Allow hierarchies of contract groups - to allow splitting the "min/max" logic and the version check logic, and better organization.

**Comment by severedsolo** [comment]
I was going to request this when I saw this issue - at the moment I use 2 groups for each body, although I limit each group to 1 simultaneous mission, 

But with only 12/13 slots avaliable in mission control, my missions could quickly take over, once I add new bodies, so could I have the ability to say - overall 3 simultaneous missions for the whole pack, and each sub group can generate one simultaneous each  until we hit the max simultaneous of the master group? 

You may have already done this, but just in case

**Comment by jrossignol** [comment]
I hadn't planned it that way, but it makes sense - I'll make sure the min/max values can be applied across the hierarchy that way.

**Comment by jrossignol** [comment]
Implemented for 0.7.12
