### ISSUE TITLE
WaypointGenerator WAYPOINT count attribute doesn't support expressions

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#188]
[QUOTE=nightingale][QUOTE=linuxgurugamer]Is it possible to have a waypoint without an icon? If so, how?

I looked at your anomoly pack, but didn't see any with that.

Also, is this allowed:

[code]
                // The number of waypoints to generate.
                // Default = 1
                count = Random(3,7)
[/code]

Thanks[/QUOTE]

Expressions will work pretty much anywhere, so the Random(3, 7) should work just fine. 

Currently, there's no way to have a hidden waypoint, but should be fairly simple to implement. Throw me a github issue with your requirements and I'll take a look.[/QUOTE]

In the RANDOM_WAYPOINT_NEAR, I'm getting an error with this:

[code]count = Random( 3,  7)[/code]

When I replaced it with the following, it worked:

[code]count = 5[/code]

You can get the full cfg file here:
https://drive.google.com/file/d/0Bzid7e3pW1k7ek03VjhqaGFHTkU/view?usp=sharing

**Comment by jrossignol** [comment]
By the way, BBcode won't work on GitHub. :wink: 

Anyway, problem is that the waypoint child nodes don't support expressions.  Need to make some minor modifications to make it work there.  I'll tentatively try to get it done for the 0.7.12 release.

**Comment by linuxgurugamer** [comment]
I did a cut/n/paste for that, sorry about the excessive codes.

Thanks for all you are doing with this.

**Comment by jrossignol** [comment]
This is now working, feel free to grab the [development .dll](https://github.com/jrossignol/ContractConfigurator/raw/master/GameData/ContractConfigurator/ContractConfigurator.dll) to test.
