### ISSUE TITLE
Spawning a vessel always has a vessel name "Untitled Space Vessel:

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#195]
Spawning a vessel always gives the vessel name "Untitled Space Vessel"
Doesn't matter if I try specifying a name or not. 

LGG

**Comment by jrossignol** [comment]
Can you provide the config details that you're using?

**Comment by linuxgurugamer** [comment]
Here is a zip file with all the cfgs and craft files needed.  The files in here have the name specified for the vessels, but when I commented them out, there was no change

https://drive.google.com/file/d/0Bzid7e3pW1k7Y282NkRXQUlyZzg/view?usp=sharing

**Comment by linuxgurugamer** [comment]
And just a thought on the ship name.  I did a small test, loading a standard ship, the name came through properly.  But spawing a vessel from a craft file in the mod directory did not pick up the ship name

**Comment by jrossignol** [comment]
Had a look at this, and unfortunately the file you linked to only has the share assets - no contracts.  Anyway, did a quick retest, and it works correctly for my tests. The following snippet spawns two ships from the same .craft file, both with different names from what's in the file:
```
    BEHAVIOUR
    {
        name = SpawnVessel
        type = SpawnVessel

        VESSEL
        {
            // If the name is not supplied, defaults from the name within the
            // craft file
            name = The new vessel

            // Path to the .craft file (relative to the GameData/ directory)
            craftURL = ContractConfigurator/Little Rocket.craft

            // Whether the vessel should show up as owned or unowned.  If it is
            // owned, then it will be immediately selectable.
            owned = True

            // Where the vessel should spawn - defaulted from the contract if
            // not supplied.
            targetBody = Kerbin

            // Orbit that the vessel should be placed in.
            // Note that REF represents the reference body - but will be
            // overriden by the targetBody.
            ORBIT
            {
                SMA = 1449999.99996286
                ECC = 1.07570816555399E-05
                INC = 0
                LPE = 270.690311604893
                LAN = 1.93635924563296
                MNA = 1.55872660382504
                EPH = 31.3999999999994
                REF = 1
            }

            CREW
            {
                count = 1
            }
        }

        VESSEL
        {
            // If the name is not supplied, defaults from the name within the
            // craft file
            name = Landed Vessel

            // Path to the .craft file (relative to the GameData/ directory)
            craftURL = ContractConfigurator/Little Rocket.craft

            // Location of the flag to use.
            // Default = Player's flag for the current game
            flagURL = Squad/Flags/satellite

            // Whether the vessel should show up as owned or unowned.  If it is
            // owned, then it will be immediately selectable.
            owned = True

            // Where the vessel should spawn - defaulted from the contract if
            // not supplied.
            targetBody = Kerbin

			lat = 0.096992729723051
			lon = 285.425467968966

            // A CREW node indicates one or more crew members to add to the
            // vessel
            CREW
            {
                // Name for the crew member - if not provided, one is
                // auto-generated.
                name = Patrick R. Kerman

                // Whether or not the Kerbal should be added to the roster on 
                // recovery.
                // Default = True
                addToRoster = True
            }
        }
    }
```

**Comment by linuxgurugamer** [comment]
Ok.  I'll build a new install and test again.

Hmmm.  I wonder if characters are significant, I noticed that you didn't have dashes or underscores in the name:

Here is an excerpt from one of the cfg files:

                        name = Sprite_-_Light_SSTO_Dropship_T

                        // Path to the .craft file (relative to the GameData/ directory)
                        craftURL = ContractPacks/Spacetux/SpriteMissions/Sprite - Light SSTO Dropship (T).craft


Thanks

**Comment by linuxgurugamer** [comment]
I wonder, that file I gave you may have been built from a debug setting.
I  just released it, and verified that the released file has everything:
https://kerbalstuff.com/mod/703/Contract%20Pack:%20Sprite%20Missions

**Comment by jrossignol** [comment]
No luck reproducing using both dashes and underscores.  Will have a look at your contract pack.

**Comment by jrossignol** [comment]
Just took the LearnToFlySprite contract and that one works fine.  Is there a specific contract that isn't working?

**Comment by linuxgurugamer** [comment]
No, that was it.
Is it possible that OSX (which is where I'm testing) is the issue?

I'll set up a new install on Windows and see if I can replicate it there.
Thanks for looking into it, I'll let you know if I find anything different.

**Comment by linuxgurugamer** [comment]
I just tested on Windows, and it worked.

So now I'll build a new install on OSX and try it again there.

**Comment by jrossignol** [comment]
Seems unlikely that OSX is the issue....  but not much else left.  If it wasn't loading the .craft file I could see it being related to file paths and / vs. \...

**Comment by jrossignol** [comment]
Doing some cleanup, assuming that this is resolved and closing.  Please re-open if you're still having problems with this.
