### ISSUE TITLE
Behaviour for unlocking tech nodes

### ISSUE THREAD

**Issue by klefenz** [jrossignol/ContractConfigurator#199]
Adding a possibility to unlock tech nodes upon the completion of a contract would allow a major change on how carrer mode is played.
Technologies could be unocked by completing research and test fly missions instead of grinding research points.

**Comment by jrossignol** [comment]
Would need to support unlocking on:
- Contract accepting
- Contract completion
- Parameter completion

**Comment by jrossignol** [comment]
Implemented by Klefenz for 1.2.2
