### ISSUE TITLE
Feature request: query semi-major axis of CelestialBodies

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [jrossignol/ContractConfigurator#218]
I'm working on a contract pack for AntennaRange, and toadicus is going to switch up the transmitter ranges so that the DTS-M1 will be useful for inner-planet missions.  Unfortunately, there's no way to tell from Contract Configurator if a planet is inner or outer.  Can we have a double SemiMajorAxis() function? Then I could do stuff like AllBodies().Where(b => b.SemiMajorAxis() < 1.6 * HomeWorld().SemiMajorAxis()) (the 1.6 is there so that Duna/Mars gets included as an inner planet).  Thanks!

**Comment by jrossignol** [comment]
Done, will be released for 1.2.2 (expected release date is tomorrow).
