### ISSUE TITLE
Renaming vessels fails RemoteTech contracts

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#220]
From Svannon on [the forum](http://forum.kerbalspaceprogram.com/threads/106580-1-0-2-Contract-Pack-RemoteTech-v1-1-4-2015-05-25?p=1987207&viewfull=1#post1987207):

> Just a possible bug Report with the 4 satellite initial Kerbin contract, don't know about the 3 sat Version,that if you rename a satellite after The Contract has turned green for the satellite your launching it instantly fails the contract.

> Had my second Satelite in place and then Renamed it from Kerbin Com Sat Mk1 to Kerbin Com Sat Beta. Don't remember that happening before. Is this by design ?

**Comment by Svannon** [comment]
Replicated the bug.  Logs below

https://www.dropbox.com/sh/1icj9itplz6ohkm/AACTtLANMQvTEWppd8V_y8BUa?dl=0

**Comment by jrossignol** [comment]
Interesting, not what I expected to see in the log, but it helps.  Thanks!

**Comment by jrossignol** [comment]
Fixed!
