### ISSUE TITLE
Add support for disabling contract groups per save

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#221]
Requested by ManuxKerb on [the forums](http://forum.kerbalspaceprogram.com/threads/101604-1-0-2-Contract-Configurator-v1-2-3-2015-05-30?p=1987647&viewfull=1#post1987647):

> I love contract configurator and also the super cool and diverse/different contracts. Now this leads to the problem that I have multiple saves and for exaple i try to play the tourism contracts on one save and on the other the seti contracts. So i would like to get only the seti contracts in the seti save. And also only the tourism ones in my tourism save. 

> However this is not possible with both packs installled at the same time.

> So here is my request: Could you make an ingame, per save, choice dialog what contracts packs should appear ? All ohters would be installed but not shown ingame. ()

> I know that there are mods like rejector and so on, but the contract modders do not seem to name their creations correctly so i dont know what contract is it. It would be better to sort them with the folder names of contract configurator.

**Comment by severedsolo** [comment]
It would be even better if we could disable per contract - say if I want to test certain missions.

**Comment by jrossignol** [comment]
That would probably be something different via the debug window (but a good
suggestion nonetheless)

**Comment by jrossignol** [comment]
Nevermind, just got another request for that one, so maybe it's needed in both places (debug window and in this new thing).

**Comment by jrossignol** [comment]
Also for consideration is extending this behaviour to stock contract types.

**Comment by jrossignol** [comment]
Done for 1.6.0
