### ISSUE TITLE
Support for Orbital Science in science stuff

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#222]
Need to support checking for Orbital Science's special experiment modules for the Field Research contract pack.

**Comment by jrossignol** [comment]
Also need to look at Station Science.

**Comment by Kerbas-ad-astra** [comment]
[N3h3miah's science mods](http://forum.kerbalspaceprogram.com/threads/118716) and [Impact!](http://forum.kerbalspaceprogram.com/threads/114087-1-0-Impact!-impact-science-an-contracts-v1-0-1-1-May-2015) also add special experiment modules.

**Comment by jrossignol** [comment]
Partially fixed - need to do Station Science and N3h3miah's stuff still.

**Comment by jrossignol** [comment]
And done.
