### ISSUE TITLE
Create ProtoVessel early to make Vessel object available in contract

### ISSUE THREAD

**Issue by GrJo** [jrossignol/ContractConfigurator#231]
Problem: A vessel spawned with the SpawnVessel behaviour is not available as an object until the contract is accepted, and it so its not possible to call methods on it. It would be great if I could do stuff like @/SpawnVesselBehaviour.Vessel().Stuff() in my contract configuration

**Comment by jrossignol** [comment]
If you don't mind testing this out (dev dll [here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true)).  I think everything should be working alright.  The syntax will be exactly as above.

**Comment by jrossignol** [comment]
Sadly, this causes some pretty major issues and I'm going to have to revert it.
