### ISSUE TITLE
Exception generating contract MedicalEmergency

### ISSUE THREAD

**Issue by jakkarth** [jrossignol/ContractConfigurator#233]
Contract Configurator 1.3.2 Exception

Exception occured while attempt to generate contract of type 'MedicalEmergency':
System.ArgumentNullException: Argument cannot be null.
Parameter name: source
  at System.Linq.Check.SourceAndSelector (System.Object source, System.Object selector) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Select[Kerbal,String] (IEnumerable`1 source, System.Func`2 selector) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.RecoverKerbalFactory.Generate (Contracts.Contract contract) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ParameterFactory.Generate (ContractConfigurator.ConfiguredContract contract, IContractParameterHost contractParamHost) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ParameterFactory.GenerateParameters (ContractConfigurator.ConfiguredContract contract, IContractParameterHost contractParamHost, System.Collections.Generic.List`1 paramFactories) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractType.GenerateParameters (ContractConfigurator.ConfiguredContract contract) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ConfiguredContract.Initialize (ContractConfigurator.ContractType contractType) [0x00000] in <filename unknown>:0 

seen when just sitting at KSC. Similar exceptions flash by too, one might be ReturnCrew, they flash by very quickly so it's hard to read them.

**Comment by jakkarth** [comment]
LSResupply is another. May also be worth noting that I have no kerbals in space at the moment.

**Comment by jakkarth** [comment]
Guessing that 1.3.3 is going to fix this problem for me. I'll reopen if I get it again after updating. Thanks as always.

**Comment by jrossignol** [comment]
Sorry, I actually forgot to look at this one before doing the 1.3.3 release!  I have to head out for a bit, but will have a look at this one tonight.

**Comment by jakkarth** [comment]
Ok, thank you! If I put a manned vessel on the runway, will that make the errors stop appearing? If not, is there some other workaround I can do so I can play until then?

**Comment by jrossignol** [comment]
The only workaround I can think of would be to remove the file (temporarily until I get a fix) for the MedicalEmergency contract (it should be somewhere in the KSS contract pack).

**Comment by jrossignol** [comment]
Hmmm....  I need more info to be able to reproduce/fix this one properly.  Are you able to provide a log file?

**Comment by jakkarth** [comment]
I should have grabbed one when I had the chance. Now I have disabled those contracts and I have kerbals in a space station. I will see what I can do.

**Comment by jakkarth** [comment]
http://silenttosaturn.com/kspsave/ContractConfigurator.log.gz is the log file. The exceptions are at the very end. I apologize for how large it is.

**Comment by jakkarth** [comment]
Also I am getting the errors now while I do have a space station in LKO, it is manned and also has free seats. It is not the active vessel when the errors start appearing; the active vessel is also in LKO, has 6 empty seats and no filled ones.

**Comment by jakkarth** [comment]
On a side note, I get each of the exceptions once every 10 seconds or so. It would be nice if, when an exception occurs, that particular contract type is ignored for 5 minutes or so instead of 10 seconds. I'm not sure if this is something you have control over or not. I do like the fact that I was notified that the generation of the contract had a problem.

**Comment by jrossignol** [comment]
Indeed, that's something that I've been meaning to do, raised https://github.com/jrossignol/ContractConfigurator/issues/236.

I'll take a look at your log.

**Comment by jrossignol** [comment]
Hmmm, having some trouble with this one.  I added some improved logging and exception handling, can you try again with the [dev dll](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true) and add this .cfg file to turn up some logging (name/location of the cfg doesn't matter:
```
CC_DEBUGGING
{
	// Possible LogLevel: VERBOSE, DEBUG, INFO, WARNING, ERROR
	//logLevel = DEBUG
	logLevel = DEBUG

	ADD_LOGLEVEL_EXCEPTION
	{
		// Type name
		type = ContractConfigurator
		// Possible LogLevel: VERBOSE, DEBUG, INFO, WARNING, ERROR
		logLevel = VERBOSE
	}

	ADD_LOGLEVEL_EXCEPTION
	{
		// Type name
		type = ContractPreLoader
		// Possible LogLevel: VERBOSE, DEBUG, INFO, WARNING, ERROR
		logLevel = VERBOSE
	}
}
```

**Comment by jakkarth** [comment]
New dll overwrites old, contents of quoted area placed in GameData/ContractConfigurator/test.cfg. Please stand by for the 10 minute load time (even on an SSD, when you have 181 mods installed starting KSP can take a while).

**Comment by jakkarth** [comment]
http://silenttosaturn.com/kspsave/ContractConfigurator2.log.gz. Occurred before I could even click the VAB when I autoloaded my save.

**Comment by jrossignol** [comment]
Okay, I am *really* having trouble reproducing it.  Let's try this, can you go to one of the contracts that's failing, and add trace = true at the top (like this):
```
CONTRACT_TYPE
{
    trace = true
    name = MedicalEmergency
    ...
}
```
Then get *another* log....  hopefully that'll have the hint I need.

**Comment by jakkarth** [comment]
trace = true added to the UsefulSpaceStation/MedicalEmergency.cfg and KerbinSpaceStation/MedicalEmergency.cfg (not sure why there's two in separate folders?). Loading now, will post log in 15 minutes.

**Comment by jakkarth** [comment]
http://silenttosaturn.com/kspsave/ContractConfigurator3.log.gz. Including http://silenttosaturn.com/kspsave/ContractPacks.zip for the record.

**Comment by jakkarth** [comment]
http://silenttosaturn.com/kspsave/modlist%202015-06-14.ckan is my current mod list if that helps.

**Comment by jrossignol** [comment]
Well that might be the hint as to what is different for you - you should
only have one!   They are supposed to be mutually exclusive. I'll have a
look at the logs, but that could be the key.

**Comment by jakkarth** [comment]
After doing some bash scripting to iterate over my installed mods and the files they provide, it looks like I have two mods that provide the MedicalEmergency contract. CKAN lists them as ContractConfigurator-KerbinSpaceStation and ContractConfigurator-UsefulSpaceStations. Both have severedsolo listed as the author and they appear to be identical in all but name. I don't know why there are two; the CKAN guys probably need to address that.

If this does turn out to be the problem I'm encountering, I'd suggest an additional feature to ignore/warn on a duplicate contract with the same name during parsing, and gracefully ignore the duplicate definition.

**Comment by jakkarth** [comment]
I stand corrected, they're not identical. The parameters are different but the contract names are the same. They should be marked as conflicting in CKAN so that both can't be installed at once.

**Comment by jrossignol** [comment]
Indeed, you should raise the CKAN issue to severedsolo. Even us this is the
cause of your issues, it's supposed to handle duplicates gracefully - so
there's still at least a little work to be done.

**Comment by jakkarth** [comment]
I have brought up the problem on the KerbinSpaceStation github issue page (issue 41). Hopefully it will be resolved soon. I will leave both packs installed for now until you track down any remaining problems.

**Comment by jrossignol** [comment]
Okay, possible fix, let's give this a try, the dll is [here](https://github.com/jrossignol/ContractConfigurator/blob/27ceb80aed233fae4d57eefd527331ef58100b29/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true).

**Comment by jakkarth** [comment]
No exceptions on save load :) I think that may have got it!

**Comment by jakkarth** [comment]
Been playing for about an hour with no exceptions popping up in-game. Would you like another log file even though nothing more is showing up on the screen? Or shall we consider this issue resolved?

**Comment by jrossignol** [comment]
No need, I think I'm going to call this one solved. Thanks for your
patience on this!

**Comment by jakkarth** [comment]
Thanks for making an awesome mod and digging through my megabytes of logs! I'll go uninstall the duplicate contract set and play on.
