### ISSUE TITLE
DV percentage parameter

### ISSUE THREAD

**Issue by CosmoBro** [jrossignol/ContractConfigurator#237]
I was seeing if is there a way to calculate the DV percentage. for example. I want a lander to land with less than 20% of it's DV for obligate him to refuel in a mining outpost is that posible. Or even not the percentage just the DV

**Comment by jrossignol** [comment]
That would be tricky.  The DV formula itself isn't bad, but then you have to look at staging.  Basically writing a whole bunch of the logic that is in KER - which I'm really not interested in doing.

How about instead looking at vessel.ResourceQuantity() / vessel.ResourceCapacity() for liquid fuel - that should give you something good enough.
