### ISSUE TITLE
Exception when working on RemoteTech CommSat contract (launch 4 comms satellites)

### ISSUE THREAD

**Issue by Aetyrno** [jrossignol/ContractConfigurator#239]
Getting the following error after launching the second satellite to orbit. Occurs when changing scenes, reproduced twice on KSP -> satellite 3 on launchpad, and KSP to monitoring station.

Exception occured while saving ScenarioModule 'ContractVesselTracker':
System.NullReferenceException: Object reference not set to an instance of an object
at ContractConfigurator.ContractVesselTracker+<>c__DisplayClass6.b__3 (.Vessel v) [0x00000] in :0 
at System.Collections.Generic.List1[Vessel].GetIndex (Int32 startIndex, Int32 count, System.Predicate1 match) [0x00000] in :0 
at System.Collections.Generic.List1[Vessel].Find (System.Predicate1 match) [0x00000] in :0 
at ContractConfigurator.ContractVesselTracker.OnSave (.ConfigNode node) [0x00000] in :0

I am running 64-bit client on win7. Can check if this is reproduced on x32 if it would be helpful.  I created a mirror install to save state for any testing required.

**Comment by jrossignol** [comment]
Already fixed for the next release - if you want to test it out early you can grab the dev version [here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true).  Should be releasing in the next day or two.

**Comment by Aetyrno** [comment]
Finally got around to testing this - it was not resolved by the update, but I can confirm that the problem is not reproduced on x32 Windows (so falls under unsupported,) and is still reproduced on x64 with only ContractConfigurator, MechJeb, and ScanSat running.
