### ISSUE TITLE
The activeUniqueValue flag isn't working correctly

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#245]
Probably due to the new preloader logic, raised by severedsolo:

> While not technically a problem, should I be seeing this contract twice? Essentially I'm getting paid twice for doing the same science (and they are exactly the same).
> 
![image](https://cloud.githubusercontent.com/assets/8717685/8254971/d573ba3c-1659-11e5-8af2-6db8efe8c01a.png)

**Comment by severedsolo** [comment]
Not just activeUniqueValue - looks like UniqueValue is also not working (same thing basically I guess?)

**Comment by jrossignol** [comment]
Yeah, it's practically the same thing (I figured if one was broken they likely both were).  But good to have confirmation.

**Comment by severedsolo** [comment]
UniqueValue is still not working.

**Comment by severedsolo** [comment]
What do you need to reproduce? Not sure how helpful a log will be?

**Comment by jrossignol** [comment]
Is it still SCANsat lite? I should be able to try reproducing this one.

**Comment by severedsolo** [comment]
Yes ScanSat Lite - it's most obvious on a fairly new career, with only 1/2 bodies orbited and a scanner unlocked. It offered 3 LoRes scan of Kerbin Contracts.

**Comment by jrossignol** [comment]
Okay, this one was a pain to track down, but think I've got it all figured out.
