### ISSUE TITLE
Parameter Hider

### ISSUE THREAD

**Issue by CosmoBro** [jrossignol/ContractConfigurator#249]
I was seeing my contracts and say an Any type parameter with like 7 child for a new sistem implemented with a list, and looks ugly and I preffer putting on the notes what can the player do.
So is there a way to get this implemmented?

**Comment by jrossignol** [comment]
Already supported - set the attribute hideChildren to true in the parent
parameter (you'll have to double check the documentation for the name,
going by memory).

**Comment by CosmoBro** [comment]
// Causes children of the parameter to be hidden (only works for
    // parameters with "automatic" children such as ReachState).
    // Use with caution - as hiding the child parameters may in some
    // cases make it more difficult for players to know what to do.
That is on the wiki. What Parameters are have "automatic" children? because i've try it on the Any param and not working

**Comment by jrossignol** [comment]
Oooh, my mistake, it's ones that you don't specify the child parameters.

Not sure why I didn't make it work in this case, I'll look into it on this
issue.

**Comment by CosmoBro** [comment]
ok thanks

**Comment by jrossignol** [comment]
Wiki is wrong - this should work anywhere.  So the question is - what do you mean when you say that it is "not working"?

**Comment by jrossignol** [comment]
Ah, I see the bug now... I'll have to give some though as to how to fix.

**Comment by jrossignol** [comment]
Fixed for 1.5.1

**Comment by CosmoBro** [comment]
Ok thanks

**Comment by CosmoBro** [comment]
This is not working for the type Any parameter I'll post a screenshot later.
