### ISSUE TITLE
vessels with locked parts do not spawn

### ISSUE THREAD

**Issue by jberkman** [jrossignol/ContractConfigurator#250]
Pretty straight forward; if a contract contains a SpawnVessel, but that vessel contains parts they haven't unlocked yet, the vessel will not spawn.

**Comment by jrossignol** [comment]
Is there an error that happens?  Or it just doesn't spawn?

**Comment by jberkman** [comment]
Well, now I can't reproduce it, so I'm guessing I just hadn't cleared my preload queue.
Sorry!

**Comment by jrossignol** [comment]
No problem!  I recently did a pretty major change to how SpawnVessel works under #231, so it wouldn't surprised me if there was an issue or two...

**Comment by jberkman** [comment]
Confirmed the problem was with the ORBIT section of a BEHAVIOUR block being doubly-nested, i.e.:

```
ORBIT
{
    {
        SMA = ...
```

**Comment by jrossignol** [comment]
Ah, haven't done too much testing with stiff that shouldn't parse - from what I've seen KSP tends to silently drop stuff like that. 

I may double check the parser for that orbit node to make sure it has appropriate warnings Regen stuff is missing (it's a bit of a special case in the code).
