### ISSUE TITLE
Allow DATA_NODE within CONTRACT_GROUP

### ISSUE THREAD

**Issue by CosmoBro** [jrossignol/ContractConfigurator#252]
I was thinking on this while making my base contracts where there are like 6 disconnected vessels so is there a way to have something like a list. The group would be defined on the VesselParameterGroup.

**Comment by jrossignol** [comment]
Well, you can specify the vessel attribute on a VesselParameterGroup multiple times.... I'd that what you're looking for?

**Comment by CosmoBro** [comment]
better like a list of vessels something like this
PARAMETER
    {
        name = NewBase
        type = VesselParameterGroup
        title = Example
        define = ExampleVessel
        group = ExampleGroup
        notes = notes
     }
   DATA
    { 
        type = List<VesselGroup>
       validvessels= [ ExampleGroup ].Random(5)
    }

**Comment by jrossignol** [comment]
I'm not sure how you would expect ExampleGroup to work in this example. VesselParameterGroup can track the child parameters against multiple vessels, but it'll only ever match one vessel at a time.

**Comment by CosmoBro** [comment]
Just like an organiser. it would work as a list. The group would be specified on the VesselParameterGroup.  You later could use that as the DATA node that I show on the prev example

**Comment by jrossignol** [comment]
Ah, I think I get what you're trying to explain.  So you would want to use the ExampleGroup as a group in many VesselParameterGroup parameters (possible across contracts) and have each vessel get added to ExampleGroup, correct?

Can you also describe the problem that you're trying to solve?  Is it so that you don't have to do [Vessel1, Vessel2, Vessel3] in every contract?

**Comment by CosmoBro** [comment]
Yes that's is
And yeah kind of and also something like vessel1 doesn't belong to examplegroup

**Comment by jrossignol** [comment]
Okay, the reason I was asking is your request is a fair bit of work.  My current thinking is that I'll add support for the DATA {} node under CONTRACT_GROUP.  That way you can specify your list of Vessel Identifiers in only one place.  It's less coding work for me, and will support a wide variety of features.  Let me know if this won't completely meet your needs.

**Comment by CosmoBro** [comment]
Yes this would help a lot, thanks!

**Comment by jrossignol** [comment]
Okay, finally time to get this one done, let me start by getting my thoughts down:

1. Scope always goes up.  CONTRACT_TYPE has access to to attributes in the parent CONTRACT_GROUP as well as any parents to that.  CONTRACT_GROUP has access to its parent CONTRACT_GROUPs, but never to the CONTRACT_TYPE(s) beneath it.
1. I think I'm going to force a "namespace" in the variable usage so the config is easier to understand after.  So to access the variable targetBody in the contract group MyGroup, you would need to do `@MyGroup:targetBody`.  This also nicely avoids the problem of collisions, as you can also access `@targetBody` in the local namespace.
1. All deterministic expressions in CONTRACT_GROUP are executed at load time (on the main menu).  Deterministic expressions are run anytime a child CONTRACT_TYPE is generated.  Values are stored under both CONTRACT_GROUP and CONTRACT_TYPE.  Specifically, the re-generation will first happen against the root CONTRACT_GROUP, and copied down to the next level and then re-generated at that level.  This is repeated until we've done the CONTRACT_TYPE level.

I think that covers all the main technical points.

**Comment by jrossignol** [comment]
Coding done, but still need doco on this one.

**Comment by jrossignol** [comment]
Documentation done, this one's finally ready. :+1:
