### ISSUE TITLE
Show orbit details in note for ReachSpecificOrbit

### ISSUE THREAD

**Issue by Shurikeeen** [jrossignol/ContractConfigurator#256]
It generates a orbit around the target but there is no info about the orbit in the contract.

**Comment by jrossignol** [comment]
Note that this is working correctly, so I've changed the title as I want to make sure you have the right expectation - what will probably get added is some expression methods that you can use for the notes - it won't be automatic.

**Comment by jrossignol** [comment]
Good news, I was able to figure out a way to get the notes displaying for this one!  No weird expressions necessary. :)
