### ISSUE TITLE
Add cooldownDuration to ProgressCelestialBody requirements

### ISSUE THREAD

**Issue by CosmoBro** [jrossignol/ContractConfigurator#259]
This was working on CC 1.5.0 but with 1.5.1 it gave me a warning and the requirement never get met.
```
ContractConfigurator.OrbitRequirement: CONTRACT_TYPE 'BaseScan', REQUIREMENT 'Orbit' of type 'Orbit': unexpected attribute 'cooldownDuration' found, ignored.
```
That was on the log.
```
REQUIREMENT
	{
	    name = Orbit
		type = Orbit
		targetBody = @/targetBody2
		cooldownDuration = 9d
	}
```
This is the requirement

**Comment by jrossignol** [comment]
:question: 

The cooldownDuration attribute has only ever been supported for the [CompleteContract requirement](https://github.com/jrossignol/ContractConfigurator/wiki/CompleteContract-Requirement).  If that wasn't throwing an error in 1.5.0, then it was a problem with my error handling (which I may have fixed a few minor issues in 1.5.1 - that might've been one of them).

But that warning still shouldn't prevent the requirement from working.  Are you sure that it's not being met?  Can you check via the debug window what targetBody / targetBody2 is being set to for that requirement?

**Comment by CosmoBro** [comment]
the @/targetBody2 is Kerbin (it says that in the config details after expressions) and now just removed the attribute and the requirement got met instantly.
Also I remember that the attribute was really working. I put 9d and that requirement doesn't got met until 9 days after that. I'll test with 1.5.0 to see if that is true. 
And this could be a good enhacement (cooldownDuration attribute avaiable to all requirements)

**Comment by jrossignol** [comment]
It would be possible only with the requirements that are based on the ProgressCelestialBodyTree, specifically:
* BaseConstruction
* Docking
* Escape
* FlyBy
* Landing
* Orbit
* Rendezvous
* ReturnFromFlyBy
* ReturnFromOrbit
* ReturnFromSurface
* SplashDown
* SurfaceEVA

I'll change this issue to track that, and add it to the 1.6.0 plan.

**Comment by jrossignol** [comment]
Sadly, I was wrong on this one - the date the node is achieved isn't available in the public API. :cry:
