### ISSUE TITLE
Some way to get the max thrust of an engine

### ISSUE THREAD

**Issue by CosmoBro** [jrossignol/ContractConfigurator#265]
To know where should be tested. For example a low thrust engine to test it on orbit, and a high thrust engine to test it on the launchpad.

**Comment by jrossignol** [comment]
Done.  You've got functions for atmosphere/vacuum thrust and ISP.

I'll try one last time to push you away from using thrust for this though.  Thrust is going to vary a lot based on the size classes, whereas ISP will vary more based on the engine's role.  Here's a sampling of some early vs mid-game engines, plus the ion thrown in for kicks:

| Engine | Primary Role | Atmo Thrust | Vac Thrust | Atmo ISP | Vac ISP |
| --- | --- | --- | --- | --- | --- |
| LV-T30 | Lifter | 200 | 215 | 280 | 300 |
| LV-909 | Space | 15 | 60 | 85 | 345 |
| Mainsail | Lifter | 1380 | 1500 | 285 | 310 |
| Poodle | Space | 65 | 250 | 90 | 350 |
| PB-ION | Space | 0.048 | 2 | 100 | 4200 |

As you can see, it's hard to use the thrust alone to get Poodle in the right category.  So you'd be far better off using either the atmo ISP to classify engines OR the ratio or Atmo/Vacuum values (either thrust or ISP, the ratio is the same).

**Comment by CosmoBro** [comment]
Nice! Thanks a lot and the ISP thing yeah it's better to do it that way
