### ISSUE TITLE
ORBITAL vs ORBITING

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#268]
https://github.com/jrossignol/ContractConfigurator/wiki/Orbit-Parameter mentions a situation ORBITAL. Are you sure that's correct? Shouldn't it be ORBITING?

**Comment by CosmoBro** [comment]
I think it should be ORBITAL because you're on an ORBITAL Situation not in an ORBIT situation

**Comment by jrossignol** [comment]
Don't have ksp handy to check the enum, but pretty sure @nathankell is
right as ReachState references the same type with the ORBITING value
listed.

**Comment by NathanKell** [comment]
If it's a parse of Vessel.Situation then ORBITING is correct. I noticed ORBITAL on a few wiki pages, actually, and didn't know if you had your own enum instead.

**Comment by jrossignol** [comment]
Did a quick grep and the Orbit parameter is the only one that I could find that was wrong.  Fixed now.

**Comment by NathanKell** [comment]
Dang, could have sworn I saw it elsewhere, sorry for over-worrying you. Well, grep will tell. :)
