### ISSUE TITLE
PartValidation Module field support

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#270]
It would be great if you could validate modules' fields as well as module presence themselves.
Consider this use case: launch a vessel with a gooExperiment on it.
There's two ways to do it now, both suboptimal (IMO):
1. PartValidation for all parts that the contract creator a priori knows have goo experiments on them (doesn't support mod parts etc).
2. Require transmitting science from the goo experiment (this voids the experiment).

Now, this could be special-cased by adding hasExperiment to part validation. However, the general solution would allow much more complex uses, as I'm sure you can imagine.

**Comment by jrossignol** [comment]
This is good, I like this idea.  I get occasional part-related feature requests that don't fit well into PartValidation because they're simply too specialized - this will help cover off a lot of those.

**Comment by jrossignol** [comment]
Done for 1.5.4.  To filter on the mystery goo experiment, you would do the following:
```
PARAMETER
{
    name = PartValidation
    type = PartValidation

    FILTER
    {
        MODULE
        {
            name = ModuleScienceExperiment
            experimentID = mysteryGoo
        }
    }

    minCount = 1
}
```
