### ISSUE TITLE
a Tech.Parent() ? 

### ISSUE THREAD

**Issue by CosmoBro** [jrossignol/ContractConfigurator#282]
Is this posible or is already implemented? because nothing on the wiki

**Comment by jrossignol** [comment]
Not implremented.  I'll add for the next release.

**Comment by CosmoBro** [comment]
nice! thanks a lot

**Comment by jrossignol** [comment]
Done for 1.6.3.  Note that it's Tech.Parents() as tech nodes can have multiple parents.  I also exposed the AnyToUnlock() attribute, which says whether a tech node needs all its parents unlocked or just one to be eligible to be unlocked.

**Comment by CosmoBro** [comment]
Great!
