### ISSUE TITLE
Possible ContractTracker Issue

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#283]
From glilienthal on https://github.com/KSP-RO/RP-0/issues/187

Exception occured while saving ScenarioModule 'ContractVesselTracker':
System.InvalidOperationException: Operation is not valid due to the current state of the object
at System.Linq.Enumerable.FirstProtoPartSnapshot [0x00000] in :0 
at ContractConfigurator.Extensions+d__18.MoveNext () [0x00000] in :0 
at System.Linq.Enumerable.AnyUInt32 [0x00000] in :0 
at ContractConfigurator.ContractVesselTracker.OnSave (.ConfigNode node) [0x00000] in :0

**Comment by glilienthal** [comment]
Fyi, I am using KSP64 on linux, RO/RSS/RP-0 installed from CKAN with the newest version. This exception occured just after I impacted the moon and the vessel was destroyed. (On a contract "Impact the moon" which was not completed as I hit the moon at more than 10,000m altitude.)

**Comment by jrossignol** [comment]
Fixed by 49af256
