### ISSUE TITLE
Modify UnlockPart or ExperimentalPart to allow full-time unlocking of a single part regardless of tech tree state

### ISSUE THREAD

**Issue by 5thHorseman** [jrossignol/ContractConfigurator#289]
I would like to gift the player access (in the VAB/SPH) to a part upon completion of a contract, regardless of the state of the tech tree currently or into the future, without changing the state of the tech tree.

As the two part-unlocking behaviors stand now, I can either:
- Use ExperimentalPart to unlock the part upon contract ACCEPTANCE (which it too early for my purposes)
- Use UnlockPart to unlock both the part and the tech tree node (which gives the player access to all parts in that node, which is too much of a gift for my purposes)

**Comment by CosmoBro** [comment]
I've thinked on something that moves the part to another node that is already unlocked (maybe a CC created one?) and that should Unlock the part Maybe thit isn't possible but is an just an Idea

**Comment by 5thHorseman** [comment]
+CosmoBro that could work if you could do it on the fly. If the part was originally in an unlocked node, then the player could just buy it.

I suppose you could make the parts cost $999999999999999999 to unlock or something. I was considering that for the tech tree nodes (Make them cost 9999999999999 science).

**Comment by jrossignol** [comment]
Done for 1.6.4 - it'll be the ExperimentalPart variant, as KSP won't let you unlock a part for a node that isn't unlocked.

Moving the parts to another node is technically feasible...  but a lot more complicated than I was willing to go when another solution was available. :wink:

**Comment by jrossignol** [comment]
Here's the updated documentation in case you want to test early (just grab the ContractConfigurator.dll from the linked commit above)
<pre>
BEHAVIOUR
{
    name = ExperimentalPart
    type = ExperimentalPart

    // The name of the part to add/remove.
    //
    // Type:      <a href="AvailablePart-Type">AvailablePart</a>
    // Required:  Yes (multiples allowed)
    //
    part = largeSolarPanel
    part = cupola

    // When (or if) the part should be added as an experimental part.
    //
    // Type:      <a href="Enumeration-Type">ExperimentalPart.UnlockCriteria</a>
    // Required:  No (defaulted)
    // Values:
    //     DO_NOT_UNLOCK
    //     CONTRACT_ACCEPTANCE (default)
    //     CONTRACT_COMPLETION
    //     PARAMETER_COMPLETION
    //
    unlockCriteria = CONTRACT_ACCEPTANCE

    // If the unlockCriteria is set to PARAMETER_COMPLETION, the name of the
    // parameter that must be completed to trigger the part unlock.
    //
    // Type:      <a href="String-Type">string</a>
    // Required:  See above
    //
    unlockParameter = TheParameter

    // When (or if) the part should be removed as an experimental part.
    //
    // Type:      <a href="Enumeration-Type">ExperimentalPart.LockCriteria</a>
    // Required:  No (defaulted)
    // Values:
    //     DO_NOT_LOCK
    //     CONTRACT_ACCEPTANCE (default)
    //     CONTRACT_COMPLETION
    //     PARAMETER_COMPLETION
    //
    lockCriteria = CONTRACT_ACCEPTANCE

    // If the lockCriteria is set to PARAMETER_COMPLETION, the name of the
    // parameter that must be completed to trigger the part lock.
    //
    // Type:      <a href="String-Type">string</a>
    // Required:  See above
    //
    lockParameter = TheParameter
}
</pre>
