### ISSUE TITLE
Allow SpawnVessel to spawn a single part

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#290]
Enhance SpawnVessel to support spawning a single part as a vessel without a craft file.

**Comment by jrossignol** [comment]
Done for 1.6.5, updated documentation follows:

<pre>
BEHAVIOUR
{
    name = SpawnVessel
    type = SpawnVessel

    // Use this to defer the creation of the vessel until the flight scene is
    // loaded.  This works around the issue that the vessel is initially loaded
    // in the actual VAB building, and if the vessel is too big will be visible
    // as it clips outside the VAB.  However, vessels with certain parts (the
    // RTG for sure) fail on a resource exception when loaded - loading them
    // earlier works around the issue slightly.  This is a stock bug that will
    // hopefully be fixed in the near future (the problem exists in KSP 1.0.4
    // for sure).
    //
    // Type:      <a href="Boolean-Type">bool</a>
    // Required:  No (defaulted)
    // Default:   false
    //
    deferVesselCreation = false

    // The VESSEL node indicates a vessel to spawn and can be specified
    // multiple times.
    VESSEL
    {
        // If the name is not supplied, defaults from the name within the
        // craft file.  Note that this name behaves like the
        // VesselParameterGroup define field - in other words, you may
        // refer back to this vessel by this name in <a href=VesselParameterGroup-Parameter>VesselParameterGroup</a>
        // parameters.
        //
        // Type:      <a href="String-Type">string</a>
        // Required:  No (defaulted)
        //
        name = A vessel

        // Path to the .craft file (relative to the GameData/ directory).
        //
        // Type:      <a href="String-Type">string</a>
        // Required:  Yes (unless craftPart is supplied)
        //
        craftURL = ContractConfigurator/Little Rocket.craft

        // The name of a single part build the craft from.  Note that spawning
        // height does not get properly detected when using this method, so a
        // manual height may need to be supplied (using the height attribute.
        //
        // Type:      <a href="AvailablePart-Type">AvailablePart</a>
        // Required:  Yes (unless craftURL is supplied)
        //
        craftURL = ContractConfigurator/Little Rocket.craft

        // Location of the flag to use.  Uses the players flag for the current
        // game if not specified.
        //
        // Type:      <a href="String-Type">string</a>
        // Required:  No (defaulted)
        //
        flagURL = Squad/Flags/satellite

        // The type of vessel (affects display in the tracking station).
        //
        // Type:      <a href="Enumeration-Type">VesselType</a>
        // Required:  No (defaulted)
        // Values:
        //     Base
        //     Lander
        //     Probe
        //     Rover
        //     Ship (default)
        //     Station
        //     Unknown
        //
        vesselType = Rover

        // Whether the vessel should show up as owned or unowned.  If it is
        // owned, then it will be immediately selectable.
        //
        // Type:      <a href="Boolean-Type">bool</a>
        // Required:  No (defaulted)
        // Default:   false
        //
        owned = False

        // Where the vessel should spawn - defaulted from the contract if
        // not supplied.
        //
        // Type:      <a href="CelestialBody-Type">CelestialBody</a>
        // Required:  No (defaulted)
        //
        targetBody = Kerbin

        // The ORBIT node indicates the orbit the vessel is in.  The
        // easiest way to get this information is to create the orbit
        // you want in KSP (using HyperEdit or good old fashioned
        // rocket science), and save your game.  In the persistant.sfs
        // file, search for your craft, and find the ORBIT node.
        //
        // Note that REF represents the reference body - but will be
        // overriden by the targetBody.
        // 
        // The ORBIT node is not used for landed vessels.
        ORBIT
        {
            SMA = 1449999.99996286
            ECC = 1.07570816555399E-05
            INC = 0
            LPE = 270.690311604893
            LAN = 1.93635924563296
            MNA = 1.55872660382504
            EPH = 31.3999999999994
            REF = 1
        }

        // If you wish to specify a landed vessel, you must also 
        // supply the following values:

        // Specifies the location of the spawn point via lat/lon.
        //
        // Type:      <a href="Numeric-Type">double</a>
        // Required:  See above
        //
        lat = -0.096992729723051
        lon = 285.425467968966

        // Only applies to landed vessels, use to override the altitude.
        // If not supplied, defaults to the terrain altitude.
        //
        // Type:      <a href="Numeric-Type">double</a>
        // Required:  See above
        //
        alt = 67.6843734193826

        // Additional height that should be added to the vessel when spawning.
        // Use this when the location chosen doesn't seem to have the right
        // auto-calculated terrain height, or when using craftPart with larger
        // parts.
        //
        // Type:      <a href="Numeric-Type">float</a>
        // Required:  No, defaulted
        // Default:   2.5
        //
        height = 5.0

        // Specifies the heading of the vessel in degrees (0 = N, 90 = E...).
        //
        // Type:      <a href="Numeric-Type">float</a>
        // Required:  No (defaulted)
        // Default:   0.0
        //
        heading = 180.0

        // Specifies the roll of the vessel in degrees (positive = roll right).
        //
        // Type:      <a href="Numeric-Type">float</a>
        // Required:  No (defaulted)
        // Default:   0.0
        //
        roll = 45.0

        // Specifies the pitch of the vessel in degrees (positive is nose up)
        //
        // Type:      <a href="Numeric-Type">float</a>
        // Required:  No (defaulted)
        // Default:   0.0
        //
        pitch = 30.0

        // A CREW node indicates one or more crew members to add to the
        // vessel.  The CREW node may be specified multiple times.
        CREW
        {
            // Name for the crew member - if not provided, one is
            // auto-generated.
            //
            // Type:      <a href="String-Type">string</a>
            // Required:  No
            //
            name = Patrick R. Kerman

            // Whether or not the Kerbal should be added to the roster on 
            // recovery.
            //
            // Type:      <a href="Boolean-Type">bool</a>
            // Required:  No (defaulted)
            // Default:   true
            //
            addToRoster = True

            // Number of crew to generate from this node.  Shouldn't be
            // supplied if name is supplied.
            //
            // Type:      <a href="Numeric-Type">int</a>
            // Required:  No (defaulted)
            // Default:   1
            //
            count = 1
        }
    }
}
</pre>

**Comment by 5thHorseman** [comment]
I was able to figure it out, but note the "craftPart" documentation is incorrect. It still refers to a .craft file location.

**Comment by 5thHorseman** [comment]
Maybe I didn't figure it out. The contract runs but it does not spawn the part. The below code generates a contract, and I can accept it, but when I do there is no part in map mode. In the accepted contract it says in Objectives "Rendezvous: Some Sort Of Container (TBD) and any vessel"

Why is it TBD? How can I make it be actually D? :D

[code]CONTRACT_GROUP
{
    name = Scavenger Tech
    displayName = Scavenger Tech
    minVersion = 0.7.0
    maxSimultaneous = 5
}

CONTRACT_TYPE
{
	name = fuelTank_long
	group = Scavenger Tech
	title = We Found A Part!
	description = We've located a part. Send a vessel out there and we'll see what we find.
	notes = Complete the following:
	synopsis = Recover the located part.
	completedMessage = Well done! We're already hard at work replicating that part. You'll be albe to use it on the next missin for sure.
	agent = Hardly Meager Vessel Parts
	minExpiry = 0
    maxExpiry = 0
	cancellable = true
	declinable = true
	autoaccept = false
	prestige = Trivial
	targetBody = Kerbin
	maxCompletions = 2
	maxSimultaneous = 2
	rewardScience = 0.0
	rewardReputation = 0.0
	rewardFunds = 0
	advanceFunds = 0
	weight = 999
	
	BEHAVIOUR
	{
		name = Some Sort Of Container
		type = SpawnVessel
		craftPart = fuelTank_long
		vesselType = Unknown
		targetBody = Kerbin
		lat = 0.0
        lon = 285.4
	}

	PARAMETER
	{
		name = Rendezvous
		type = Rendezvous	 
		vessel = Some Sort Of Container
		distance = 10.0
	}
	BEHAVIOUR
	{
		name = ExperimentalPart
		type = ExperimentalPart
		part = fuelTank_long
		unlockCriteria = CONTRACT_COMPLETION
		lockCriteria = DO_NOT_LOCK
	}
}[/code]

**Comment by jrossignol** [comment]
Thanks, fixed the documentation for release.

Unless something's messed up in my validation code, you should be getting warnings about unexpected attributes in your SpawnVessel.  I've just fixed it to add even more validation for the specific issue you've got - which is not having a VESSEL sub-node (the stuff that's supposed to be there is in your BEHAVIOUR node instead).  Here's what it should be changed to:
```
BEHAVIOUR
{
    type = SpawnVessel

    VESSEL
    {
        name = Some Sort Of Container
        craftPart = fuelTank_long
        vesselType = Unknown
        targetBody = Kerbin
        lat = 0.0
        lon = 285.4
    }
}
```

**Comment by 5thHorseman** [comment]
Thank you. And duh. I r dubm.
