### ISSUE TITLE
Spaces in lists of parts (at least) affect expected part names.

### ISSUE THREAD

**Issue by 5thHorseman** [jrossignol/ContractConfigurator#292]
If (as the documentation suggests) you put spaces after a part name and the comma or bracket, the part name will contain the space and therefore be an invalid part.

	DATA
	{
	type = AvailablePart
	thePart = [ fuelTankSmallFlat , liquidEngine ].Random()
	}

fails but

	DATA
	{
	type = AvailablePart
	thePart = [ fuelTankSmallFlat, liquidEngine].Random()
	}

works

**Comment by jrossignol** [comment]
Done for 1.6.5.
