### ISSUE TITLE
Duration in ReachState

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#304]
Doesn't seem to work for RP-0 contracts. It's listed in the parameter, but it completes as soon as the state is reached.
Example (that Scott Manley just demonstrated): https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/X-Planes/CrewedFlight.cfg#L90

**Comment by jrossignol** [comment]
You're doing it wrong!  The Duration parameter isn't supposed to be a child parameter.

*However*...   this is about the fourth time I've seen this mistake, and the other ways to do what you're trying to do are...  ugly at best.  So I think it's time to change this up a bit - I'm going to see if I can make the Duration parameter work in this way - I think it should be possible, and it'll simplify contracts like this a lot.

**Comment by NathanKell** [comment]
Aha. I know I copied it from an example, but evidently they were using it wrong too ^_^

**Comment by NathanKell** [comment]
Meanwhile: Is it that the parent/child should be swapped, or are they all on the same level, or...?

**Comment by jrossignol** [comment]
it's supposed to be at the same level.  But if you put it at the same level, when you try to land for the ReturnHome parameter, the ReachState will become incomplete again, preventing you from finishing the contract.  So you end up having to move the ReturnHome into another VesselParameterGroup and "link" them by having the first "define" the vessel and the second one umm...  "vessel" the vessel (okay, the attribute names aren't great).

So you can see why changing it to work the way you want it to is appealing - the alternative is a bit clumsy to configure, and isn't necessarily easy to understand for the player either.

**Comment by NathanKell** [comment]
Ah. Yeah. Yep, can indeed. I guess I won't try to mess with it at the moment then...

**Comment by jrossignol** [comment]
I should be able to get the fix done shortly, and I'm planning another release in the next couple of days.  So shouldn't be too bad of a wait.

**Comment by NathanKell** [comment]
No worries. :)

**Comment by jrossignol** [comment]
Done for 1.7.0
