### ISSUE TITLE
Request: invisible parameters 

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#305]
Don't know if this is possible (or advisable) but I'd like to set some parameters that are hidden to the player.

My reasoning is, that I'd like to trigger dialog boxes, which appear when (for Example) a passenger is loaded onto a craft, but the player doesn't necessarily need to know that the parameter is there as they would trigger it automatically when the passenger is loaded

**Comment by jrossignol** [comment]
On mobile at the moment so can't provide a link, but there should be a
hidden flag you can use. Look at the parameter page.

**Comment by severedsolo** [comment]
If you mean hidechildren - which is all I can see (but may be being blind) - not exactly what I want. That will still present some kind of parameter in mission control I believe, the details will just be hidden. I don't want the player to know this is there at all.

**Comment by jrossignol** [comment]
Huh, you're right.  I have everything for hiding in the code because of hideChildren, but there's no actual way to hide it.

Workaround - anything with a blank title will be hidden.  So put all your special parameters under an All or Any parameter with the title set to blank and hideChildren=true.  That should accomplish what you need.

**Comment by severedsolo** [comment]
You lie ;) 
...
name = Any
type = Any
title =
...
Will give you an error that title cannot be blank. No worries though, I can work around it for now.

**Comment by jrossignol** [comment]
Oh.... oops. :wink: 

Well, if you were able to make it blank, it would disappear.  Anyway, shouldn't be a big change, and I want to do a 1.7.1 release pretty quick anyway to get that one exception that came up in the thread squared away.

**Comment by jrossignol** [comment]
New attribute is called "hidden".  Set to true for all your hiding needs.
