### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#311]
Dug through the wiki, didn't see anything on this. Is it possible to round doubles? I.e. I want to pick a random speed between 400m/s and 600m/s in 10m/s chunks.

**Comment by jrossignol** [comment]
I think I was going to add some stuff in 1.8.0 based on #45.  I can definitely add this in earlier though, since they're pretty easy.  At the moment you'll have to do something like this:
```
DATA
{
    type = int
    speedIncrement = Random(40, 60)
}

DATA
{
    type = double
    speed = speedIncrement * 10
}
```

**Comment by NathanKell** [comment]
Cool. No biggie, RP-0 has survived this long with infinitely precise requirements, so it can survive a while longer. I was just going back through some contracts and remembered I'd meant to ask about this. :)

**Comment by jrossignol** [comment]
Done for 1.7.3.  Documentation preview:

| [`numeric`](Numeric-Type) `Round(`[`numeric`](Numeric-Type)` value)` | Rounds the number to the nearest full integer value (uses bankers rounding). |
| [`numeric`](Numeric-Type) `Round(`[`numeric`](Numeric-Type)` value, `[`numeric`](Numeric-Type)` precision)` | Rounds the number to the nearest multiple of `precision`.  For example `Round(113.0, 5.0)` would return `115.0`. |
