### ISSUE TITLE
More duration stuff

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#312]
I apparently am still not implementing duration correctly.

Consider a ReachState followed by a Duration. When I have disableOnStateChange = true set for the ReachState, the Duration will increment even when you leave the state. When I don't have that set, the ReachState goes false once you leave the state, even after you complete the Duration. Is there a way, short of putting them both inside an All (and having disableOnStateChange = false for the ReachState, but true for the All), that it will work as desired?

**Comment by jrossignol** [comment]
Assuming this is for the record contracts (speed, altitude, whatever).  In that case I think you definitely do want disableOnStateChange = false for the ReachState - that should be the mechanism by which it stops counting.

So I think all I need to do is for each duration "tick", do another check of the pre-requisites, and if they are unmet, reset the timer back to the start position.  Let me play around with this a bit tonight.

Do you have either a config you can link or a snippet you can post?  I just want to be sure that we're talking about the same thing. :wink:

**Comment by NathanKell** [comment]
It's actually for the X-Plane contracts; record contracts just check you're there once ever.
Yeah, I totally should have posted an example, sorry. Here you go:
https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/X-Planes/CrewedSupersonic.cfg#L53-L74

**Comment by jrossignol** [comment]
Hmmm....  ran a scaled down test and it worked for me (without the disableOnStateChange on ReachState though).

In my test I simplified it to be just state = FLYING and used hyperedit's landing function to put a capsule in the air.  While the capsule was in the air, the timer was counting down, but when it landed it reset back to 3:00.  I could repeat this as many times as I wanted to.

AH, and talking through that now I realize what the problem is...  now you can't do the ReturnHome with that setup.  Okay, need to think on this.

**Comment by NathanKell** [comment]
What's working right now is All with disableOnStateChange { reachstate , duration }. That models the desired behavior: As soon as the duration is completed, the collection of (state + duration) completes and you can move on with the contract (and leave the state). I don't see how to get that without encasing both in a change-disabled All, however.
(That behavior models the duration-inside-state misunderstanding of prior behavior, i.e. the duration is a qualifier for the reachstate, and the collection of (that state, for that duration) will only become true once you've been in that state for that duration, but once you *have*, you can leave the state and the (collection) is still true.)

**Comment by NathanKell** [comment]
Example (same file, but after the latest commit):
https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/X-Planes/CrewedSupersonic.cfg#L52-L80

**Comment by jrossignol** [comment]
The duration-inside-state misunderstanding is now supported... and is what works best in my testing.  The All container has the drawback that the All will stay checked even if you switch vessels.  This way worked perfectly:

* VPG
  * HasCrew
  * ReachState (disableOnStateChange = true)
    * Duration 
  * ReturnHome

I should mention that disableOnStateChange is special for Vessel parameters - it will disable on a vessel per vessel basis.  So if you complete the flight and then crash, the next vessel will have the contract look like it is "reset" to the initial state.

**Comment by jrossignol** [comment]
So yeah...   back to how you originally had it. :cry:

**Comment by NathanKell** [comment]
Hah! Ok, will do. :)
Thanks!
