### ISSUE TITLE
hidden and hideChildren not hiding parameters

### ISSUE THREAD

**Issue by 5thHorseman** [jrossignol/ContractConfigurator#314]
PARAMETER
	{
		type = VesselParameterGroup
		title = Get the ENTIRE station on the ground. If a couple parts burn off or explode it shouldn't be a big deal, but we need at least ONE of every part the station started with.
		hideChildren = true
		PARAMETER
		{
			type = ReturnHome
			hidden = true
		}
		PARAMETER
		{
			type = PartValidation
			part = batteryBank
			hidden = true
		}
		PARAMETER
		{
			type = PartValidation
			part = advSasModule
			hidden = true
		}
	... (and about 20 more)
	}
Neither one of those (hidden or hideChildren) is not actually hiding the parameters, whether I use them individually or together.

**Comment by jrossignol** [comment]
The fact that a parameter was supposed to be hidden was never being written out to the persistence file.  Whoops!

Fixed for 1.7.3
