### ISSUE TITLE
Sigma Binary Support

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#317]
Add support for Sigma Binary.  It allows adding barycenters, so a typical planetary hierarchy will look like this:
```
Sun
 \- DunaIke
      |- Duna
      \- Ike
```
So this will need to:
 * [ ] Not include the barycenter "body" in the various lists of bodies.  They are 1m radius planets, so this can be done by eliminating anything below a radius threshold.
 * [ ] Figure out what is a planet vs. moon when the parent is a barycenter.  Probably just pick the one with the highest mass as the planet.  Could maybe do "co-planetary" systems if they are close enough in mass.

**Comment by Sigma88** [comment]
hi there
I had never seen there was an issue open for sigmabinary :)
feel free to contact me if you need any info about my mod

and by the way, the binary system works like this:

Sun
 \- DunaIke
       \- Duna
            \- Ike

**Comment by Sigma88** [comment]
there is a strange issue that comes up when using radius = 1

I may need to change it to radius = 61

just a heads up, nothing sure yet

**Comment by jrossignol** [comment]
Done for 1.7.4.  I used radius = 100 as the threshold for "not a real planet".

**Comment by Sigma88** [comment]
:+1:
