### ISSUE TITLE
Allow Message behaviour to fire on CONTRACT_ACCEPTED

### ISSUE THREAD

**Issue by NoriSilverrage** [jrossignol/ContractConfigurator#320]
Please allow message behaviour to be able to fire on CONTRACT_ACCEPTED

**Comment by jrossignol** [comment]
Done for 1.7.4, you can grab the dev version [here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true) to test it out.
