### ISSUE TITLE
Duration rounding

### ISSUE THREAD

**Issue by ctiberious** [jrossignol/ContractConfigurator#321]
I see from the wiki that we can generate random durations, and can even specify whether those durations are in y, d, h, m or s.  But can't seem to find any way to round durations.  For instance, if I wanted a random number of whole hours.  Any possibility something like that could be added?

**Comment by jrossignol** [comment]
You actually can, due to the fact that you can cast a Duration to a double (although, not very explicitly):
```
    DATA
    {
        type = Duration

        unrounded = Random(2d, 10d)
        precision = 1d
    }

    DATA
    {
        type = double

        roundedDouble = Round(@unrounded, @precision)
    }

    DATA
    {
        type = Duration

        rounded = @roundedDouble
    }
```
Anyway, I'll keep this open and try to provide a "native" version of the round method for Duration so there's fewer hoops to jump through to do this.

**Comment by jrossignol** [comment]
Added for 1.7.5

**Comment by ctiberious** [comment]
Awesome, awesome and more awesome.
