### ISSUE TITLE
Add some string functions

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#336]
Stuff like:
* Contains()
* StartsWith()
* EndsWith()

**Comment by jrossignol** [comment]
Done for 1.8.0

**Comment by jrossignol** [comment]
By the way @severedsolo, I didn't get a chance to test these out, but they were super simple, and I assume you'll probably look at it before release.  Let me know here if you have any issues!

**Comment by severedsolo** [comment]
I will take a look. I'm working on [K-Files](https://github.com/severedsolo/ContractPackKFiles) at the moment (nearly done) but I'm going to move on to the rescue stuff afterwards.
