### ISSUE TITLE
HasNotPassengers parameter desired

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#339]
A simple HasNotPassengers parameter  to check to see if passengers have been unloaded, would make for completing transportation contracts more of a reality. See: http://forum.kerbalspaceprogram.com/threads/101604-1-0-5-Contract-Configurator-v1-8-0-2015-11-09?p=2293609&viewfull=1#post2293609

**Comment by jrossignol** [comment]
Since this is just the inverse of HasPassengers, decided to solve it a different way.  There is now a Not parameter (which is a variant of the None parameter, except it doesn't cause the contract to fail).  So what you need instead of HasNotPassengers is:
```
PARAMETER
{
    type = Not

    PARAMETER
    {
        type = HasPassengers
        ...
    }
}
```
Let me know if anything about this doesn't work as expected.

**Comment by jrossignol** [comment]
Full documentation for new parameter:



The Not parameter inverts the state of its child parameter.  This frequently is used with the completeInSequence flag.

<pre>
PARAMETER
{
    name = Not
    type = Not

    // The text to display.  Highly recommended not to use the default text, as
    // when the parameter is complete the text of the children disappears (and
    // the default text doesn't give the player a very good idea what the
    // parameter was about).
    //
    // Type:      <a href="String-Type">string</a>
    // Required:  No (defaulted)
    // Default:   Is not true
    //title =

    // Generally need completeInSequence set to true for the Not parameter.
    // See the <a href=Parameters>Parameters</a> page for more details.
    completeInSequence = true

    PARAMETER
    {
        name = ReachState
        type = ReachState

        situation = LANDED
    }
}
</pre>

**Comment by inigmatus** [comment]
Schweet! Thank you! Will test sometime tonight late. You just made a large number of missions possible with this not parameter.  Thanks again!

**Comment by inigmatus** [comment]
With the current development version of 1.8.1 CC, I tested: 

//Air Shuttle Contract to KSC Island

CONTRACT_TYPE
{
	name = BugTest
    title = Bug Test
    group = AirShuttle
	agent = KSC Air Shuttle
   
    description = Bug Test.
	
	synopsis = Bug Test.
	completedMessage = Bug Tested!

    minExpiry = 7.0
    maxExpiry = 7.0
	deadline = 0
	cancellable = true
	declinable = false
    autoAccept = false
	
	prestige = Trivial

   	targetBody = Kerbin

   	maxCompletions = 0
   	maxSimultaneous = 1

 	rewardScience = 5.0
  	rewardReputation = 5.0
  	rewardFunds = 10000.0
 	failureReputation = 20.0
  	failureFunds = 20000.0
  	advanceFunds = 5000.0
	weight = 1.0
	
	PARAMETER
	{
		name = ReachState
		type = ReachState
		situation = FLYING
		minSpeed = 100
		disableOnStateChange = false
	}
	
	PARAMETER
	{
		name = Not
		type = Not
		completeInSequence = true
		disableOnStateChange = false
		
		PARAMETER
		{
			name = HasPassengers
			type = HasPassengers
			completeInSequence = true
			disableOnStateChange = false
		}
	}
	
	BEHAVIOUR
	{
		name = SpawnPassengers
		type = SpawnPassengers
		count = 1
		passengerName = 
		kerbalType = Unowned
	}	
}

Interesting behavior. The nested HasPassengers does not list the Kerbal names in the Contract pop up checklist but rather simply the number of passengers.

**Comment by jrossignol** [comment]
Don't include blank attributes. The empty passengerName tag might be your
problem.

**Comment by jrossignol** [comment]
Nevermind, took another look, what's happening is that the parameter is set to complete because of the way I coded it (it's ignoring the completeInSequence attribute).  Fixing that now.

**Comment by jrossignol** [comment]
Fixed.

**Comment by inigmatus** [comment]
testing..,

**Comment by inigmatus** [comment]
Tested: When passenger is not loaded, their name appears in the contract drop down, but when the passenger is loaded (after the popup to load passengers on the runway), the name disappears and the contract drop down says  Passengers: 1  - is there a way to get this to still say On Board: Bug Kerman, rather than a summary Passengers: 1?

//Air Shuttle Contract to KSC Island

CONTRACT_TYPE
{
	name = BugTest
    title = Bug Test
    group = AirShuttle
	agent = KSC Air Shuttle
   
    description = Bug Test.
	
	synopsis = Bug Test.
	completedMessage = Bug Tested!

    minExpiry = 7.0
    maxExpiry = 7.0
	deadline = 0
	cancellable = true
	declinable = false
    autoAccept = false
	
	prestige = Trivial

   	targetBody = Kerbin

   	maxCompletions = 0
   	maxSimultaneous = 1

 	rewardScience = 5.0
  	rewardReputation = 5.0
  	rewardFunds = 10000.0
 	failureReputation = 20.0
  	failureFunds = 20000.0
  	advanceFunds = 5000.0
	weight = 1.0

//To prevent contract completion during runway test of HasPassengers parameter	
	PARAMETER
	{
		name = ReachState
		type = ReachState
		situation = FLYING
		minSpeed = 100
		disableOnStateChange = false
	}

//Not HasPassengers Check	
	PARAMETER
	{
		name = Not
		type = Not
		completeInSequence = true
		disableOnStateChange = false
		
		PARAMETER
		{
			name = HasPassengers
			type = HasPassengers
			completeInSequence = true
			disableOnStateChange = false
		}
	}

//Normal HasPassegers check
	PARAMETER
	{
		name = HasPassengers
		type = HasPassengers
		completeInSequence = true
		disableOnStateChange = false
	}
	
	BEHAVIOUR
	{
		name = SpawnPassengers
		type = SpawnPassengers
		count = 1
		passengerName = Kremlin Kerman
		kerbalType = Unowned
	}	
}

**Comment by jrossignol** [comment]
There isn't. It's stock behaviour to hide children of completed parameters.

**Comment by inigmatus** [comment]
Is there a way to reference the names of the onboard passengers and their loaded state in the contract  status window without requiring it for contract completion? Sort of like an Ignore parameter so it can display status info for various parameters in the contract status?  I can submit it as an enhancement if required.

**Comment by jrossignol** [comment]
I'm not 100% clear on what you're looking for, but it sounds overly complex. :wink: 

Generally how I handle it is using appropriate custom titles for top-level parameters when necessary (such that the parameter is still clear when collapsed).  Alternatively, in some cases, the code will pick up the details for the child parameters and add it to the title of the top level parameter.  I don't really want to do that with passenger names because it gets big fast.  If it sufficient, I can make it do that for when there's only one passenger.

**Comment by inigmatus** [comment]
Don't sweat it. Its a limit in KSP. Would most likely would require some major coding like Contracts Plus to show persistent parameter statuses. Thanks for your hard work on this enhancement.  It works great!
