### ISSUE TITLE
KerbalDeaths - add title attribute

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#342]
KerbalDeaths title attribute is not working. Either bug or enhancement.

	PARAMETER
	{
		name = All
		type = All
		title = Recover

		PARAMETER
		{
			name = RecoverVessel
			type = RecoverVessel
			title = your airplane
		}
		
		PARAMETER
		{
			name = VesselNotDestroyed
			type = VesselNotDestroyed
			title = without destroying it
		}
		
		PARAMETER
		{
			name = KerbalDeaths
			type = KerbalDeaths
			title = or killing your volunteer pilot
			countMax = 1
		}
		
	}

**Comment by jrossignol** [comment]
Didn't actually test this one, but 99% sure it'll work since it's just a simple wrapper around the stock parameter.  Let me know if there's any issues.

Fixed for 1.8.2.

**Comment by inigmatus** [comment]
I'll add to my test schedule. Thanks!

**Comment by inigmatus** [comment]
tested. works beautifully.
