### ISSUE TITLE
Enhancement to include check for if exists in loaded part list, else ignore PartUnlocked requirement

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#344]
Currently this bugs out and kills the contract loading if I don't have Kerbal Aircraft eXpansion parts installed in my GameData.  Essentially trying here to require either jet engine or KAX propeller part access before making available the first SSI-Aerospace contract.

	REQUIREMENT
	{
		name = Any
		type = Any

		REQUIREMENT
		{
			name = PartUnlocked
			type = PartUnlocked
			part = JetEngine
		}

		REQUIREMENT
		{
			name = PartUnlocked
			type = PartUnlocked
			part = KAXsportprop
		}
	}

An enhancement to run this check for all part checking parameters and requirements would probably be necessary to keep this expected logic consistent for developers.

**Comment by jrossignol** [comment]
Use module manager for this:
```
REQUIREMENT
{
    name = Any
    type = Any

    REQUIREMENT
    {
        name = PartUnlocked
        type = PartUnlocked
        part = JetEngine
    }

    REQUIREMENT:NEEDS[KAX]
    {
        name = PartUnlocked
        type = PartUnlocked
        part = KAXsportprop
    }
}
```

You'll have to confirm it's actually KAX and not KerbalAircraftExpansion (it'll be whatever the top-level directory of KAX is).
