### ISSUE TITLE
prestige = Exceptional not recognized?

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#345]
When I set a contract to 

prestige = Exceptional

It fails to ever appear in the list of available contracts. Even with stock contracts disabled. Trivial and Significant show up.

**Comment by jrossignol** [comment]
Most likely you need to increase your reputation.  The way the stock system works with the starting reputation (zero), you don't get any 3-star contracts (with the exception of some that the system forces to appear).
