### ISSUE TITLE
Orbital Parameters as expressions

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#346]
As we discussed on the forum can we get the orbital parameters as a double?

I'm specifically looking for Periapsis at the moment, but it would make sense to add the AP at the same time, possibly inclination? (not quite sure how KSP stores the orbit info)

**Comment by jrossignol** [comment]
This will depend on what I can easily get from an unloaded vessel.  Hopefully all the expected stuff like inclination and eccentricity should be easy.

**Comment by jrossignol** [comment]
Adding these four methods to Vessel:

| Method Signature | Description |
| :--- | :--- |
| [`double`](Numeric-Type) `OrbitApoapsis()` | The apoapsis of the vessel's orbit. |
| [`double`](Numeric-Type) `OrbitPeriapsis()` | The periapsis of the vessel's orbit. |
| [`double`](Numeric-Type) `OrbitInclination()` | The inclination of the vessel's orbit. |
| [`double`](Numeric-Type) `OrbitEccentricity()` | The eccentricity of the vessel's orbit. |

**Comment by jrossignol** [comment]
Done for 1.8.2
