### ISSUE TITLE
Duration timer resetting on scene change.

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#347]
I presume it's duration anyway:

Specifically noticed it on the Remote Tech 4 sat mission - it's resetting to 2 days every time I change scene. (specifically, noticed it happening going from flight scene to space centre, and vice versa)

**Comment by jrossignol** [comment]
I can't remember if VesselParamterGroup now uses the Duration timer or if it has its own implementation, I'll have to double check that.

Also, can you confirm this is on 1.8.1?

**Comment by severedsolo** [comment]
Yup 1.8.1 - (may actually be the dev version of 1.8.2 - I can't remember whether I uninstalled it or not, but the CC menu says it's 1.8.1)

**Comment by jrossignol** [comment]
The timer isn't supposed to stop in the space centre scene - as time is still moving in that scene.  In the VAB/SPH it should stop.

**Comment by jrossignol** [comment]
Fixed for 1.8.2
