### ISSUE TITLE
Duplicate contracts - uniqueValue not being honoured

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#348]
From severedsolo on the [RemoteTech contract pack thread](http://forum.kerbalspaceprogram.com/showthread.php?p=2303858#post2303858):

> I'm getting duplicate "create a network for Mun" contracts (duplicate offered that is, I haven't accepted them)

**Comment by jrossignol** [comment]
I made some changes to the pre-loader system, but still haven't been able to reproduce this.

@severedsolo - Are you able to re-test this on the dev version and let me know if you're still seeing this?

**Comment by severedsolo** [comment]
I don't think it's CC actually. I was just looking through the files:
On the one hand you have PlanetMoonRelay: 
```descDefault = They say there's no point to setting up a relay for @targetMoon.  We say otherwise!  Set up a communication network for us.```

What I'm seeing as a "duplicate" is MoonRelay which says:
```descMinmus = They say that Minmus is too small to bother with setting up a dedicated communications network.  Let's prove them wrong!```

So I think your problem is that PlanetMoonRelay should be ignoring Minmus?

**Comment by jrossignol** [comment]
Ah! So PlanetMoonRelay is picking up Kerbin when it shouldn't.  Okay, well that confirms that Contract Configurator itself is working.

Raised https://github.com/jrossignol/ContractPack-RemoteTech/issues/16
