### ISSUE TITLE
Waypoints don't flash when in range

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#352]
As we discussed on the forum:

Waypoints generated for VisitWaypoint don't emulate standard stock behaviour.

Ie; if you have waypoint manager installed, they should flash when you are in range.

**Comment by jrossignol** [comment]
This is actually stock, not Waypoint Manager that does the flashing. :)

**Comment by jrossignol** [comment]
For my own reference, the messages are posted via:
```
ScreenMessages.PostScreenMessage(msg, 5.0f, ScreenMessageStyle.UPPER_CENTER);
```
The messages are:
> You are entering $wpName.
> You are leaving $wpName.

**Comment by jrossignol** [comment]
VisitWaypoint now supports a showMessages attribute (false by default):
```
   // Whether to show the "Entering/Leaving $waypointName." messages when a player gets within the
   // distance tolerance of the waypoint.
   //
   // Type:      <a href="Boolean-Type">bool</a>
   // Required:  No (defaulted)
   // Default:   false
   //
   showMessages = false
```
Field Research and Tourism will get updated, as the default value is false.
