### ISSUE TITLE
Feature Request: Contextual Contract Highlights

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#354]
Would it be possible to access the Contextual Contract targeting icons in map view/tracking station for CC purposes?

It would be cool if, say one of my KSS missions generated, and the vessel was highlighted in the same way as a contextual would be.

**Comment by jrossignol** [comment]
Oh yeah, I almost forgot about this, it was one of the few things for contextual contracts that I wanted to try to work in.  I'll put it for 1.8.2 for now, not sure how difficult the change required will be though.

**Comment by jrossignol** [comment]
![image](https://cloud.githubusercontent.com/assets/8717685/11326375/6d9bec94-9125-11e5-9b55-0561d9c227dc.png)

:wink:

**Comment by jrossignol** [comment]
Done for 1.8.2

**Comment by severedsolo** [comment]
Wonderful :D is there a flag I need to turn on, or is it automatic?

**Comment by jrossignol** [comment]
I couldn't see any reason to not show it, so it's automatic.  If you find a case where you want it turned *off*, let me know and I'll add a flag.
