### ISSUE TITLE
New parameter to check maximum g force on target vessel

### ISSUE THREAD

**Issue by topsailor** [jrossignol/ContractConfigurator#356]
It'll be nice if there's a way to limit maximum g force on target vessel. Can be applied to various situations: Tourism, Emergency, Cargo shipping. Also can introduce some difficulties to existing contracts by adding the parameter. Some tourists and patients may have difficult times with too much g force on them and also some precious cargo's might broken into pieces.

**Comment by jrossignol** [comment]
Should be fairly straightforward, since vessel acceleration is available in the API.  It'll be a new parameter and will support both minAcceleration and maxAcceleration (minAcceleration could be used for "record" contracts).

**Comment by jrossignol** [comment]
Done for 1.8.4.  Added this to ReachState instead of creating a new parameter.  Also added support for failWhenUnmet in ReachState (so you can cause the contract to fail if the exceed X gees).

**Comment by jrossignol** [comment]
Relevant documentation updates:

    // Minimum acceleration (in gees) that the vessel must be at.
    //
    // Type:      <a href="Numeric-Type">float</a>
    // Required:  No (defaulted)
    // Default:   0.0
    //
    minAcceleration = 0.0

    // Maximum acceleration (in gees) that the vessel must be at.
    //
    // Type:      <a href="Numeric-Type">float</a>
    // Required:  No (defaulted)
    // Default:   float.MaxValue
    //
    maxAcceleration = 5.0

    // Set to true to fail the contract if the vessel doesn't meet the
    // conditions.  Take care that the contract doesn't get written in such a
    // way that the player's other vessels cause the contract to faile (for
    // example, if you say "don't go above 10,000m, but the player has another
    // vessel in orbit, make sure that there are other parameters that prevent
    // the orbiting vessel from triggering the failure - the completeInSequence
    // is useful for this).
    //
    // Type:      <a href="Boolean-Type">bool</a>
    // Required:  No (defaulted)
    // Default:   false
    //
    failWhenUnmet = false
