### ISSUE TITLE
Add support to include .cfg files within a .cfg file for repeat code inclusion

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#357]
I would love to be able set up a specific function such as landing, coming to a stop, and recovering all kerbs, in a cfg file or function that I could then reference in all my other contracts that need it, so updating such a function doesn't involve me updating all my contracts that use it.

**Comment by jrossignol** [comment]
I had to give this some thought, but I think I can do it in a reasonable way.  How it'll work is that you will have the parts just as you would in a contract, but standalone:
```
PARAMETER
{
    name = TheParameter
    ...
}
```
Then, in the contract, I'd have a special tag that "expands" into the parameter:
```
CONTRACT_TYPE
{
    ...
    importParameter = TheParameter
    ...
}
```
...which would be automatically be expanded into:
```
CONTRACT_TYPE
{
    ...
    importParameter = TheParameter
    PARAMETER
    {
        name = TheParameter
        ...
    }
    ...
}
```
*No validation* would happen on the individual parameter - it'd still all be on the expanded contract.  So if the parameter is wrong and you have it in 100 places, then you'd see 100 errors. :wink:

**Comment by inigmatus** [comment]
Would this work for behaviors and other parts of CONTRACT_TYPE ?

**Comment by jrossignol** [comment]
Behaviors, parameters, requirements.

**Comment by inigmatus** [comment]
heh nevermind i get it. thanks! looking forward to it.

**Comment by inigmatus** [comment]
might want to add a check to ensure one doesn't accidentally create an import loop.

**Comment by jrossignol** [comment]
Of course. 😊

**Comment by inigmatus** [comment]
I'm thinking this is a low priority enhancement for me. I can't see a need for it now with my current contract set. If you want an enhancement to drop off the 1.8.4 table, this would be one I'd recommend.

**Comment by inigmatus** [comment]
Simply not needed. Feel free to keep this enhancement closed until desired.
