### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dcrockwell** [jrossignol/ContractConfigurator#358]
This is with the latest, `1.8.3`.

When clicking on the VAB, or on the "close" button in the top right of the contract select screen:

```
[EXC 21:10:02.725] NullReferenceException: Object reference not set to an instance of an object
	Contracts.Templates.PartTest.OnSave (.ConfigNode node)
	Contracts.Contract.Save (.ConfigNode node)
	Contracts.ContractSystem.OnSave (.ConfigNode gameNode)
	ScenarioModule.Save (.ConfigNode node)
	ProtoScenarioModule..ctor (.ScenarioModule module)
	ScenarioRunner.GetUpdatedProtoModules ()
	Game.Updated ()
	GamePersistence.SaveGame (System.String saveFileName, System.String saveFolder, SaveMode saveMode)
	MCSceneSpawner.onMCDespawn ()
	EventVoid.Fire ()
	MCDespawner.BtnExit (.POINTER_INFO& ptr)
	UIButton.OnInput (.POINTER_INFO& ptr)
	AutoSpriteControlBase.OnInput (POINTER_INFO ptr)
	UIManager.DispatchHelper (.POINTER_INFO& curPtr, Int32 camIndex)
	UIManager.DispatchInput ()
	UIManager.Update ()
	UIManager.DidAnyPointerHitUI ()
	SpaceCenterCamera2.InputCamera ()
	SpaceCenterCamera2.Update ()
```

**Comment by jrossignol** [comment]
The stack trace looks to be 100% related to stock stuff.  From the contract that's failing (PartTest), I'm going to guess that you may have had an active/offered/completed contract for a part that you no longer have (due to uninstalling a mod).

If that doesn't sound right, can you confirm whether rolling back or uninstalling Contract Configurator makes the error go away?

**Comment by dcrockwell** [comment]
That does sound about right. I was uninstalling and installing some new mods / upgrading.

Removing ContractConfigurator does not solve the problem. Same issue.

Do you know of a way to reset contracts so that I can salvage this save game?

**Comment by jrossignol** [comment]
Depends how scorched earth you want to go.  In the debug menu (alt-f12), under contracts there should be some buttons for clearing out contracts that you can use to clear out all your active and completed contracts.  This will mess with your save though, as you will have to re-complete some of the basic contracts.

Alternatively, if you're comfortable with save file editing, find the PartTest CONTRACT node with the part that is causing trouble, and delete the entire node.  If you're really not sure which part, then you can just kill all the PartTest CONTRACTs in the save.

**Comment by dcrockwell** [comment]
That worked perfectly. Thank you very much.
