### ISSUE TITLE
SpawnVessel Vessel PQS rather than just lat and long?

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#359]
Was wondering if it was possible to use PQS coords for SpawnVessel.

**Comment by jrossignol** [comment]
It's not possible, would be a relatively minor enhancement.

**Comment by jrossignol** [comment]
Done for 1.8.4

**Comment by inigmatus** [comment]
Tested and confirmed working. Great enhancement! Now contracts are fully RSS compatible.
