### ISSUE TITLE
Disable multiple contracts at once from CC Settings Menu

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#360]
With all this testing, it's getting a bit tedious to disable all the stock contracts individually. Possible to add a button to disable all stock contracts at once in the CC Settings menu?  Sorry to spam you with so many enhancements.  I'm vigorously testing the command seat bug. I think I found something...but I'll post in the bug report for it there.

**Comment by jrossignol** [comment]
This one I won't do, since you can do it via a config file.  See https://github.com/jrossignol/ContractConfigurator/wiki/Miscellaneous

**Comment by inigmatus** [comment]
ty!  the one part of the wiki i hadnt read yet. misc.
