### ISSUE TITLE
low priority bug - load passengers dialog not destroyed when no option selected, and player recovers craft

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#364]
the load passengers dialog does not destroy itself when someone clicks Recover. tested this while on runway, new loaded craft, was asked if i wanted to load passengers, clicked Recover instead. dialog box remained into Space Center view I think. I reported this in my change log as a KSP bug, but reading that you said the dialog is CC's, I'm opening this now for investigation. low priority.

**Comment by jrossignol** [comment]
Easy fix, done for 1.8.4

**Comment by inigmatus** [comment]
I think this fix is the cause of what I reported to you in

https://github.com/seanmcdougall/TakeCommand/issues/1

Where the popup is killed after the first Take Command kerbal is loaded. Your checking if vessel is launched as condition to kill the popup. Take command is somehow causing a launch in the example provided in that case which triggers the popup to close?  I think you could just remove the launch check altogether but keep the scene change check to fix this.

**Comment by jrossignol** [comment]
Don't currently have TakeCommand, I'll ask you to test this fix for me - it still works fine for stock, but I want to know if it has resolved the issue for you.

I need to keep the check in to prevent silliness like launching with the dialog up, and then loading passengers once you're in orbit.

**Comment by inigmatus** [comment]
Tested with Take Command. Perfect fix. Thanks, this can be closed. I'm so excited.
