### ISSUE TITLE
Improved Kerbal generation in contracts

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#366]
From @inigmatus:

> Any reason why
```
        CREW
        {
            addToRoster = false
            name = RandomKerbalName(Random())
        }
        CREW
        {
            addToRoster = false
            count = 1
        }
//this passes into DATA fine (and can be used in HasPassengers fine):
DATA
{
    type = string
    kerbal2 = @/TourBus.Kerbals().ElementAt(0)
}
//this fails with errors and is not passed into DATA (and thus can not be used in HasPassengers):
DATA
{
    type = string
    kerbal2 = @/TourBus.Kerbals().ElementAt(1)
}
```
> any reason why the second example Crew node is not passing the kerbal name to the DATA node?

and:

> Both DATA notes below (using latest dev build of CC as of this writing) fail to load in the corresponding CREW node kerbal name whenever a CREW node uses the count attribute. Neither can HasPassengers find anything in Kerbals() and thus fails to list names.
```
	BEHAVIOUR
	{
		name = TourBus
		type = SpawnVessel
		deferVesselCreation = false
		VESSEL
		{
			name = Tour Bus
			craftURL = ContractPacks/SSI-Aerospace/Assets/TouristBus.craft
			vesselType = Ship
			owned = True
			targetBody = Kerbin
			lat = -0.0544780548632459
			lon = 285.275492359036
			CREW
			{
				addToRoster = false
				name = RandomKerbalName(Random())
			}
			CREW
			{
				addToRoster = false
				count = 1
			}
		}
	}
	DATA
	{
		type = string
		kerbal1 = @/TourBus.Kerbals().ElementAt(0)
		kerbal2 = @/TourBus.Kerbals().ElementAt(1)
	}
	PARAMETER
	{
		name = HasPassengers
		type = HasPassengers
		name = @/TourBus.Kerbals().ElementAt(0)
		name = @/TourBus.Kerbals().ElementAt(1)
		disableOnStateChange = false
	}
```
> errors are:
```
[Error]: ContractConfigurator.ContractType: CONTRACT_TYPE 'BugTest': Error parsing kerbal1
[Exception]: NotSupportedException: Unsupported type: ContractConfigurator.Behaviour.SpawnVesselFactory
```
```
[Error]: ContractConfigurator.ContractType: CONTRACT_TYPE 'BugTest': Error parsing kerbal2
[Exception]: NotSupportedException: Unsupported type: ContractConfigurator.Behaviour.SpawnVesselFactory
```
> The above DATA node is really meant to capture the names of the Kerbals spawed by SpawnVessel/Crew for use in other places, such as use in HasPassengers.

> Now when I switch all CREW nodes to use RandomKerbalName shown below, instead of the count attribute above, the DATA node still can't seem to load the names into kerbal1 and kerbal2 (log spits out same exact errors above); but... HasPassengers can seemingly use Kerbal() to pull out the names for use in HasPassengers.  HasPassengers seems to work fine in this scenario so kludging together a work around is possible at this point. It remains messy though, since I will have to do your gender array suggestion that you shared in #355 to keep gender matching when using RandomKerbalName as a source for CREW node kerbal generation, and later reference by HasPassengers:
```
	BEHAVIOUR
	{
		name = TourBus
		type = SpawnVessel
		deferVesselCreation = false
		VESSEL
		{
			name = Tour Bus
			craftURL = ContractPacks/SSI-Aerospace/Assets/TouristBus.craft
			vesselType = Ship
			owned = True
			targetBody = Kerbin
			lat = -0.0544780548632459
			lon = 285.275492359036
			CREW
			{
				addToRoster = false
				name = RandomKerbalName(Random())
			}
			CREW
			{
				addToRoster = false
				name = RandomKerbalName(Random())
			}
		}
	}
	DATA
	{
		type = string
		kerbal1 = @/TourBus.Kerbals().ElementAt(0)
		kerbal2 = @/TourBus.Kerbals().ElementAt(1)
	}
	PARAMETER
	{
		name = HasPassengers
		type = HasPassengers
		name = @/TourBus.Kerbals().ElementAt(0)
		name = @/TourBus.Kerbals().ElementAt(1)
		disableOnStateChange = false
	}
```
> So yes, I get the same errors as above for the DATA node's variables kerbal1 and kerbal2, but this time HasPassengers is able to read names and list them in the contract parameters window.

> The idea I was shooting for was hoping that DATA and HasPassengers could use a syntax like @/TourBus.Kerbals().ElementAt(0) to reference crew spawned via SpawnVessel/Crew's count attribute. If so, I would not have to worry about gender matching since the Crew count attribute (I assume) does this already. All I would have to do is simply set Crew to count the number of Kerbals I want, and then reference the correct elements in Vessel.Kerbals() in HasPassengers to get those crew members to show up on the contract parameter list as a required passenger to pick up.

> Btw, thank you so much for answering all my questions. I was wondering if you'd like my Island Tour to Valentina's Cay be renamed after you. You sir, are amazing.

**Comment by jrossignol** [comment]
The first one fails because `@/TourBus` is not supported - the only ContractBehaviour objects that you can do that with (right now) are SpawnKerbal and WaypointGenerator (see the right hand pane on https://github.com/jrossignol/ContractConfigurator/wiki/Expressions).

The second issue (I mentioned this last night, but there were so many issues that I'm not going to go find the quote :wink: ), but I'd recommend *not* using HasPassengers here.  It's only useful for loading passengers on the runway/launchpad (documentation has been updated on that point).  Use HasCrew instead.

I've been thinking about this one, and I think I will make some changes (but not until tonight at the earliest, if not tomorrow).  The *goal* will be to change it so that something along these lines is possible:
```
DATA
{
    type = Kerbal
    kerbal1 = newKerbal()
    kerbal2 = newKerbal(FEMALE)
    kerbal3 = newKerbal(FEMALE, "Valentina Tereshkova Kerman")
    kerbal4 = newKerbal(Engineer)
    kerbal5 = newKerbal(MALE, "Gus Grissom Kerman", Pilot)
}
```
And then the kerbals can be referenced once (and it'll encapsulate all that info about them.  Then when the contract is accepted, they'll actually get added to the crew roster.  I need to dig into it though, don't know how challenging it will be.  Once I've taken a look into it, I'll post up the details here.

**Comment by jrossignol** [comment]
> Btw, thank you so much for answering all my questions. I was wondering if you'd like my Island Tour to Valentina's Cay be renamed after you. You sir, are amazing.

I'd be honoured if you want to name a geological formation after me. :+1:

**Comment by inigmatus** [comment]
Jeremy's Cay or Nightingale's Cay (the dockmaster that will spawn will also be Jeremy Kerman or Nightingale Kerman). 

I like the idea for a newKerbal() function. 

Would newKerbal() SpawnVessel/Crew members be removed from roster after contract completion? (desired).

**Comment by jrossignol** [comment]
Let's keep it to Nightingale.

The removal of the kerbal would work as before, based on the addToRoster attribute.  Although a RemoveKerbal might be an idea for the future.

**Comment by inigmatus** [comment]
Nightingale's Cay it is then. thanks for making this whole project fun and educational :)

**Comment by inigmatus** [comment]
If you do make a newKerbal(), I recommend also adding a:

BEHAVIOUR
{
     type = RemoveKerbal
     
      name = kerbal1
      OnState = CONTRACT_COMPLETION

}

This will effectively eliminate #373 #366 #355 and #353.

All of these just come down to the idea of being able to spawn a single temporary list of kerbals in various places and craft for simple transport, rescue, and recovery; and be able to reference those kerbals in parameters and dialogs.

**Comment by jrossignol** [comment]
There's still a few things I want to do with this one, but the bulk is done (use the example as a guide).  SpawnKerbal CREW nodes also support the kerbal attribute, so you can do `kerbal = @/kerbal1` for example.

I'll finish tomorrow, but figured you may want to play with this one a bit.

**Comment by inigmatus** [comment]
Thank you! I'll probably not get to testing it until tomorrow or Thursday. Hoping for a 1.8.4 weekend release so I can push out GAP 0.2 shortly after.

**Comment by jrossignol** [comment]
It's practically ready, this is the last change, so the weekend is likely.

Also, decided it'll be 1.9.0, since the number of new features has been
adding up. I'll update GitHub tags tomorrow.

**Comment by inigmatus** [comment]
fun. thanks for all your hard work. have a good night!

**Comment by jrossignol** [comment]
Done for 1.9.0

**Comment by inigmatus** [comment]
Looking forward to playing with this.

**Comment by inigmatus** [comment]
Tested. NewKerbal() works great.
