### ISSUE TITLE
PartTest not giving part test option

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#367]
I want to have a player test a batteryPack (or any part for that matter)

	PARAMETER
	{
		name = PartTest
		type = PartTest
		
		part = batteryPack
		
	}

Yet even though the part is on board the craft, there is no option when right clicking the part to test the part, thus the parameter can not complete. I tested this with batteryPack and roverWheel1.

Battery Pack is the Z-100 batteries.

**Comment by jrossignol** [comment]
I'll need to update the documentation for this.  For a part to work with PartTest, the part needs to have a `ModuleTestSubject`.  You can find out which do by looking at the .cfg file for the part.  It comes in two flavours, one with `useStaging = True` (think engines), and one with `useEvent = True` (the ones with the Run Test option).  There are a TON of other options, but those all have to do with the stock part test contracts.

You should in theory be able to add the module to any part that doesn't already have it using Module Manager.

**Comment by jrossignol** [comment]
Documentation updated.
