### ISSUE TITLE
Ability to Accept Negative Value in advanceFunds?

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#368]
I am looking to create a starter contract for my pack which would:

- Require 65% of a player's available funds, but no more than 500,000 funds. (so require a funds withdrawal on contract acceptance.

Issue: Currently negative values are not accepted on advanceFunds). - Would this be an enhancement?

**Comment by jrossignol** [comment]
Would be an enhancement, see #149.  Will position that one for 1.9.0.  You'll also need a function to get the player's funds to be able to do the 65% bit.  Raised #370 for that, and targettng 1.8.4 because it's a pretty easy change.
