### ISSUE TITLE
Experimental Part, when not locked after completing contract, remains Experimental, even when tech is researched later by player

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#369]
I have a starter contract that 

- Gives access to parts for permanent use (Command Seat, Z-100 battery pack, and small rover wheels) but not unlock any other tech or part.

This is to get around any tech tree limitation that the player may be using.

Issue: Currently when using ExperimentalPart behavior, the item appears Experimental in VAB/SPH, until its locked again. But my contract is set to lockCriteria = DO_NOT_LOCK the part on purpose so they can use it indefinitely. But even when the player researches the technology later that includes the Experimental Part, the Experimental Part remains Experimental. Do I need to create a future contract to check for the researched part, and then do a lock to purge the Experimental status of the part?

**Comment by jrossignol** [comment]
Hmmm....that's kind of ugly.  I don't have a good solution, I'll have to hack something in.  Putting as a bug, not sure what release I'll look at for this one.  Probably low priority, because it's mostly a visual change and doesn't functionally affect anything.

**Comment by inigmatus** [comment]
Apparently the work around doesn't work either. Once an experimental part is set DO_NOT_UNLOCK, it remains experimental forever. No known way to declassify it.


//Declassify batteryPack

CONTRACT_TYPE
{
//Requirements for Contract to Appear	
	REQUIREMENT
	{
		name = PartUnlocked
		type = PartUnlocked
		
		part = batteryPack
	}
	
//Contract Descriptions
	name = SSI-Declassify-batteryPack
	title = SSI: Declassify the Z-100 Battery Pack
	group = SSI Aerospace
	agent = SSI Aerospace
	
	description = It looks like the SSI Aerospace Z-100 Battery Pack patent has expired. Accept this contract to declassify it.
	
	synopsis = Declassify the Z-100 Battery Pack
	
	notes = Simply accept this contract, and launch or fly any craft to clear the Experimental tag on the Z-100 Battery Pack.
	
	completedMessage = We have declassified the Z-100 Battery Pack. It should no longer be classified as Experimental.

//Contract Limits
	minExpiry = 7.0
	maxExpiry = 7.0
	deadline = 0
	cancellable = true
	declinable = true
	autoAccept = false
	prestige = Trivial
   	targetBody = Kerbin
   	maxCompletions = 0
   	maxSimultaneous = 1

//Contract Rewards
 	rewardScience = 0
  	rewardReputation = 0
  	rewardFunds = 0
 	failureReputation = 0
  	failureFunds = 0
  	advanceFunds = 0
	weight = 10.0


//Behaviors to do when creating contract
	BEHAVIOUR
	{
		name = ExperimentalPart
		type = ExperimentalPart
		
		part = batteryPack
		
		unlockCriteria = CONTRACT_ACCEPTANCE
		lockCriteria = CONTRACT_COMPLETION
	}

	
//Parameters for Contract Completion
	PARAMETER
	{
		name = Timer
		type = Timer
		
		duration = 5s
		timerType = CONTRACT_ACCEPTANCE
		failContract = false
		
	}

}

**Comment by jrossignol** [comment]
Removing low priority, since there's no workaround.

**Comment by jrossignol** [comment]
Fixed for 1.8.4.  The part will automatically lose its experimental status when the tech is researched.

**Comment by inigmatus** [comment]
Thank you! You deserve a raise! I'll test this tonight.

**Comment by inigmatus** [comment]
Experimental flag gets cleared when you research the part. That part works.

But if someone already has the part researched and owned prior to the part going Experimental, then the part is set to Experimental, and there is no way to clear the Experimental flag.  Is there a way to prevent setting to Experimental parts that already are researched and owned by the player?

**Comment by jrossignol** [comment]
The idea was that you'd use the [PartUnlocked](https://github.com/jrossignol/ContractConfigurator/wiki/PartUnlocked-Requirement) requirement to only offer the contract if the part wasn't already unlocked.  However, it's a very simple check, so I've gone ahead and added it.

**Comment by inigmatus** [comment]
It works now. Fixed in both cases. This can be closed for good.
