### ISSUE TITLE
Enhancement request: Behavior node SpawnFlag

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#372]
Would love the ability to spawn a flag, if it's even possible. Maybe even give it a heading attribute.

**Comment by jrossignol** [comment]
So many enhancements, it'll be a while before I get to it.  Are you sure that a waypoint won't do?  The biggest difference is that the waypoint is tied to the contract and the flag is permanent.

**Comment by inigmatus** [comment]
Oh, permanent flags? no. Go ahead and close this.
