### ISSUE TITLE
SpawnPassengers kerbals and SpawnVessel/Crew kerbals on EVA are not Removed from Game when Contract Completes (SpawnKerbal unaffected)

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#373]
Oy, I promised myself not to create any more issues until at least 1.8.4. This one though I think is critical. I posted about this in https://github.com/seanmcdougall/TakeCommand/issues/1 but wanted to open it here separately.

I think there is a problem in that when SpawnPassengers kerbals or SpawnVessel/Crew kerbals are dropped off (EVA'd) and are not recovered by the player, that when the contract completes (such as a contract to drop off passengers somewhere), those kerbals are not removed from the game and in fact remain for later player recovery. 

See http://www.mediafire.com/download/j9i18la5iik8yea/BugTesting_TC1.zip for an example contract.

I could not duplicate with SpawnKerbal, which spawns the Kerbal prior to loading in a craft. Loading and then Unloading him from the craft and completing the contract parameters does not cause him to remain in the game, and he gets promptly removed from the game as expected.

ok, now i promise myself not to open any more issues until next CC release, and just go back to coding contracts :P

**Comment by jrossignol** [comment]
Okay, pretty straightforward thing going on here.  Before there was tourism contracts in the game, Contract Configurator would clean up tourists automatically.  Then when 1.0 came out, the game started cleaning them up automatically.  Now in 1.0.5, the game doesn't do it automatically anymore.  So I've got to go back to the old way where Contract Configurator needs to do the cleanup.

**Comment by inigmatus** [comment]
Reminder to check this again in KSP 1.1.

**Comment by inigmatus** [comment]
I think this affects spawned vessels too. Not just kerbals.

**Comment by jrossignol** [comment]
That should do it for this one - have a test and let me know if there's any scenarios where you're still seeing kerbals left behind.

**Comment by inigmatus** [comment]
Ill run a special operations mission tonight: No Kerbals Left Behind

**Comment by inigmatus** [comment]
Fixed and can be closed.
