### ISSUE TITLE
RemoveKerbal Behaviour

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#375]
Realized that given all the changes this is probably still desirable for 1.9.0.

**Comment by inigmatus** [comment]
Useful for general kerbal cleanup if necessary,  and could be used to uh...terminate kerbals if not rescued in time if a parameter group included a timer. All kinds of fun. Pairs well with newKerbal ()

**Comment by jrossignol** [comment]
Good, you saw this, saves me from mentioning it to you. :wink: 

Done for 1.9.0
