### ISSUE TITLE
HasPassengers ignoring kerbal attribute and reverting to index all

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#376]
This returns a list of all passengers (kerbal1 and kerbal2) not just kerbal2. The kerbal attribute is being ignored it seems.

		PARAMETER
		{
			name = HasPassengers
			type = HasPassengers

			kerbal = @/kerbal2

		}

**Comment by inigmatus** [comment]
HasCrew works fine btw.

**Comment by jrossignol** [comment]
Can you post or link to the whole contract?

**Comment by inigmatus** [comment]
https://github.com/inigmatus/GAP/blob/master/IslandTours-2-ThreeHourTour.cfg

replace the HasCrew in the Unload Passengers section with HasPassengers

**Comment by jrossignol** [comment]
That contract doesn't have any DATA nodes, so it errors.

**Comment by inigmatus** [comment]
ha, forgot to sync. it has now. :)  swich HasCrew to HasPassengers starting at line 338.

**Comment by jrossignol** [comment]
It's a timing issue due to the parameters being created before the behaviours.  Need to fix HasPassengers to use Kerbal instead of ProtoCrewMember.

**Comment by jrossignol** [comment]
Fixed for 1.9.0
