### ISSUE TITLE
Cancelling contract with loaded passengers freezes Mission Control from exiting

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#377]
Found this rather interesting surprise while testing cancelling contracts as part of my release testing routine. Maybe a KSP bug?

https://github.com/inigmatus/GAP/blob/master/Development/BugTest377.cfg

**Comment by jrossignol** [comment]
Doubtful, usually means an exception. Can you find it in the log?

**Comment by inigmatus** [comment]
[VERBOSE] ContractConfigurator.ExpressionParser.BaseParser:     <- ListExpressionParser`1[ContractPrestige].ParseSimpleStatement<List`1>() = (EXCEPTION), expression = 

there a lot of exceptions.  this one repeats a while.

[LOG 23:33:40.939] Flight State Captured
[EXC 23:33:40.947] NullReferenceException: Object reference not set to an instance of an object

go ahead and run the cfg yourself if you find time. i worked on creating a basic bug test file for future stuff like this to make it easy to report. hope you like. :)

**Comment by jrossignol** [comment]
Yup, and it's appreciated (I'll be looking at it tomorrow night).

And by the way, the most important lines are the ones right *after* that
NullReferenceException.

**Comment by inigmatus** [comment]
[LOG 23:33:40.939] Flight State Captured
[EXC 23:33:40.947] NullReferenceException: Object reference not set to an instance of an object
	KerbalRoster.ValidateAssignments (.Game st)
	Game.Updated ()
	GamePersistence.SaveGame (System.String saveFileName, System.String saveFolder, SaveMode saveMode)
	MCSceneSpawner.onMCDespawn ()
	EventVoid.Fire ()
	MCDespawner.BtnExit (.POINTER_INFO& ptr)
	UIButton.OnInput (.POINTER_INFO& ptr)
	AutoSpriteControlBase.OnInput (POINTER_INFO ptr)
	UIManager.DispatchHelper (.POINTER_INFO& curPtr, Int32 camIndex)
	UIManager.DispatchInput ()
	UIManager.Update ()
	UIManager.DidAnyPointerHitUI ()
	SpaceCenterCamera2.InputCamera ()
	SpaceCenterCamera2.Update ()


and later...


[EXC 23:39:17.329] NullReferenceException
	UnityEngine.Component.get_transform ()
	SpriteRoot.SetCamera (UnityEngine.Camera c)
	AutoSpriteControlBase.SetCamera (UnityEngine.Camera c)
	SpriteRoot.UpdateCamera ()
	UIListItemContainer.UpdateCamera ()
	UIScrollList.SetupCameraAndSizes ()
	UIScrollList.UpdateCamera ()
	ScrollListResizer.ScaleListToFitContent (Int32 offsetTop, Int32 offsetBottom, Int32 offsetLeft, Int32 offsetRight, Boolean stdDirection)
	ApplicationLauncher.ScaleModList ()
	ApplicationLauncher.RemoveModApplication (.ApplicationLauncherButton button)
	QuickScroll.QStockToolbar.Destroy ()
	QuickScroll.QStockToolbar.AppLauncherDestroyed ()
	EventVoid.Fire ()
	ApplicationLauncher.OnDestroy ()

**Comment by jrossignol** [comment]
Ah, excellent! I had got that one but never reproduced it, so this will be
perfect.

**Comment by inigmatus** [comment]
Thanks for all your hard work so far. I'm happily coding the rest of my project.  I think I only have one obstacle to release and leaving you a lone for a while: randomizing passengers. I'll post my support request for that on the forum. Feel free to answer it tomorrow or this weekend.

**Comment by inigmatus** [comment]
Oh and this bug is low priority. can easily wait until 1.10 or later. not many players will do this action.

**Comment by jrossignol** [comment]
Anything that is save breaking like this is a support nightmare, so this is pretty serious and needs to be fixed for 1.9.0.

**Comment by jrossignol** [comment]
Alright, this one is done.  And by the way - thanks for the simplified reproduction contracts, they really do help.

I think 1.9.0 is pretty much ready after this.  I'll likely hold off a day or so, unless you are done testing and are ready to release your contract pack.

**Comment by inigmatus** [comment]
My release will be ready sometime tomorrow night I hope. Go ahead and publish 1.9.0. I have everything I need. Thanks for making this a fun project!

**Comment by jrossignol** [comment]
Sounds good, I'll still wait until tomorrow, just in case.

**Comment by inigmatus** [comment]
confirmed fixed.
