### ISSUE TITLE
SpawnPassengers should accept a list of kerbals instead of passenger names

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#378]
To go along with the improved Kerbal generation changes.

**Comment by inigmatus** [comment]
yes yes! :D

**Comment by jrossignol** [comment]
Done for 1.9.0.  Note that the new attribute is `kerbal` instead of `passengerName`.

**Comment by inigmatus** [comment]
yea! the crowd rejoices!  this makes 1.9.0 worth it. the crowning piece.

**Comment by inigmatus** [comment]
Confirmed fixed and working beautifully.  It's up to you to fix the HasPassengers index bug that remains open for 1.9.0, however you have my green light for publishing 1.9.0 at this point since I have everything I need to start churning out quality contracts. Thanks nightingale!
