### ISSUE TITLE
Carriage returns \n not recognized on Tracking Center switch or game load

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#381]
I've been able to narrow this down and consistently duplicate this bug.  

https://github.com/inigmatus/GAP/blob/master/Development/BugTest381

Newlines in a contract description are not recognized on initial game load, or when switching to Tracking Center and back to Mission Control. 

If you decline the broken newline contract and the contract gets generated again, the newlines reappear as they should in the regenerated contract. But switch to Tracking Center, and then back to Mission Control, and the newlines are removed/not recognized. Same thing happens when you reload KSP - the newlines are not initially recognized.

**Comment by jrossignol** [comment]
Having carriage returns in the title is going to cause other rendering problems in the stock window.  You can try ~n (I found out that's a KSP config node representation for a newline in some places).  But since it isn't Contract Configurator that is saving/loading this value I can't easily do my newline fixes to it.

**Comment by inigmatus** [comment]
the same appears to be true of completedMessage it appears. \n simply not recognized it seems?

See https://github.com/inigmatus/GAP/blob/master/SSI-Start.cfg

**Comment by jrossignol** [comment]
Correct

**Comment by inigmatus** [comment]
I'm testing,  but it appears newlines \n are no longer recognized in contract descriptions too, or for this matter anywhere. They were working before as seen in screenshots on my thread OP. Now they are not.

**Comment by jrossignol** [comment]
New issue please.

**Comment by inigmatus** [comment]
It's intermittent. Can't duplicate at the moment. If I can find a way to reasonably duplicate it I will post a new Issue. Thanks!

**Comment by inigmatus** [comment]
I've been able to narrow this down and consistently duplicate this bug.  

https://github.com/inigmatus/GAP/blob/master/Development/BugTest381

Newlines in a contract description are not recognized on initial game load, or when switching to Tracking Center and back to Mission Control. 

If you decline the broken newline contract and the contract gets generated again, the newlines reappear as they should in the regenerated contract. But switch to Tracking Center, and then back to Mission Control, and the newlines are removed/not recognized.

**Comment by jrossignol** [comment]
Sorry, forgot about this one before releasing 1.91.

**Comment by jrossignol** [comment]
I think I've got a fix for this one (it will only apply to newly generated contracts).  If you don't mind doing a quick verification for me, it would be appreciated.  It should work with title, description, notes, synopsis, and completedMessage.  However, I'll still maintain that having newlines in the title will give you grief from some stock stuff or other.

**Comment by inigmatus** [comment]
Exception occured while saving contract 'BugTest381':
System.NullReferenceException: Object reference not set to an instance of an object
  at ContractConfigurator.ConfiguredContract.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0 


i get that when loading Mission Control, selecting the Bug contract. I confirm the newlines are there. but when exiting Mission Control I get the above.

**Comment by jrossignol** [comment]
Serves me right for rushing this one.  Try the latest checkin.

**Comment by inigmatus** [comment]
Newlines are fixed. Thanks! Confirmed. No further errors on my end.
