### ISSUE TITLE
Enhancement: Set Parameters with attribute hideChildren = false should show children when Set completed

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#382]
Not for 1.9.0 as the work around is to not use a Set, but for a later CC release if accepted:

I hope to build a tidy on-screen passenger manifest that shows incomplete passenger statuses and complete statuses for the player. Currently when Set completes, all children are automatically hidden though and contract window shows only

Passenger Manifest:  

with a green checkmark but no passenger names underneath. I am not sure, but I think a Set treats hideChildren as referring to the child parameter's children and not its own children. Enhancement would be to find a way for a Set's hideChildren attribute set to false mean that its own children aren't hidden on completion.

//Passenger Manifest
	PARAMETER
	{
		name = All
		type = All
		title = Passenger Manifest
		hideChildren = false
		
		PARAMETER
		{
			name = HasCrew
			type = HasCrew
			title = @/kerbals.ElementAt(0)		
			kerbal = @/kerbals.ElementAt(0)
			disableOnStateChange = true
			hideChildren = true
			
			REQUIREMENT
			{
				type = Expression
				expression = @/numPassengers >= 1
			}
			
		}
		
		PARAMETER
		{
			name = HasCrew
			type = HasCrew
			title = @/kerbals.ElementAt(1)
			kerbal = @/kerbals.ElementAt(1)
			disableOnStateChange = true
			hideChildren = true
			
			REQUIREMENT
			{
				type = Expression
				expression = @/numPassengers >= 2
			}
			
		}

	}

**Comment by jrossignol** [comment]
Can't be done. It's stock behaviour to hide children of completed
parameters.

**Comment by jrossignol** [comment]
That being said, in the latest build HasPassengers will collapse down if it only has one child element.  So if you want a crew manifest it can be done by having lots of HasPassengers parameters with only one passenger on each.

**Comment by inigmatus** [comment]
Perfect! Thank you!

**Comment by inigmatus** [comment]
Test.  HasPassengers now shows in the Contracts menu after accepting contact (but before loading passengers):

Passenger On Board: Allia Kerman; On Board: Allia Kerman
Passenger On Board: Aidsey Kerman; On Board: Aidsey Kerman

for:

	PARAMETER
	{
		name = HasPassengers
		type = HasPassengers	
		kerbal = @/kerbals.ElementAt(0)
		disableOnStateChange = true
		
		REQUIREMENT
		{
			type = Expression
			expression = @/numPassengers >= 1
		}
		
	}
	
	PARAMETER
	{
		name = HasPassengers
		type = HasPassengers

		kerbal = @/kerbals.ElementAt(1)

		hideChildren = true
		
		REQUIREMENT
		{
			type = Expression
			expression = @/numPassengers >= 2
		}
		
	}

**Comment by jrossignol** [comment]
Whoops, silly mistake.  Should be fixed now.

**Comment by inigmatus** [comment]
Confirmed fixed. Golden.
