### ISSUE TITLE
Crew: At least 0 kerbals  is the line that shows in the Contract Window.

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#383]
Really odd display bug in the Contract Window for this contract. Any ideas why it says 0 kerbals in the contract window?

https://github.com/inigmatus/GAP/blob/master/Development/BugTest383.cfg

**Comment by jrossignol** [comment]
There was a bit of a logic flow error, try it now.

**Comment by inigmatus** [comment]
I confirmed fixed. Thanks!
