### ISSUE TITLE
Add CelestialBody.SCANsatCoverage()

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#389]
New method to determine the amount of coverage for given SCANsat scans.

**Comment by jrossignol** [comment]
Done for 1.9.1

**Comment by severedsolo** [comment]
Lovely :) what's the usage here? Is it 
``SCANSat.Coverage(Biome) >90`` ?

**Comment by jrossignol** [comment]
Yup, exactly that.

**Comment by severedsolo** [comment]
Awesome, I'm getting better at reading your source code :D
