### ISSUE TITLE
HasNotResearchedTech Requirement desired (or a Not set for Requirements)

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#392]
I would like to offer a contract to gift experimental parts for money (see #149 ) but only offer the contract if the parts are not yet researched by the player. Could also be useful for limiting contracts to below a certain tech advancement.

A Not set would open up a range of requirements, possible to even be used to set contracts used in series with Strategia.

**Comment by jrossignol** [comment]
Already possible.  See [Requirement.invertRequirement](https://github.com/jrossignol/ContractConfigurator/wiki/Requirements).

**Comment by inigmatus** [comment]
ty!
