### ISSUE TITLE
WaypointGenerator fixes

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#393]
* [x] Allow clustered waypoints
* [x] Different parameter for each hidden waypoint in a set
* [x] Allow multiple behaviours (VisitWaypoint currently only looks at the first WaypointGenerator)

**Comment by severedsolo** [comment]
Related to #393 - VisitWaypoint parameter is not showing on the latest dev version of CC.

**Comment by severedsolo** [comment]
Related - the VisitWaypoint Parameter is not reading the index. I'm getting an error of "Couldn't find waypoint in WaypointGenerator behaviour(s) with index 0"

**Comment by jrossignol** [comment]
Thanks @severedsolo, that was pretty badly broken. :cry:

**Comment by jrossignol** [comment]
Done for 1.9.1
