### ISSUE TITLE
disableStockContract and 1.0.5

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#394]
Have any new ones been added for 1.0.5, like for the haul contracts? Any other changes?
(Apologies if this was mentioned during the release of 1.9.0, I've been somewhat disconnected...)

**Comment by jrossignol** [comment]
I forgot to update the list on the wiki for 1.0.5, but the only change was removing RecordTrack.  The haul contracts are just PartTest, and most of the contextuals fall into Satellite, Survey or Base.

You can also double check this in the GUI window available in the space centre, as it will list all the loaded contract types (although I think it adds spaces and removes the word Contract for readability).

**Comment by NathanKell** [comment]
Awesome, thanks! :)
