### ISSUE TITLE
ITERATOR - unexpected attribute 'iteratorCount' found, ignored.

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#395]
I made a test bug contract based on your description here: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-105-contract-configurator-v190-2015-12-06/&do=findComment&comment=2318215

See BugTest395:

https://github.com/inigmatus/GAP/blob/master/Development/BugTest395.cfg

This contract fails for:

[Warning]: ContractConfigurator.ConfigNodeUtil: Got an unexpected exception trying to load 'kerbals' as a list:

[Exception]: ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index

[Error]: ContractConfigurator.ContractType: CONTRACT_TYPE 'BugTest': Error parsing kerbals

[Exception]: ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index

[Warning]: ContractConfigurator.ConfigNodeUtil: Got an unexpected exception trying to load 'kerbal' as a list:

[Exception]: ArgumentNullException: Argument cannot be null.
Parameter name: source

[Error]: ContractConfigurator.HasPassengersFactory: CONTRACT_TYPE 'BugTest', PARAMETER 'HasPassengers' of type 'HasPassengers': Error parsing kerbal

[Exception]: ArgumentNullException: Argument cannot be null.
Parameter name: source

[Warning]: ContractConfigurator.HasPassengersFactory: CONTRACT_TYPE 'BugTest', PARAMETER 'HasPassengers' of type 'HasPassengers': unexpected attribute 'iteratorCount' found, ignored.

**Comment by jrossignol** [comment]
Looking into this, but have a side question - where are you getting the error messages from when copy+pasting into the GitHub issue?  Is it from the debug window?  If so, please grab them from KSP.log, as it doesn't show the stack-traces in the debug window (which is the most important part for me to debug these).

**Comment by jrossignol** [comment]
Did some cleanup of the error handling, it now gives you the correct error message, which is:
```
[EXC 12:51:16.598] ArgumentException: Couldn't find matching signature for method 'Random'.
	Error occurred near '*':
	[ NewKerbal(), NewKerbal(), NewKerbal(), NewKerbal() ].Random(2,4)
	................................................................* <-- HERE
```
Basically, there is no Random(int, int) method for lists.  But it's a good thing to have, so I'll add that next.

**Comment by jrossignol** [comment]
Added the Random(int, int) method.  All fixed up for 1.9.1

**Comment by inigmatus** [comment]
Ok, same test bug contract, no errors, but Kerbals are not loading in the contract window.

https://github.com/inigmatus/GAP/blob/master/Development/BugTest395.cfg

Contract window says:

Passenger: System.Collections.Generic.List`1[ContractConfigurator.Kerbal]

and not 

Passenger: Joe Kerman

Also, Kerbals are not loading into vessel or appearing anywhere on Astronaut Complex roster.

**Comment by jrossignol** [comment]
That one is all you. ;)

kerbal in HasPassengers is a list of kerbals (the iterator makes it a list
of one).  So I'd just remove the title (since the default is exactly what
you want in this case), or change the title to @kerbal.First()

**Comment by inigmatus** [comment]
https://github.com/inigmatus/GAP/blob/master/Development/BugTest395.cfg still not working.

@kerbal.First() fixed the title, however the Kerbals still do not appear anywhere on the roster to load.


[LOG 15:20:53.189] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [BugTest]
[LOG 15:20:53.445] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [Wright-AirplaneRide]
[WRN 15:21:09.056] HighlightingSystem : Edge Highlighting requires AA to work!
[LOG 15:21:09.059] Launcher start settings screen: False
[LOG 15:21:36.042] Launcher here(in write): False
[WRN 15:21:36.047] HighlightingSystem : Edge Highlighting requires AA to work!
[LOG 15:21:37.033] Launcher here(in write): False
[WRN 15:21:37.036] HighlightingSystem : Edge Highlighting requires AA to work!
[LOG 15:21:46.653] Awarding 1106194.70477104 funds to player for contract advance
[LOG 15:21:47.989] Flight State Captured
[LOG 15:21:48.018] Saving Achievements Tree...
[ERR 15:21:48.022] Input is null

[ERR 15:21:48.023] Input is null

[ERR 15:21:48.025] Input is null

[LOG 15:21:48.106] Game State Saved to saves/default/persistent

**Comment by jrossignol** [comment]
Sorry, on mobile app can't easily check - do you have a SpawnPassengers?
HasPassengers won't spawn if I recall.

**Comment by inigmatus** [comment]
I am simply using the example you gave in the forum post.

	DATA
	{
		type = List<Kerbal>
		kerbals = [ NewKerbal(), NewKerbal(), NewKerbal(), NewKerbal() ].Random(2,4)
	}

	PARAMETER
	{
		name = HasPassengers
		type = HasPassengers
		title = Passenger: @kerbal.First()
		hideChildren = true
		
		ITERATOR
		{
			type = Kerbal
			kerbal = @/kerbals
		}
	}

**Comment by jrossignol** [comment]
Was only a partial example pulled from one of your contracts - the iterator
part seems to be working, which is what it read meant to demonstrate.

**Comment by inigmatus** [comment]
I'm such a noob. I needed a SpawnPassengers behavior. it's what i get for creating a bug report past my bedtime. :D
