### ISSUE TITLE
Contract disabling via contract pack not working

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#397]
There are some issues with disabled contracts still showing up or coming back.  Need details.

**Comment by Blu3wolf** [comment]
As soon as I had unlocked the parts needed for space stations I started getting both stock station contracts and KSS contracts. I think that means it appears not to have been disabled, from the start. Ill check the CC settings in the KSC menu for whether the stock missions are listed as disabled.

**Comment by jrossignol** [comment]
Unable to reproduce this as of yet, will defer to 1.9.2.  If anyone is able to reproduce in a new game, please let me know (my current suspicion is this is a holdover from older Contract Configurator versions that were messing up the saved settings).

**Comment by Blu3wolf** [comment]
Do note that my install was a fresh KSP install, without having older CC versions installed.

**Comment by jrossignol** [comment]
:disappointed: I think you might've mentioned that already on the forums.  I'll have to play around some more - it worked perfectly for me, so there must be something else needed to trigger it getting messed up.

**Comment by Blu3wolf** [comment]
well, Ill install 1.9.1 as soon as CKAN notices the update. Ill mention it here if it happens again on 1.9.1, but as Im not planning on starting a new game for it just yet that might not be very useful for you. Sorry.

**Comment by jrossignol** [comment]
Sent a PM to Rokker to hopefully help diagnose this.

**Comment by Blu3wolf** [comment]
I did update, and Ive now manually disabled contracts through contract configurators settings window. It claims they are disabled either way, but I was getting contracts from those categories, so..

**Comment by jrossignol** [comment]
Rokker wasn't able to reproduce.  For anyone who is able to, here's what I need on this one:
 1. Get the development version ([here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true))
 1. Turn debug on (instructions [here](https://github.com/jrossignol/ContractConfigurator/wiki/How-To#turning-on-debug))
 1. Provide a KSP.log file to me that includes the KSP startup and starting a new game (assuming that doing so causes the contracts to show up as disabled).
 1. Provide the persistent.sfs

**Comment by jrossignol** [comment]
Defer to 1.9.3

**Comment by jrossignol** [comment]
Fixed for 1.9.3

**Comment by Blu3wolf** [comment]
Hi, 

Look  what I've just  found on the web! It's so amazing, check it out  <http://motive.russtoolshed.com/aeayeim>

Sincerely yours, blue

**Comment by Blu3wolf** [comment]
Hello! 

I've found some new stuff recently, it  is  really gorgeous, please take a look  here  <http://principle.hmongbroadcasting.com/aeujn>

Regards, blue

**Comment by Blu3wolf** [comment]
Hello, 

There is  something I wanted to show you, it's  just some really great stuff! Just take a look <http://guest.electronicmedrec.org/aesijwrr>

Best, blue

**Comment by jrossignol** [comment]
Probably time for you to run a virus scanner...

**Comment by Blu3wolf** [comment]
Sorry, but its not my system sending it. Would probably be better for Github to implement basic email verification. My emails are signed, and all originate from my web server. 

Nothing more I can do to prevent spoofing at my end. Other than changing my email address, but that wont stop spoofed emails coming from this address.
