### ISSUE TITLE
Minor QOL improvement to ReachState

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#399]
Just a minor low priority request:

Any chance of making a further "situation" that would cover Landed or Splashed just to make the contract screen slightly cleaner? Or even just make ReachState support more than one situation?

Although thinking about it, I guess this is what hideChildren is for - so feel free to close it down if you don't feel it's worth it.

**Comment by jrossignol** [comment]
It's doable, but would ReturnHome work for your use case instead?

**Comment by severedsolo** [comment]
Not really, as this is for extraplanetary bases. I know there isn't a massive amount of water out there, but people may want water bases with 1.0.5, so I'm having to cover off splashed to be safe.

**Comment by jrossignol** [comment]
Okay, makes sense.  I've had scenarios where it would've been nice too.  I'll see what I can do.

**Comment by severedsolo** [comment]
As I said no rush, just one of those "would be nice" things.

**Comment by jrossignol** [comment]
Done, will do documentation tomorrow.  Basically, ReachState allows multiple situations now and it will be a logical or between the various situations.

**Comment by jrossignol** [comment]
Doc changes done.
