### ISSUE TITLE
VesselParameterGroup defined vessel not being set on parameter completion

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#400]
VesselParameterGroup defines the vessel just fine if craft is a CommandSeat aircraft

however

VesselParameterGroup vessel attribute is not loading the defined vessel if craft is a Command Seat only craft.  The craft is defined fine and dandy, but not recalled by the vessel attribute at all leading to a contract that is not compleatable with Command Seat only craft using the VesselParameterGroup vessel attribute as a check on parameter completion.

See: https://github.com/inigmatus/GAP/blob/master/SSI-KAX-Helicopter.cfg

command seat only craft: not recognized
https://github.com/inigmatus/GAP/blob/master/Development/aRackofKerbals.craft

command pod craft: recognized https://github.com/inigmatus/GAP/blob/master/Development/aPlatterofKerbals.craft

HyperEdit to the Admin Building rooftop:

Lat -0.0927379114208622
Long 285.337201630856
alt 20 (default)

Requires TakeCommand mod (download and install it via CKAN)

**Comment by inigmatus** [comment]
In the contract example linked above, the initial definition of the vessel has only a HasCrew parameter. It triggers the definition, but for some reason the reference isn't being loaded by the vessel attribute when later recalled. 

In further testing I discovered that the VesselParameterGroup definition parameter must have more than just a HasCrew parameter if using a CommandSeat only craft. Adding an additional attribute such as a PartValidation attribute, enables the VesselParameterGroup definition to be later recalled by VesselParameterGroup vessel attribute calls.  Again, this only affects Command Seat only craft. Not sure why.  The work around for now is for me to add an Any set to include a PartValidation for Command Seat or some other part.

**Comment by jrossignol** [comment]
Can you toss me a save file of this in the "bad" state (the one parameter
not completed and the other not completing)?

**Comment by inigmatus** [comment]
contract with work around commented out: https://github.com/inigmatus/GAP/blob/master/Development/Issue400-notworking

save where Command Seat only craft not able to complete above contract: 
https://github.com/inigmatus/GAP/blob/master/Development/Issue400-noWorkAround-CSonlyNotWorking.sfs

save where any other pod able to complete the above contract:
https://github.com/inigmatus/GAP/blob/master/Development/Issue400-noWorkAround-PodOnlyWorking.sfs

contract with work around uncommented:
https://github.com/inigmatus/GAP/blob/master/Development/Issue400-working

save where Command Seat only craft able to complete the above workaround contract:
https://github.com/inigmatus/GAP/blob/master/Development/Issue400-WorkAround-CSonlyWorking.sfs

**Comment by jrossignol** [comment]
Testing something out - can you try the dev version?  If it still doesn't work, please provide a log that covers the time that the first VesselParamterGroup goes to completed.

**Comment by inigmatus** [comment]
You broke VesselParameterGroup. heh.

Whatever change you made is now having the opposite effect. The Command Seat aircraft is able to be recalled by the vessel attribute and complete the contract, but now any other Command Pod craft is not able to be recalled by the vessel attribute (I tested with the aplatterofkerbals craft linked above.

Log using aPlatterofKerbals (mk1 command pod craft) having its vessel defined, but not recalled by the vessel attribute to complete the commented contract linked above.

[LOG 23:00:42.917] [Pre-Flight Check]: All Checks Complete. Go for Launch!
[LOG 23:00:42.918] Launching vessel from Runway. Craft file: C:\Users\Administrator\Downloads\KSP\KSP_win_DEV\saves\Development\Ships\SPH\aPlatterofKerbals.craft
[LOG 23:00:42.918] Flight State Captured
[ERR 23:00:42.920] Input is null

[LOG 23:00:42.922] Saving Achievements Tree...
[LOG 23:00:42.936] Game State Saved to saves/Development/persistent
[WRN 23:00:42.948] [HighLogic]: =========================== Scene Change : From SPACECENTER to FLIGHT (Async) =====================
[LOG 23:00:43.816] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[WRN 23:00:44.553] ApplicationLauncher already exist, destroying this instance
[LOG 23:00:44.556] QuickScroll(1.32): Settings Loaded
[LOG 23:00:44.563] AddonLoader: Instantiating addon 'NavWaypoint' from assembly 'KSP'
[LOG 23:00:44.566] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[LOG 23:00:44.588] ------------------- initializing flight mode... ------------------
[LOG 23:00:44.611] Loading ship from file: C:\Users\Administrator\Downloads\KSP\KSP_win_DEV\saves\Development\Ships\SPH\aPlatterofKerbals.craft
[WRN 23:00:44.634] [Part]: PartModule TransferDialogSpawner at mk1pod, index 7: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 23:00:44.635] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 23:00:44.647] [Part]: PartModule TransferDialogSpawner at mk2CrewCabin, index 5: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 23:00:44.648] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 23:00:44.659] [Part]: PartModule TransferDialogSpawner at mk2CrewCabin, index 5: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 23:00:44.660] ...no TransferDialogSpawner module found on part definition. Skipping...
[LOG 23:00:44.662] aPlatterofKerbals loaded!
[LOG 23:00:45.974] putting ship to ground: 9.221963
[LOG 23:00:45.978] [aPlatterofKerbals]: Ready to Launch - waiting to start physics...
[LOG 23:00:45.985] Crewmember Jebediah Kerman assigned to Mk1 Command Pod, seat # 0 (crew seat index: 0)
[LOG 23:00:45.985] [FLIGHT GLOBALS]: Switching To Vessel aPlatterofKerbals ---------------------- 
[LOG 23:00:45.987] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[LOG 23:00:45.988] Reference Frame: Rotating
[LOG 23:00:45.999] InternalSeat: Cannot find seatTransform of name 'Seat_UpLeft'
[LOG 23:00:46.000] InternalSeat: Cannot find portraitCamera of name 'Camera_UpLeft'
[LOG 23:00:46.000] InternalSeat: Cannot find seatTransform of name 'Seat_UpRight'
[LOG 23:00:46.001] InternalSeat: Cannot find portraitCamera of name 'Camera_UpRight'
[WRN 23:00:46.001] InternalModel error: Part Crew capacity is 4, but 6 seats are defined in internal model
[LOG 23:00:46.002] InternalSeat: Cannot find seatTransform of name 'Seat_UpLeft'
[LOG 23:00:46.003] InternalSeat: Cannot find portraitCamera of name 'Camera_UpLeft'
[LOG 23:00:46.003] InternalSeat: Cannot find seatTransform of name 'Seat_UpRight'
[LOG 23:00:46.004] InternalSeat: Cannot find portraitCamera of name 'Camera_UpRight'
[WRN 23:00:46.004] InternalModel error: Part Crew capacity is 4, but 6 seats are defined in internal model
[LOG 23:00:46.006] stage manager resuming...
[LOG 23:00:46.007] Vessel assembly complete!
[LOG 23:00:46.008] stage manager starting...
[LOG 23:00:46.008] all systems started
[LOG 23:00:46.049] Reloaded override drag cube for zeroed cube root part mk1pod on vessel aPlatterofKerbals
[LOG 23:00:46.198] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 23:00:46.200] [ScenarioUpgradeableFacilities]: Loading... 0 objects registered
[ERR 23:00:46.262] Cannot find a Module of typename 'HoloDeck'

[ERR 23:00:46.262] ScenarioModule is null.

[LOG 23:00:46.264] Loading Depletion Nodes
[LOG 23:00:46.265] DepNodeCount:  0
[LOG 23:00:46.265] Loading Biome Nodes
[LOG 23:00:46.265] BiomeNodeCount:  0
[LOG 23:00:46.266] Loading Planet Nodes
[LOG 23:00:46.266] PlanetNodeCount:  0
[LOG 23:00:46.299] [FlightIntegrator]: Vessel aPlatterofKerbals has been unloaded 1.79769313486232E+308, applying analytic temperature 315.043421976266
[LOG 23:00:46.305] [Progress Node Reached]: RecordsAltitude
[LOG 23:00:46.306] [Progress Node Reached]: RecordsSpeed
[LOG 23:00:46.307] [Progress Node Reached]: RecordsDistance
[LOG 23:00:46.311] Added 1.999999 (2) reputation: 'Progression'.
[LOG 23:00:46.317] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [Issue398]
[LOG 23:00:46.397] [PlanetariumCamera]: Focus: aPlatterofKerbals
[LOG 23:00:46.607] Flight State Captured
[LOG 23:00:46.614] Saving Achievements Tree...
[LOG 23:00:46.643] Game State Saved as persistent
[LOG 23:00:47.667] [aPlatterofKerbals]: ground contact! - error: -0.102m
[LOG 23:00:47.668] Unpacking aPlatterofKerbals
[LOG 23:00:52.590] Game Paused!
[LOG 23:01:39.822] Game Unpaused!
[WRN 23:01:39.823] Can not play a disabled audio source
[LOG 23:01:48.105] HyperEdit: Set ActiveVessel.Landed = false
[LOG 23:01:48.106] HyperEdit: Set ActiveVessel.landedAt = ""
[LOG 23:01:48.108] Packing aPlatterofKerbals for orbit
[LOG 23:01:48.111] HyperEdit: Orbit "Active vessel" changed to: inc=0.0927379114225716 ecc=0.994798243853743 sma=300827.27207501 lan=112.308858587992 argpe=90.0167931140715 mep=3.13014333347281 epoch=417.319999999911 refbody=Kerbin
[LOG 23:01:48.128] HyperEdit: (Happening every frame) Soft-lander changed ship velocity this frame by vector 4.36383537985217,0.00820226288965931,-3.01803878694795 (mag 5.30581611244569)
[LOG 23:01:48.653] [AsteroidSpawner]: No new objects this time. (Odds are 1:2)
[LOG 23:01:49.208] [Progress Node Reached]: FirstLaunch
[LOG 23:01:49.209] [Progress Node Complete]: FirstLaunch
[LOG 23:01:49.430] Unpacking aPlatterofKerbals

**Comment by inigmatus** [comment]
Trying to be more clear: all contracts using VesselParameterGroup, if not using a Command Seat, are now broke and can't complete contracts when a parameter for a vessel is checked against a defined VPG. Just sounding the klaxon on the critical brokeness of this most awesome break. :D

**Comment by jrossignol** [comment]
Okay, so this is the combination of how TakeCommand works (EVA the kerbal from an imaginary seat, reseat them in the chair to get the model there) and with the rather odd contract layout.  The problem was it would still keep tracking the EVA kerbal even after they are reseated.

I'd suggest dropping the define + vessel VesselParameterGroup combinations.  You're far better off having the VAB/admin building VesselParameterGroup parameters be the one that does the define of the vessel.

Anyway, fixed for 1.9.1

**Comment by inigmatus** [comment]
confirmed fixed.
