### ISSUE TITLE
uniquenessCheck = GROUP_ALL not working

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#402]
Again, assuming I understand correctly: GROUP_ALL should only ever generate one contract per vessel.

I'm getting duplicates (I thought it might be because I reloaded contracts, but it came back even after I completed it again)

**Comment by jrossignol** [comment]
GROUP_ALL means the value must be unique for every DATA element with the same name as this one, in every contract type with the same parent group as this one with a status of Active, Offered or Completed.

Can you send the contracts where you're seeing this issue?  Is the duplicate in the same contract type, or a different one.  Reloading contracts *shouldn't* allow duplicates, but I've had problems with this in the past too (although there are some refresh issues in the KSP GUIs when doing a reload too).

**Comment by severedsolo** [comment]
This is the one that's specifically causing the issue:
https://github.com/severedsolo/KerbinSpaceStation/blob/master/Core%20Missions/BaseScience.cfg

Basically, what's happening is, you complete the contract and it comes straight back up again (because in my testing save I have a very small pool of available contracts).

I expect that the others that use this node will show the same issue:
https://github.com/severedsolo/KerbinSpaceStation/blob/7970e7ad9b4548417cc016d715653fa9f2425af4/Core%20Missions/BaseSelf-Sufficiency.cfg

https://github.com/severedsolo/KerbinSpaceStation/blob/7970e7ad9b4548417cc016d715653fa9f2425af4/Core%20Missions/BaseExpansion.cfg

but I imagine that they will sort themselves out anyway, because generally speaking when you complete the contracts, the conditions that lead to it being generated won't be met.

**Comment by jrossignol** [comment]
Is there any docking involved?  DATA nodes for Vessels are pretty simplistic - so if the ID changes all bets are off.

**Comment by severedsolo** [comment]
None at all. The contract is literally "Land a science lab within 500m of the base" - that's it. No id changes, no docking, nothing.

Having said that, you've just given me an idea. I could use a VPG to make sure that it doesn't generate again.

**Comment by jrossignol** [comment]
There were two major problems here:
 1. Vessel values for the uniqueness check were getting lost from all contracts anytime you go to the VAB/SPH.
 1. It wasn't ever checking the finished contracts
Once I got those two cleared up, this started working quite nicely.  Should be a major fix for your contract packs in this one. :+1:

**Comment by jrossignol** [comment]
Fixed in 1.9.2.

**Comment by severedsolo** [comment]
Huh, I had noticed the vab thing, but I assumed it was hypetedit messing up the contract system and it reset on a scene change, I was using it as a workaround for testing
