### ISSUE TITLE
String Expression Parsing Issues

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#403]
Take this line from Field Research:
``validBodies = OrbitedBodies().Where(cb => (cb.IsPlanet() || cb.IsMoon()) && cb != HomeWorld())``

Add SCANsatCoverage (like so)

``validBodies = OrbitedBodies().Where(cb => (cb.IsPlanet() || cb.IsMoon()) && cb != HomeWorld() && cb.SCANsatCoverage(Biome)>80)``

CC fatal errors.

**Comment by jrossignol** [comment]
Won't be able to look at this until tonight - what's the error?

**Comment by severedsolo** [comment]
Eh, might be easier to give you a log, as it falls over pretty hard, as the whole group fails to load.
https://www.dropbox.com/s/ivrtklna104p7ty/output_log.txt?dl=0

**Comment by jrossignol** [comment]
```
MissingMethodException: Cannot find method 'SCANSatCoverage' for class 'CelestialBody'.
  at ContractConfigurator.ExpressionParser.ExpressionParser`1[T].GetCalledFunction (System.String functionName, Function& selectedMethod, Boolean isFunction) [0x00000] in <filename unknown>:0 
```
Ahem. SCAN**s**atCoverage.

**Comment by severedsolo** [comment]
My bad, I typed that out quickly because I deleted what I did earlier. Even with correct spelling it falls over - new log: https://www.dropbox.com/s/ivrtklna104p7ty/output_log.txt?dl=0

**Comment by severedsolo** [comment]
Wait, if it's relevant. I used a :NEEDS module manager label on a DATA node. So the full thing is:
``	 DATA:NEEDS[SCANsat]
    {        
		type = List<CelestialBody>
        validBodies = OrbitedBodies().Where(cb => (cb.IsPlanet() || cb.IsMoon()) && cb != HomeWorld() && cb.SCANsatCoverage(Biome)>80)
        l2Bodies = @validBodies.Where(cb => cb.Parent() == (@homeIsMoon ? HomeWorld().Parent() : HomeWorld()) || cb == HomeWorld().Parent())
        l3Bodies = @validBodies.ExcludeAll(@l2Bodies)
    }
}``

**Comment by jrossignol** [comment]
```
NullReferenceException: Object reference not set to an instance of an object
  at ContractConfigurator.ExpressionParser.ExpressionParser`1[T].GetCalledFunction (System.String functionName, Function& selectedMethod, Boolean isFunction) [0x00000] in <filename unknown>:0 
```
Probably an easy fix, but I'll need access to KSP to fix it.

The method is supposed to work even when SCANsat isn't installed (it should return 100.0, but actually returns 1.0, so I'll fix that too) .  Otherwise you'd need to provide two data nodes (one NEEDS[SCANsat] and one NEEDS[!SCANsat}).

**Comment by severedsolo** [comment]
I have a NEEDS[!SCANsat] but that worked fine so didn't mention it. Good to know it isn't needed though.

**Comment by jrossignol** [comment]
It was an error handling issue, once I fixed the error handling and got the right message out, I realized that you need to do this:
```
validBodies = OrbitedBodies().Where(cb => (cb.IsPlanet() || cb.IsMoon()) && cb != HomeWorld() && cb.SCANsatCoverage("Biome") > 80)
```
Because Biome is a string and not an enum.  Weird and rare exception.  Going to leave this open and think about if there's a way to handle it so the string parsing doesn't incorrectly gobble everything to the end of the expression, it causes annoying and confusing issues like this one.

**Comment by severedsolo** [comment]
Don't know whether to mention this here or raise a new issue - but you know how you said that SCANsatCoverage should be ignored if the player doesn't have SCANsat? Well it's not. It's spamming the log with "Couldn't find assembly for SCANsat!" and stopping the contracts from generating.

**Comment by jrossignol** [comment]
I fixed the version/assembly check spam - forgot to set the silent flag for that one. :)
