### ISSUE TITLE
Add pqsOffsetData(NameOfCity) to Waypoint Type

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#405]
https://github.com/jrossignol/ContractConfigurator/wiki/Waypoint-Type

Would be nice if I could extract PQS values from random generated waypoints for use in DATA node expressions and elsewhere in the contract. Case use is to generate random pqs waypoints for downed vessels, and then use the same random generated pqs waypoint to spawn kerabls and vessels.

Perhaps a pqsOffsetData(NameOfCity) so it looks like:

@/DistressLocationWaypointGenerator.Waypoints().ElementAt(1).pqsOffsetData(IslandAirfield)

until something like this can be coded, random waypoint references will be limited to lat/long coordinates which breaks the whole intent of using pqs waypoints in a contract pack.

http://forum.kerbalspaceprogram.com/index.php?/topic/91625-105-contract-configurator-v191-2015-12-15/&do=findComment&comment=2327454

**Comment by jrossignol** [comment]
I don't understand the use case here.

* Waypoint Generator can generate a waypoint for you based on a bunch of different inputs, including PSQ offset.
* You can get the location of a waypoint
* You can feed that location into another thing (like SpawnKerbal).

If you got the waypoint location (internally a lat/lon) and it was translated to a PQS offset, you could then put it into SpawnKerbal as a PQS offset - which would get internally translated back to the lat/lon.  So you haven't gained anything with a PQS offset here.

**Comment by inigmatus** [comment]
I have a hidden PQS waypoint, which then I use to generate a random waypoint near it.

I want to spawn kerbals and vessels with that random waypoint while maintaining PQS values.

SpawnKerbal and Spawn Vessel both take PQS values. However I am forced to use lat/long in SpawnKerbal and SpawnVessel rather than PQS since the random waypoint generator only gives me a function to grab lat and long, not PQS.

**Comment by jrossignol** [comment]
Right, but you can pass the lat/lon into SpawnKerbal and it will be fine.

If I generate off the KSC PQSCity I would get waypoints with locations 0.0, 285 in stock or 28.6, -80.7 in RSS.  There's no reason to translate those back into a PQSoffset to put into SpawnKerbal, as SpawnKerbal is just going to translate it back to the lat/lon anyway.

**Comment by inigmatus** [comment]
so SpawnKerbal and SpawnVessel lat long values are translated into RSS values correctly then?

**Comment by inigmatus** [comment]
oh I see. so you're saying that when the waypoint is created PQS, that the function lat() and long() pass to SpawnKerbal and SpawnVessel the translated RSS lat long values?

**Comment by jrossignol** [comment]
Essentially yes - although in reality the translation is done when you do the initial WaypointGenerator PQS offset - after that the values are just... the values. :wink:

**Comment by inigmatus** [comment]
awesome. thanks for the explanation. that's resolves my questions for now.
