### ISSUE TITLE
SpawnPassengers kerbalType = HasCrew not spawning crew but tourists

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#407]
all my contracts. using latest CC dev.
here's one.
see https://github.com/inigmatus/GAP/blob/master/Airlines-Flight-5.cfg

**Comment by inigmatus** [comment]
Simple bug contract for testing. Consistently spawns passenger as Tourist.

https://github.com/inigmatus/GAP/blob/master/Development/BugTest407.cfg

**Comment by jrossignol** [comment]
Yay, fixed for 1.9.2.  One step closer!

**Comment by inigmatus** [comment]
testing...

**Comment by inigmatus** [comment]
confirmed fixed. thank you!
