### ISSUE TITLE
Unhandled Exception - "Late bound operations cannot be performed on types or methods for which ContainsGenericParameters"

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#408]
```
Exception occured while loading contract 'StationSciencePlantGrowth':
System.InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ConfiguredContract.OnLoad (.ConfigNode node) [0x00000] in <filename unknown>:0
```

The contract that caused it (haven't checked if it's a mistake in the contract yet): https://github.com/severedsolo/KerbinSpaceStation/blob/StationScience/MaintenanceMissions/StationSciencePlantGrowth.cfg

**Comment by jrossignol** [comment]
Will look into this one tomorrow (hopefully).

**Comment by severedsolo** [comment]
No rush, I know it's a busy time of year. I could wait until 2016 if necessary :)

**Comment by jrossignol** [comment]
Started looking into this, but hadn't quite gotten to reproducing yet because stuff started getting bogged down (will have to wait for tomorrow).  A tip - avoid using the AllScienceSubjects(), as it is a very expensive function.  Use AllScienceSubjectsByBody() instead, since you want to filter down to a specific body anyway.

**Comment by severedsolo** [comment]
That's fine, the error occurs at the point the contract tries to generate (so you have the station in orbit with the right part).

**Comment by jrossignol** [comment]
This one was a pain to track down, glad to have it fixed.  Let me know if this gives you any more grief.

**Comment by severedsolo** [comment]
Thanks! I'll test it on Boxing Day
