### ISSUE TITLE
SpawnVessel and SpawnKerbals on water respawning to ocean floor on player approach

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#411]
SpawnKerbal on water spawns the kerbal on the ocean surface with savefile showing splashed, but if you fly a Velocitize or any craft over their heads for about 30-60 seconds or go in and out of 2km and back to them, the Kerbals (and sometimes any SpawnVessel nearby) suddenly disappears from the ocean surface and reappears at the bottom of the sea with the savefile showing landed.

Sometimes the SpawnVessel is just fine but the kerbals reappear at the bottom of the sea. Sometimes the Kerbals just lose buoyancy altogether and sink away from the player... affecting all Kerbals there on out in the game, forcing a game restart.

before state:

		VESSEL
		{
			pid = 3c706e51654944168ad1f73397c24482
			name = Seemore Kerman
			type = EVA
			sit = SPLASHED
			landed = False
			landedAt = 
			splashed = True
			met = 903.859999999475
			lct = 903.859999999475
			lastUT = -1
			root = 0
			lat = -1.77640504170036
			lon = 286.681273944899
			alt = 0
			hgt = -1
			nrm = 0.1736481,0.9848079,-1.634471E-07
			rot = -0.716763,-0.160609,-0.04183841,0.6772779
			CoM = 0,0,0
			stg = 0
			prst = False
			ref = 0
			ctrl = False
			ORBIT
			{
				SMA = 300000.000173613
				ECC = 1
				INC = NaN
				LPE = 33.2228671596007
				LAN = 245.121116187451
				MNA = 0.570796326794897
				EPH = 913.399999999466
				REF = 1
                          }

after state (I flew a stock Velocitize over their heads for about 30 seconds flying in and out of 2km and buzzing their heads prob no more than 50m away; the SpawnKerbals and the SpawnVessel disappear from the surface only to reappear immediately at the bottom of the ocean):

		VESSEL
		{
			pid = 3c706e51654944168ad1f73397c24482
			name = Seemore Kerman
			type = EVA
			sit = LANDED
			landed = True
			landedAt = 
			splashed = True
			met = 216.578244323658
			lct = 903.859999999475
			lastUT = 1120.45824432313
			root = 0
			lat = -1.77640698369608
			lon = 286.681279345141
			alt = -938.583692370914
			hgt = 0.2998332
			nrm = -0.03432799,0.8413847,0.5393453
			rot = -0.7373633,-0.1600629,-0.04419624,0.6547686
			CoM = -2.499856E-05,1.641571E-05,6.076093E-06
			stg = 0
			prst = False
			ref = 0
			ctrl = True
			cPch = 0
			cHdg = 0
			cMod = -1
			ORBIT
			{
				SMA = 300307.042636799
				ECC = 0.994829728379279
				INC = 1.77640698344342
				LPE = 90.0000000000001
				LAN = 125.399744660368
				MNA = 3.14159265358979
				EPH = 1120.45824432313
				REF = 1
			}

I am still doing my data gathering, but figured I'd open this case to get started.

**Comment by inigmatus** [comment]
before: 

KERBAL
		{
			name = Seemore Kerman
			gender = Male
			type = Crew
			trait = Engineer
			brave = 0.2686244
			dumb = 0.6362562
			badS = False
			tour = False
			state = Assigned
			ToD = 0
			idx = -1
			CAREER_LOG
			{
				flight = 0
			}
			FLIGHT_LOG
			{
				flight = 0
			}
		}



after:


		KERBAL
		{
			name = Seemore Kerman
			gender = Male
			type = Crew
			trait = Engineer
			brave = 0.2686244
			dumb = 0.6362562
			badS = False
			tour = False
			state = Assigned
			ToD = 0
			idx = -1
			CAREER_LOG
			{
				flight = 0
			}
			FLIGHT_LOG
			{
				flight = 0
				0 = Land,Kerbin
			}
		}

**Comment by jrossignol** [comment]
Hmmm...  hyperedited a Kerbal to the same coordinates, and did a diff of the save to what you provided.  Here's the items for me to look at from the diff:
```
10,12c10,12
<                       met = 903.859999999475
<                       lct = 903.859999999475
<                       lastUT = -1
---
>                       met = 33.4671807861467
>                       lct = 132.743069458001
>                       lastUT = 166.230250244148
```
Should have to do with the last time it was updated, should be fine as is.
```
14,16c14,16
<                       lat = -1.77640504170036
<                       lon = 286.681273944899
<                       alt = 0
---
>                       lat = -1.77640470707676
>                       lon = 286.681275529967
>                       alt = -0.17109682073351
```
The slightly negative altitude is noteworthy, I may try that one out as a "fix".
```
24c24,27
<                       ctrl = False
---
>                       ctrl = True
>                       cPch = 0.356
>                       cHdg = -0.206
>                       cMod = 0
```
I think ctrl is whether the player can control it?  Pitch and heading stuff are probably not relevant.

**Comment by inigmatus** [comment]
I'm still testing. I could not duplicate it with just CC. Eliminating mods from my dev stack...

**Comment by inigmatus** [comment]
so far my mod list is down to:

CC
KAX (with dependencies Firespitter core and Firespitter Resources config)
HyperEdit
TakeCommand
KAS
KIS
Module Manager
QuickScroll
Toolbar
Wider Contracts App


Here is a log showing a flight scene duplication. Each game pause is a single pass of a stock Velocitize with a pilot (Jeb), and loaded SpawnPassenger (Lt. Dan Kerman from the Coast Guard) flying over a capsized SpawnVessel watercraft, and two SpawnKerbal kerbals in the water.

The third pass is captured by the third pause and end of this log, capturing the moment after my third pass where the Kerbals and even the ship immediately disappeared from the surface and respawned at the bottom of the sea.

[WRN 23:29:41.535] [HighLogic]: =========================== Scene Change : From FLIGHT to FLIGHT =====================
[LOG 23:29:42.206] [PlanetariumCamera]: Focus: Kerbin
[WRN 23:29:42.454] ApplicationLauncher already exist, destroying this instance
[LOG 23:29:42.456] QuickScroll(1.32): Settings Loaded
[LOG 23:29:42.462] AddonLoader: Instantiating addon 'NavWaypoint' from assembly 'KSP'
[LOG 23:29:42.465] AddonLoader: Instantiating addon 'KASAddonWinchGUI' from assembly 'KAS'
[LOG 23:29:42.465] AddonLoader: Instantiating addon 'KASAddonDebugTools' from assembly 'KAS'
[LOG 23:29:42.466] AddonLoader: Instantiating addon 'KASAddonControlKey' from assembly 'KAS'
[LOG 23:29:42.467] AddonLoader: Instantiating addon 'KISAddonCursor' from assembly 'KIS'
[LOG 23:29:42.467] AddonLoader: Instantiating addon 'KISAddonPickup' from assembly 'KIS'
[LOG 23:29:42.468] AddonLoader: Instantiating addon 'KISAddonPointer' from assembly 'KIS'
[LOG 23:29:42.469] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[LOG 23:29:42.508] ------------------- initializing flight mode... ------------------
[LOG 23:29:42.514] Target vessel index: 10  vessel count: 11
[LOG 23:29:42.515] [FLIGHT GLOBALS]: Switching To Vessel Velociteze ---------------------- 
[LOG 23:29:42.515] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[LOG 23:29:42.516] Reference Frame: Rotating
[WRN 23:29:42.532] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:29:42.544] [Part]: PartModule TransferDialogSpawner at Mark1Cockpit, index 8: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 23:29:42.545] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 23:29:42.545] PartModule is null.
[WRN 23:29:42.570] [Part]: PartModule TransferDialogSpawner at MK1CrewCabin, index 6: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 23:29:42.570] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 23:29:42.571] PartModule is null.
[LOG 23:29:42.660] [Velociteze]: landed - waiting for ground contact to resume physics...
[LOG 23:29:42.661] Camera Mode: AUTO
[LOG 23:29:42.670] stage manager resuming...
[LOG 23:29:44.029] all systems started
[LOG 23:29:44.065] Reloaded override drag cube for zeroed cube root part Mark1Cockpit (Velociteze) on vessel Velociteze
[LOG 23:29:44.096] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 23:29:44.098] [ScenarioUpgradeableFacilities]: Loading... 0 objects registered
[LOG 23:29:44.116] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: Contracts.Templates.CollectScience (Assembly-CSharp.dll)
[LOG 23:29:44.117] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: Contracts.Templates.ExploreBody (Assembly-CSharp.dll)
[LOG 23:29:44.118] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: Contracts.Templates.GrandTour (Assembly-CSharp.dll)
[LOG 23:29:44.118] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: Contracts.Templates.PartTest (Assembly-CSharp.dll)
[LOG 23:29:44.119] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: Contracts.Templates.PlantFlag (Assembly-CSharp.dll)
[LOG 23:29:44.120] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: Contracts.Templates.RecoverAsset (Assembly-CSharp.dll)
[LOG 23:29:44.120] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.ARMContract (Assembly-CSharp.dll)
[LOG 23:29:44.121] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.BaseContract (Assembly-CSharp.dll)
[LOG 23:29:44.121] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.ISRUContract (Assembly-CSharp.dll)
[LOG 23:29:44.122] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.SatelliteContract (Assembly-CSharp.dll)
[LOG 23:29:44.123] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.StationContract (Assembly-CSharp.dll)
[LOG 23:29:44.123] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.SurveyContract (Assembly-CSharp.dll)
[LOG 23:29:44.124] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.TourismContract (Assembly-CSharp.dll)
[LOG 23:29:44.125] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: FinePrint.Contracts.WorldFirstContract (Assembly-CSharp.dll)
[LOG 23:29:44.166] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: Contracts.Templates.CollectScience (Assembly-CSharp.dll)
[LOG 23:29:44.167] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: Contracts.Templates.ExploreBody (Assembly-CSharp.dll)
[LOG 23:29:44.167] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: Contracts.Templates.GrandTour (Assembly-CSharp.dll)
[LOG 23:29:44.168] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: Contracts.Templates.PartTest (Assembly-CSharp.dll)
[LOG 23:29:44.168] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: Contracts.Templates.PlantFlag (Assembly-CSharp.dll)
[LOG 23:29:44.169] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: Contracts.Templates.RecoverAsset (Assembly-CSharp.dll)
[LOG 23:29:44.170] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.ARMContract (Assembly-CSharp.dll)
[LOG 23:29:44.170] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.BaseContract (Assembly-CSharp.dll)
[LOG 23:29:44.171] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.ISRUContract (Assembly-CSharp.dll)
[LOG 23:29:44.171] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.SatelliteContract (Assembly-CSharp.dll)
[LOG 23:29:44.172] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.StationContract (Assembly-CSharp.dll)
[LOG 23:29:44.173] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.SurveyContract (Assembly-CSharp.dll)
[LOG 23:29:44.173] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.TourismContract (Assembly-CSharp.dll)
[LOG 23:29:44.174] [DEBUG] ContractConfigurator.ContractDisabler: Disabling ContractType: FinePrint.Contracts.WorldFirstContract (Assembly-CSharp.dll)
[ERR 23:29:44.179] Cannot find a Module of typename 'HoloDeck'

[ERR 23:29:44.180] ScenarioModule is null.

[ERR 23:29:44.180] Cannot find a Module of typename 'CustomWaypoints'

[ERR 23:29:44.180] ScenarioModule is null.

[LOG 23:29:44.181] Loading Depletion Nodes
[LOG 23:29:44.182] DepNodeCount:  0
[LOG 23:29:44.182] Loading Biome Nodes
[LOG 23:29:44.182] BiomeNodeCount:  0
[LOG 23:29:44.183] Loading Planet Nodes
[LOG 23:29:44.183] PlanetNodeCount:  0
[ERR 23:29:44.183] Cannot find a Module of typename 'TCAScenario'

[ERR 23:29:44.184] ScenarioModule is null.

[LOG 23:29:44.225] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [CoastGuard-Certification]
[LOG 23:29:45.038] [PlanetariumCamera]: Focus: Velociteze
[LOG 23:29:45.254] Flight State Captured
[LOG 23:29:45.272] Saving Achievements Tree...
[LOG 23:29:45.328] Game State Saved as persistent
[LOG 23:29:46.258] [00:00:00]: Velociteze boarded Mk1 Crew Cabin on Velociteze.
[LOG 23:29:46.377] [Velociteze]: ground contact! - error: 0.006m
[LOG 23:29:46.378] Unpacking Velociteze
[LOG 23:29:47.582] activating stage 0 - current stage: 1
[LOG 23:29:47.583] [Mark1Cockpit (Velociteze)]: Activated
[LOG 23:29:47.583] [SmallGearBay]: Activated
[LOG 23:29:47.584] [Mk1FuselageStructural]: Activated
[LOG 23:29:47.584] [Mk1FuselageStructural]: Activated
[LOG 23:29:47.584] [MK1CrewCabin]: Activated
[LOG 23:29:47.585] [sweptWing]: Activated
[LOG 23:29:47.585] [StandardCtrlSrf]: Activated
[LOG 23:29:47.585] [StandardCtrlSrf]: Activated
[LOG 23:29:47.586] [sweptWing]: Activated
[LOG 23:29:47.586] [StandardCtrlSrf]: Activated
[LOG 23:29:47.586] [StandardCtrlSrf]: Activated
[LOG 23:29:47.587] [SmallGearBay]: Activated
[LOG 23:29:47.587] [SmallGearBay]: Activated
[LOG 23:29:47.588] [pointyNoseConeB]: Activated
[LOG 23:29:47.588] [R8winglet]: Activated
[LOG 23:29:47.588] [R8winglet]: Activated
[LOG 23:29:47.589] [R8winglet]: Activated
[LOG 23:29:47.589] [miniFuselage]: Activated
[LOG 23:29:47.589] [miniIntake]: Activated
[LOG 23:29:47.590] [miniJetEngine]: Activated
[LOG 23:29:47.590] [miniFuselage]: Activated
[LOG 23:29:47.591] [miniIntake]: Activated
[LOG 23:29:47.592] [miniJetEngine]: Activated
[LOG 23:29:47.592] [telescopicLadder]: Activated
[LOG 23:29:47.592] [00:00:00]: Liftoff!!
[LOG 23:30:11.126] [Progress Node Reached]: RecordsSpeed
[LOG 23:30:14.373] [Progress Node Reached]: RecordsAltitude
[LOG 23:30:24.306] Added 1.99728 (2) reputation: 'Progression'.
[LOG 23:30:31.605] Added 1.997131 (2) reputation: 'Progression'.
[WRN 23:30:46.495] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:30:46.527] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:30:46.733] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:30:46.868] [Part]: PartModule indexing mismatch at probeCoreOcto2, index 2.
Node 'TWR1Data' found in loaded data, but 'ModuleTripLogger' is defined in prefab.
Looking for TWR1Data in other indices...
[WRN 23:30:46.869] ...no TWR1Data module found on part definition. Skipping...
[WRN 23:30:46.869] PartModule is null.
[WRN 23:30:46.870] [Part]: PartModule indexing mismatch at probeCoreOcto2, index 2.
Node 'RCSLandingAidModule' found in loaded data, but 'ModuleTripLogger' is defined in prefab.
Looking for RCSLandingAidModule in other indices...
[WRN 23:30:46.870] ...no RCSLandingAidModule module found on part definition. Skipping...
[WRN 23:30:46.871] PartModule is null.
[LOG 23:30:46.895] [TakeCommand] added escape hatch to seatExternalCmd (-299216)
[LOG 23:30:46.896] [TakeCommand] added escape hatch to seatExternalCmd (-299266)
[LOG 23:30:46.899] Reloaded override drag cube for zeroed cube root part structuralPanel2 (S.S. Alice) on vessel S.S. Alice
[LOG 23:30:46.927] [FlightIntegrator]: Vessel Tedemone Kerman has been unloaded 1.79769313486232E+308, applying analytic temperature 313.486440985534
[LOG 23:30:46.928] [FlightIntegrator]: Vessel Calemone Kerman has been unloaded 1.79769313486232E+308, applying analytic temperature 313.486464101123
[LOG 23:30:47.004] [FlightIntegrator]: Vessel S.S. Alice has been unloaded 1.79769313486232E+308, applying analytic temperature 313.486319766383
[LOG 23:30:48.127] Game Paused!
[LOG 23:30:48.127] Active Vessel is in atmosphere. Cannot save.
[LOG 23:31:18.455] Game Unpaused!
[LOG 23:31:24.880] Unpacking Tedemone Kerman
[LOG 23:31:24.881] Unpacking Calemone Kerman
[LOG 23:31:24.881] Unpacking S.S. Alice
[LOG 23:31:24.992] Unpacking kerbalEVA (Tedemone Kerman). Vel: (0.7, 0.0, -0.5)
[LOG 23:31:24.993] Unpacking kerbalEVA (Calemone Kerman). Vel: (0.7, 0.0, -0.5)
[LOG 23:31:26.820] Game Paused!
[LOG 23:31:26.820] Active Vessel is in atmosphere. Cannot save.
[LOG 23:31:29.521] Game Unpaused!
[LOG 23:31:30.012] Packing Calemone Kerman for orbit
[LOG 23:31:30.013] Packing S.S. Alice for orbit
[LOG 23:31:30.034] Packing Tedemone Kerman for orbit
[LOG 23:31:55.525] Unpacking Tedemone Kerman
[LOG 23:31:55.526] Unpacking Calemone Kerman
[LOG 23:31:55.543] Unpacking S.S. Alice
[LOG 23:31:55.581] Unpacking kerbalEVA (Tedemone Kerman). Vel: (0.0, 0.0, 0.0)
[LOG 23:31:55.581] Unpacking kerbalEVA (Calemone Kerman). Vel: (0.0, 0.0, 0.0)
[LOG 23:31:58.525] [Progress Node Reached]: Landing
[LOG 23:31:58.527] [Progress Node Reached]: Kerbin
[LOG 23:31:59.122] [Progress Node Complete]: Landing
[LOG 23:32:00.125] [Progress Node Reached]: Splashdown
[LOG 23:32:00.127] [Progress Node Complete]: Splashdown
[LOG 23:32:00.127] Added 0.9985162 (1) reputation: 'Progression'.
[LOG 23:32:00.847] Packing Tedemone Kerman for orbit
[LOG 23:32:00.847] Packing Calemone Kerman for orbit
[LOG 23:32:00.848] Packing S.S. Alice for orbit
[LOG 23:32:03.468] Game Paused!
[LOG 23:32:03.468] Active Vessel is in atmosphere. Cannot save.
[LOG 23:32:12.067] Game Unpaused!
[WRN 23:32:12.068] Can not play a disabled audio source
[LOG 23:32:30.825] [Calemone Kerman]: ground contact! - error: -1104.420m
[LOG 23:32:30.825] Unpacking Calemone Kerman
[LOG 23:32:30.842] [Tedemone Kerman]: ground contact! - error: -1104.394m
[LOG 23:32:30.843] Unpacking Tedemone Kerman
[LOG 23:32:30.843] Packing Calemone Kerman for orbit
[LOG 23:32:30.844] [S.S. Alice]: ground contact! - error: -1103.584m
[LOG 23:32:30.844] Unpacking S.S. Alice
[LOG 23:32:30.869] Packing Tedemone Kerman for orbit
[LOG 23:32:30.870] Packing S.S. Alice for orbit
[LOG 23:32:30.895] Unpacking kerbalEVA (Calemone Kerman). Vel: (0.0, 0.0, 0.0)
[LOG 23:32:30.918] Unpacking kerbalEVA (Tedemone Kerman). Vel: (0.0, 0.0, 0.0)
[LOG 23:32:31.950] Game Paused!

**Comment by inigmatus** [comment]
Ok, I was able to duplicate this only with Contract Configurator. Consistently. The logs above are still relevant. 

Here is a save file to test:
https://github.com/inigmatus/GAP/blob/master/Development/BugTest%23411.sfs

Here is the contract that is being used:
https://github.com/inigmatus/GAP/blob/master/CoastGuard-RescueFishermen.cfg

Here are the steps to duplicate:

1. Fly the Velocitize on the runway.
2. Load your passenger (Lt. Dan Kerman)
3. Fly to SOS waypoint
4. Fly over the S.S. Alice and Tedmone Kerman and Calemone Kerman within 100m (the distance GUI info will disappear)
5. Fly back over them within 100m a second time.
6. Fly back over them within 100m a third time.
7. At the third flyover within 100m, the S.S. Alice and two kerbals should disappear and spawn at bottom of the ocean.

**Comment by jrossignol** [comment]
I think this is a stock bug.  The SS Alice is magically changing to LANDED after the second pass.  On the third pass when re-entering physics range (somewhere between 100-200m), it realizes that landed means it should be on the ocean floor, and warps catastrophically.  Same goes with the Kerbals.

I'll try to pass this one on to NathanKell after doing a bit more testing.

**Comment by inigmatus** [comment]
thanks for investigating! looking forward to what Nathan says on it.

**Comment by inigmatus** [comment]
bug status on this one?

**Comment by jrossignol** [comment]
I need to take the saves and reduce it down to a stock only thing (basically just trim the contract configurator and other stuff out of the saves I have).  Once I have that I'll submit the bug.  Or if you're willing to help out on that, I can pass the saves I'm using on to you.

**Comment by inigmatus** [comment]
I wouldn't have a clue how to perform such save file surgery without confidentially not messing anything up heh.

**Comment by jrossignol** [comment]
No worries.  I'll get to it soon. :)

**Comment by inigmatus** [comment]
Here is a stock quick savefile: https://github.com/inigmatus/GAP/blob/master/Development/stockBugQuickSaveforCC411.sfs

I did the same steps as above, completely stock 100%

Here are the steps to duplicate:

Fly the Velocitize on the runway.
Load your passenger (Lt. Dan Kerman)
Fly to SOS waypoint
Fly over the S.S. Alice and Tedmone Kerman and Calemone Kerman within 100m (the distance GUI info will disappear)
Fly back over them within 100m a second time.
Fly back over them within 100m a third time.
At the third flyover within 100m, the S.S. Alice and two kerbals should disappear and spawn at bottom of the ocean.

was able to duplicate it pure stock. This is confirmed a stock bug.

**Comment by jrossignol** [comment]
Awesome!!  I'd like one more thing - can you do a quicksave in flight, right before the third pass (ie. a few seconds before the bug shows up).  With both files we'll be able to show the difference in the persistence files before things go pear shaped (which is what I observed in my saves).

**Comment by inigmatus** [comment]
...just one more pass... man I feel like its the battle of hoth... heh. savefile soon.

**Comment by inigmatus** [comment]
Here is the stock savefile, a few seconds right before the third pass, which when one passes over the Kerbals to where the distance GUI disappears, the kerbals and craft spawn at the bottom of the ocean floor:  https://github.com/inigmatus/GAP/blob/master/Development/RightBefore3rdPassCC411.sfs

**Comment by jrossignol** [comment]
Great stuff, I'll do some quick validation of my own and pass this on.

**Comment by jrossignol** [comment]
Okay, this one has been reported.  I'll update here if there's any action on it for 1.1.

**Comment by inigmatus** [comment]
Any action feedback for 1.1?

**Comment by jrossignol** [comment]
Won't know until 1.1 is out and we're able to test it ourselves.

**Comment by jrossignol** [comment]
Confirmed this one was fixed a long time ago, but wasn't able to officially close out until now. :+1:
