### ISSUE TITLE
Rate of climb indicator

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#412]
I was looking for a way to determine the rate of change of altitude.  This is something that is measured by a Variometer in an aircraft.  The ReachState has detection for speed, altitude, etc, but not for this.

 

This is also known as Rate of Climb, and Rate of Descent

 As a suggestion, have a new var called RateOfClimb, value to be in m/sec, positive is going up, negative going down

Thanks

**Comment by jrossignol** [comment]
Easy enough for 1.9.2 - dot product with the normal vector will give this value.  To be added to ReachState.

**Comment by jrossignol** [comment]
Done for 1.9.2

**Comment by linuxgurugamer** [comment]
Thank you.
I'll be able to use this to generate contracts which will require a descending vector, finally
