### ISSUE TITLE
Feature request - Is it possible to have a mod edit an existing mod to be able to extend a contract's duration for some sort of payment in either cash or rep?

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#414]
Is it possible to have a mod edit an existing mod to be able to extend a contract's duration for some sort of payment in either cash or rep?

LGG

**Comment by jrossignol** [comment]
I need to understand this one a little be more.  You want something (like a GUI?) to allow a Duration parameter to have its time increased at a cost to the player?

If that's correct, it's doable as a separate C# mod, but would be considered out of scope for Contract Configurator.

**Comment by linuxgurugamer** [comment]
Ok.  I'd be happy to write it, are there some pointers you can give me?  So far the mods I've written have not been gameplay related (other than the contracts, of course)

**Comment by jrossignol** [comment]
Well, you'd need some sort of UI (you can look at my debug UI for displaying contract types, although that's a pretty complex one), and the hooks into Duration to increment the timer (it's just a double, but I'd need to expose it via a public member).  Let me know if you're moving forward with this and I'll do that.

**Comment by linuxgurugamer** [comment]
If I do this, could you add a new variable (?) which contact authors 
could use to specify the penalty?

It would be either credits or rep, and could be either a percentage or a 
flat amount (or both).  The percentage would be used to reduce the 
reward for that contract, and amount could either do the same or just an 
immediate deduction from available cash.

for this, I guess I would need a hook to the contract rewards, as well 
as a way to get the penalty(s)

**Comment by jrossignol** [comment]
They're all public already, and for the extra stuff you could use a DATA node on the config side (ends up in a DataNode on the [ContractType](https://github.com/jrossignol/ContractConfigurator/blob/master/source/ContractConfigurator/ContractType.cs#L74)).

**Comment by jrossignol** [comment]
Cleaning up, nothing to be done here, let me know if you need more support.
