### ISSUE TITLE
Duration start at a mission launch

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#415]
Also, can the duration be set up to start at a mission launch?  This is harder, I'm sure, but figured I'd ask.

LGG

**Comment by jrossignol** [comment]
It's doable, but it's not a significant difference from starting on contract accept - (just the time it takes to click to the VAB or launchpad).  Unless this is for an auto-accept contract.

Could you let me know why you need this?

**Comment by linuxgurugamer** [comment]
Sure.  I had a complaint from a streamer that he would accept contracts, which normally would have a duration of, say, 100 days.  The contract was to go to Duna with a probe (ignore the fact that it probably takes longer than 100 days, this is an example).  They build the rocket, and save it, and have to wait somewhere between 90 and 200 days for a launch window.  The contract expires.  If, the contract would start at the launch of the rocket, it would be more doable.

Thanks

**Comment by jrossignol** [comment]
Okay.  I'm still a little bit iffy on it because it doesn't work very well with someone running multiple missions.  However there will also be the ability to do it off a parameter completion too (much like some of the triggered behaviours).

**Comment by linuxgurugamer** [comment]
Ok.  So, tell me if this is what you are envisioning:  put a specific part on a ship, have the duration start when that part becomes flying.  It may also make sense in this case to require a specific name for the ship at launch, so that the contract knows which ship it is for.  Actually, thinking about it, that may be the best way.  No special parts, but a special ship name.  Maybe a 4 letter code in the name?

**Comment by jrossignol** [comment]
I'm not a fan of having to enforce naming conventions and things like that on the player.  What I'll do is allow the duration timer to start on a number of conditions:
 * Contract acceptance
 * Next Launch
 * Parameter Completion

The parameter completion is the one that will let you do anything you want - you can even tie it to an invisitible parameter.  It could be a parameter that says a vessel must be on the launch pad (or maybe in orbit) with a specific set of parts, or specific crew composition).  Basically, I'll leave that flexibility up to the contract author.

**Comment by linuxgurugamer** [comment]
Well, I normally would agree with you about naming conventions, but not 
going to argue  :-)

Maybe I'll come up with some parts to be tied to these sorts of contracts.

Thanks


JBB

**Comment by jrossignol** [comment]
Defer to 1.9.4

**Comment by jrossignol** [comment]
Done for 1.9.4
