### ISSUE TITLE
VesselParameterGroup: Add hideVesselName attribute to hide the vessel child parameter

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#416]
I have a VPG used to ensure a specific vessel completes a set of parameters that have children info that I want displayed but not the vessel name (which always shows up in the contract window as TBD). I can hide the vessel name currently using hideChildren = true, but this also hides all the sub parameter children info as well from the contract window.

Is there a way to just hide the vessel name used for a VPG but show sub parameter children info?

Simple attribute desired: hideVesselName = true

**Comment by jrossignol** [comment]
If I'm not mistaken, it shouldn't display any of that if you use a custom title on the VesselParameterGroup.  Can you confirm that, and if not I can make this change.

**Comment by inigmatus** [comment]
I can confirm custom titles are not hiding the vessel name when a subparameter such as a visitwaypoint or HasPassengers exists with child info for display.

**Comment by jrossignol** [comment]
Can you show me a screenshot?  I'm looking at the code and that shouldn't be the case, so either I'm reading it wrong (sick at the moment, so not out of the question), or there's a misunderstanding somewhere.

**Comment by inigmatus** [comment]
not able at the moment, however, i just drafted a bug test for you when you get a moment:

https://github.com/inigmatus/GAP/blob/master/Development/BugTest%23416.cfg

if I remember right, a VPG with a define attribute gets hidden when title attribute exists, but VPG with a vessel attribute does NOT get hidden when a title attribute exists, and instead displays the name of the craft variable and (TBD) even though contract window shows it passing.

**Comment by inigmatus** [comment]
oh, and forgot to say - sorry to hear you're sick. get well soon!

**Comment by jrossignol** [comment]
Don't need a screenshot, the contract will do fine.

**Comment by jrossignol** [comment]
Okay, now I see what you were getting at.  Will do this one as an enhancement.  Milestone TBD.

**Comment by jrossignol** [comment]
Target 1.9.3

**Comment by jrossignol** [comment]
Done for 1.9.3

**Comment by inigmatus** [comment]
Tested. Rather than (Craft: TBD) it now says (Optional) in the contract window app when hideVesselName = true. Is this intended?

**Comment by inigmatus** [comment]
http://i.imgur.com/RAOywt4.png

**Comment by jrossignol** [comment]
Probably not. Can you show me the vpg?

**Comment by inigmatus** [comment]
PARAMETER
	{
		name = VesselParameterGroup
		type = VesselParameterGroup
		title = and load your passenger

		vessel = craft
		hideVesselName = true
		
		PARAMETER
		{
			name = HasPassengers
			type = HasPassengers
			
		}
	
	}

**Comment by jrossignol** [comment]
Easy fix - should be actually hidden now.

**Comment by inigmatus** [comment]
Ok, now it disappears from app window, but still not from Mission Control.

**Comment by jrossignol** [comment]
Stupid mission control.  I'll note it in #426

**Comment by inigmatus** [comment]
Cool beans. Low priority for GAP right now. Can wait to 1.9.4 or higher on this one if you want to work on getting 1.9.3 out.

**Comment by inigmatus** [comment]
tagging for you to reopen until #429 is fixed.

**Comment by jrossignol** [comment]
Nah, this will stay closed, #426 is a separate and actually very long standing issue (despite going unreported for a long while). I've put a link the other way, do this will get retested.

**Comment by jrossignol** [comment]
Darn mobile. #429. Link all the things
