### ISSUE TITLE
ReachState maxAltitude negative value not recognized (for underwater parameters)

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#417]
Trying to get this to complete:

https://github.com/inigmatus/GAP/blob/master/SSI-Submarine.cfg

but instead the ReachState is not recognizing the maxAltitude = -50.0

http://i.imgur.com/eBMWWxI.png

http://i.imgur.com/fWzKjDo.png

**Comment by inigmatus** [comment]
pinging for inclusion in 1.9.2 or 1.9.3

**Comment by jrossignol** [comment]
It'll be one of those. Waiting to decide whether it'll make sense to do in
1.9.2 or 1.9.3.

**Comment by inigmatus** [comment]
PARAMETER
	{
		name = VesselParameterGroup
		type = VesselParameterGroup
		title = and dive to 50m below the surface
		
		vessel = @/craft
		
		PARAMETER
		{			            
			name = ReachState   
			type = ReachState

			situation = SPLASHED
			maxAltitude = -50.0
			
		}
		
		completeInSequence = true
		hideChildren = true
		
	}

**Comment by jrossignol** [comment]
Will try to get this as a 1.9.2 item.

**Comment by inigmatus** [comment]
ive worked around this for now using a waypoint. not necessary for GAP 1.0. feel free to defer this to 1.9.3 or later.

**Comment by jrossignol** [comment]
Nah, needed to get another easy one to get warmed up, working it now

**Comment by inigmatus** [comment]
:)

**Comment by jrossignol** [comment]
Easy fix, was using 0.0 as the default for minAltitude, which was why it didn't work.

**Comment by inigmatus** [comment]
confirmed fixed. thanks!
