### ISSUE TITLE
Load Passengers causing Argument out of Range exception error

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#418]
Contract:
https://github.com/inigmatus/GAP/blob/master/Airlines-Flight-101.cfg

For my magnum opus GAP contract: Flight 101 where a player loads anywhere from 8 to 80 tourists for an island flight and back, the Load Passengers GUI loads the passengers when clicked but fails to complete or finish, leaving a warning on leftover seats, however for purposes of the contract, the passengers are loaded fine:

http://i.imgur.com/yWdUuV5.png

http://i.imgur.com/AsssiWD.png

I am getting in the the log the following: 

[LOG 14:17:33.712] Flight State Captured
[LOG 14:17:33.739] Saving Achievements Tree...
[LOG 14:17:33.739] Saving Achievements Tree...
[LOG 14:17:33.810] Game State Saved as persistent
[LOG 14:17:35.674] [T-100]: ground contact! - error: -0.146m
[LOG 14:17:35.677] Unpacking T-100
[LOG 14:17:40.417] [00:00:03]: T-100 boarded Mk3 Cockpit on T-100.
[LOG 14:17:40.446] [00:00:03]: T-100 boarded Mk3 Passenger Module on T-100.
[EXC 14:17:42.461] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[EventData`1+[GameEvents+HostedFromToAction`2[ProtoCrewMember,Part]]].get_Item (Int32 index)
	EventData`1[GameEvents+HostedFromToAction`2[ProtoCrewMember,Part]].Fire (HostedFromToAction`2 data)
	ContractConfigurator.Behaviour.SpawnPassengers.AddPassengersToActiveVessel ()
	ContractConfigurator.Behaviour.SpawnPassengers+PassengerLoader.PassengerDialog (Int32 windowID)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 14:17:49.648] [Orbit Targeter]: Target is null
[LOG 14:18:05.189] activating stage 0 - current stage: 1
[LOG 14:18:05.190] [mk3Cockpit.Shuttle]: Activated
[LOG 14:18:05.190] [GearMedium]: Activated
[LOG 14:18:05.191] [noseCone]: Activated

**Comment by inigmatus** [comment]
I am not sure CC is coded to allow loading that many passengers.

**Comment by inigmatus** [comment]
This happens regardless if HasCrew or HasPassengers is used as the loading parameter.

**Comment by jrossignol** [comment]
Might be related (or even the same issue as #410).  If it is, it's supposed to be fixed in 1.1.

**Comment by jrossignol** [comment]
Assume bug for now, target 1.9.3

**Comment by jrossignol** [comment]
Won't be fixed in Contract Configurator, will wait for the stock fix in KSP 1.1

**Comment by jrossignol** [comment]
Confirmed as fixed in 1.1.

**Comment by jrossignol** [comment]
Should be fixed by KSP 1.1
