### ISSUE TITLE
Break out celestial body milestone requirements into manned/unmanned versions

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#420]
New feature of 1.0.5 tracks manned and unmanned progress in different trees.

**Comment by linuxgurugamer** [comment]
Oh, cool!  This would be so handy for me!

**Comment by jrossignol** [comment]
Basically the same code that is in Strategia, but there's problems there (see https://github.com/jrossignol/Strategia/issues/15).  Need to get that ironed out and then do the same thing.

**Comment by jrossignol** [comment]
Added a checkType attribute to all the CelestialBody requirements (valid values are Unmanned and Manned).

**Comment by jrossignol** [comment]
Fixed by 5e76f2a
