### ISSUE TITLE
Support for list of names in RANDOM_WAYPOINT (and similar nodes) in WaypointGenerator

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#422]
when generating a RANDOM_WAYPOINT, I'd like the name to be unique for each.  I have a number of strings in a list, which I'd like to use for this

Also. the "parameter =", would be useful if it could refer to a generated parameter name, so that a number of waypoints can be generated, each dependent on a different parameter.

**Comment by jrossignol** [comment]
Defer to 1.9.4

**Comment by jrossignol** [comment]
Done for 1.9.4.
