### ISSUE TITLE
Support for "chained" waypoints in RANDOM_WAYPOINT_NEAR

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#423]
the nearIndex, would be nice if, instead of all the waypoints being near a single one, if each could be near the previous one.

**Comment by inigmatus** [comment]
you can manually do this creating separate waypoints each referencing next in index.

**Comment by linuxgurugamer** [comment]
I know that.  Nightingale asked that I post this as an Enhancement request, which is why the subject line says "Enhancement".
You are correct, and that is what I'm doing, but it makes the file much longer and harder to change

**Comment by jrossignol** [comment]
Defer to 1.9.4

**Comment by jrossignol** [comment]
Added for 1.9.4, there is now a chained boolean that can be specified that will put it in chained mode.

**Comment by linuxgurugamer** [comment]
Thank you
