### ISSUE TITLE
Crew not a recognized node in SpawnVessel

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#424]
https://github.com/jrossignol/ContractConfigurator/wiki/SpawnVessel-Behaviour

The crew node returns unrecognized in debug:

	BEHAVIOUR
	{
		name = SpawnVessel
		type = SpawnVessel
		deferVesselCreation = false

		VESSEL
		{
			name = KSS Rix
			craftURL = ContractPacks/GAP/Assets/Sea/Inigma Class Carrier.craft
			vesselType = Ship
			owned = false
			targetBody = Kerbin
			
			lat = @/carrierLat
			lon = @/carrierLon
			alt = -1
			heading = 90
			
		}
		
		CREW
                {
			name = Adm. Redbiertje Kerman
			gender = male
			addToRoster = false
			
		}
       }

[Warning]: ContractConfigurator.Behaviour.SpawnVesselFactory: CONTRACT_TYPE 'KSP-CarrierLanding', BEHAVIOUR 'SpawnVessel' of type 'SpawnVessel': unexpected child node 'CREW' found, ignored.

**Comment by jrossignol** [comment]
It's in the wrong spot - needs to be in the vessel node (crew belongs to a
vessel).

**Comment by inigmatus** [comment]
yup. my bad.
