### ISSUE TITLE
ReachState failWhenUnmet = true not failing a contract, but only sets parameter to not completed.

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#426]
I have this parameter in a contract:

    PARAMETER
    {
        name = ReachState
        type = ReachState
        
        maxAcceleration = 2.0
        
        failWhenUnmet = true
    }

This parameter shows with green completed check mark as expected. But when you exceed 2 gees, the parameter loses its green completed check mark, and it doesn't fail the contract, but instead when the craft goes back under 2 gees, the parameter goes back to complete with a green check mark. Is this working as designed, or is this attribute supposed to fail the contract outright?

**Comment by jrossignol** [comment]
Bug, investigate for 1.9.2

**Comment by jrossignol** [comment]
Partially fixed, the failWhenUnmet flag wasn't being saved to the persistence file.  But it still doesn't work in this case, and fixing it could have other repercussions.  Too risky with 1.9.2 coming in the next few days, move to 1.9.3.

**Comment by jrossignol** [comment]
Fixed for 1.9.3

**Comment by inigmatus** [comment]
confirmed fixed.
