### ISSUE TITLE
completeInSequence doesn't work, at least with iteratived parameters

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#428]
Doesn't work for anything other than the 1st set of iteratived parameters.

You already downloaded (I think) the zip file, let me know if you need anything else

**Comment by jrossignol** [comment]
Need all the details here or at least a link back to the post - otherwise
when I get to this in going to have no idea what it's about.

**Comment by linuxgurugamer** [comment]
Here it is, I'll keep it around for a while;  https://www.dropbox.com/s/av34v4m935o63yz/rover.zip?dl=0

**Comment by jrossignol** [comment]
Nothing to do with iterated parameters, this is a problem with CollectScience.

**Comment by jrossignol** [comment]
Pushed a fix for what I believe is the problem here.  Please let me know if that resolves your issue.
