### ISSUE TITLE
Running an experiment when requirements aren't fulfilled, will be listed as completed when the requirements ARE fulfilled

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#431]
I reorganized the rover missions to put all the science experiments after all the waypoints.  When used properly, it works.  However, if I run any of the experiments before reaching the last waypoint (the last waypoint is the first parameter in a sequence where the experiments are), when I do reach the last waypoint that experiment is shown as completed.
Here is a link to the modified contract:  

https://www.dropbox.com/s/zuespqsxkz4m84d/roverScienceAtEnd.zip?dl=0

I'm going to release this, since it's fairly minor IMHO.  But I wonder if this is related to one of the other issues I raised

I just updated the link since I put it in a safe place to save (so I won't delete it)

**Comment by jrossignol** [comment]
Fixed by #428
