### ISSUE TITLE
SpawnKerbals are showing up on roster as MIA after contract completion

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#437]
I can't seem to figure this out. This could turn serious fast.

All SpawnKerbals in GAP are usually programmed like this:

	BEHAVIOUR
	{
		name = SpawnKerbal
		type = SpawnKerbal

		KERBAL
		{
		
			kerbal = @/kerbalsSSI.ElementAt(0)  //i use a data note to specify a list of NewKerbals
			kerbalType = Unowned
			owned = false
			addToRoster = false
			
			pqsCity = KSC
			pqsOffset = -635.450871107884, 44.6770752507737, 25.391827671981
			alt = 75
			heading = 314

		}
		
	}

My SSI-Start contract: https://github.com/inigmatus/GAP/blob/master/SSI-Start.cfg
My Flight38 contract: https://github.com/inigmatus/GAP/blob/master/IslandTours-Flight-38.cfg

Yet when a player completes these contracts (by recovering the Kerbals), the recovered NewKerbal SpawnKerbals above are not removed from the roster entirely, but show up in the MIA list. Some players even report that after contract completion, these kerbals show up available on the roster: http://forum.kerbalspaceprogram.com/index.php?/topic/129208-contract-pack-giving-aircraft-a-purpose-gap-101-beta-air-flights-tours-coast-guard-sts-jan-5-2016/&do=findComment&comment=2351410

Ok, so I figure there's something going on. So then I resorted to using this as a possible work around:

	BEHAVIOUR
	{
		name = RemoveKerbal
		type = RemoveKerbal
		
		kerbal = Inigma Kerman
		
	}

On craft load from runway, I get:

Exception occured while saving contract 'SSI-Start':
System.NullReferenceException: Object reference not set to an instance of an object
  at ContractConfigurator.Behaviour.RemoveKerbalBehaviour.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractBehaviour.Save (.ConfigNode configNode) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ConfiguredContract.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0 

Something's amiss with these SpawnKerbals it seems. Isn't CC supposed to be removing SpawnKerbals entirely from the roster on contract completion?  This could turn serious because after a while as players play the repeatable contracts such as the charter flights, their rosters will start to fill up rather quickly.

**Comment by jrossignol** [comment]
Fixed the RemoveKerbal exception - that much was easy.

Let me poke around a bit and see if I can figure out how the MIA thing works.

**Comment by jrossignol** [comment]
Hoping you have a test set up for this one, I can't see how Kerbals get in the MIA list, but I have a guess - it's based on the respawn settings, and it's triggering off the removal event (I would've expected it on the killed event).  Anyway, if my guess is right the fix should hopefully work.

**Comment by inigmatus** [comment]
Testing now...

**Comment by inigmatus** [comment]
RemoveKerbal works now without the exception, and works fine to remove the Kerbal from the roster as expected. However if I don't use RemoveKerbal, and the recovered Kerbal shows up on the Lost list.

**Comment by jrossignol** [comment]
Okay, that gives me some hints, I'll look at this more tomorrow in more
depth.

**Comment by inigmatus** [comment]
ty. i should prob add RemoveKerbal anyways to my contracts to give them a proper washdown anyways, and it serves for now as a decent work around.

**Comment by jrossignol** [comment]
Except that RemoveKerbal is completely broken in the released version. 😛

**Comment by inigmatus** [comment]
thankfully no one is using it. yet. and i suppose rosters can handle a large number of MIAs for now. :) With 1.1 looming, I expect a lot of new careers, so it's not that serious yet.

**Comment by jrossignol** [comment]
Okay, think I got this one, report back and I'll reopen if you're still seeing issues.

**Comment by inigmatus** [comment]
confirmed fixed. thanks again! you are awesome!
