### ISSUE TITLE
Add CelestialBody.ContractCompleteForBody()

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#444]
per your comment:

@targetBody = AllBodies.Where(cb => cb.ContractCompleteForBody(FirstImpact_Unmanned)).Random()

So, this would be a function for a CelestialBody, and would return true if the specified contract had been completed for that body, false otherwise

**Comment by jrossignol** [comment]
Assume this is not needed due to the support for Lists in global variables.
