### ISSUE TITLE
Support lists in the global variables

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#445]
Lists aren't actually supported in the global variables.  They're not explicitly not supported (which is why you don't get a nice clean error), but I'll need to write a bunch of code to make it work.  Raise an enhancement request and I'll try to get it for you in 1.9.4

**Comment by jrossignol** [comment]
Fixed for 1.9.4

**Comment by linuxgurugamer** [comment]
Thanks
