### ISSUE TITLE
Add new parameter:  maxCompletionsPerCelestialBody

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#446]
This would be similar to the current maxCompletions, but it would limit it for each body, not globally

**Comment by jrossignol** [comment]
If you are only trying to limit it to one completion per celestial body, then you can do that by storing the celestial body in a data node value and setting uniqnessCheck to CONTRACT_ALL (@severedsolo has examples in his contract packs, I believe).

If you want to do maxCompletions per body of an arbitrary value, then yes, a change is needed (although you could probably rig something up with the uniquenessCheck plus a global variable counter).

**Comment by linuxgurugamer** [comment]
Well, that is what I was trying to do with the persistent lists, which don't work yet.  I'll look at @severedsolo's packs, but I'm also trying to make this Kopernicus compatible, which means no hard-coded planet names, and I don't think (correct me if I'm wrong) that I can store a generated name in the persistent data store (ie:  create a var based on the @/targetBody)

**Comment by jrossignol** [comment]
Didn't realize I never answered this.

You definitely can store the generated name in the persistence file, should look something like this:
```
DATA
{
   type = CelestialBody
   uniqnessCheck = CONTRACT_ALL

   contractBody = @targetBody
}
```

**Comment by jrossignol** [comment]
Given the list support in #445, is this still needed?

**Comment by jrossignol** [comment]
Preference is to use generic lists, instead of something specific to celestial bodies - so will close this out for now.
