### ISSUE TITLE
Enhancement: ReachState add attribute RateofClimb

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#447]
Desired for GAP speed contracts requiring player to hold airplane in level flight:

a simple RateofClimb attribute whose value allows for positive and negative deviations:

RateofClimb = 10

would pass when a craft's rate of climb is between -10 m/s and 10 m/s.  Currently maxRateofClimb only checks for positive values.

**Comment by jrossignol** [comment]
That's a bug, it really should allow for negative values.

**Comment by inigmatus** [comment]
A bug then! I found a bug. I'm awesome.

**Comment by jrossignol** [comment]
The default for minRateOfClimb is now double.minValue (effectively negative infinity) instead of 0.0.

Pinging @linuxgurugamer in case the new default breaks something for him.

Fixed for 1.9.4

**Comment by inigmatus** [comment]
Sorry, not working as expected. Also, shouldn't this be for both minRateofClimb and maxRateofClimb?

anyways, here's the code:

			PARAMETER
			{
				name = ReachState
				type = ReachState
				
				targetBody = Kerbin
				situation = FLYING
				minRateOfClimb = 10

				disableOnStateChange = false
				hideChildren = true
				hidden = true
				
			}

Result:

Flying a plane with more than 10 negative m/s (dive) does not pass.
Flying a plane between -10 and 10 m/s (level) does not pass.
Flying a plane with more than 10 positive m/s (climb) passes.

If I flip it around to use a maxRateofClimb rather than minRateofClimb:


			PARAMETER
			{
				name = ReachState
				type = ReachState
				
				targetBody = Kerbin
				situation = FLYING
				maxRateOfClimb = 10

				disableOnStateChange = false
				hideChildren = true
				hidden = true
				
			}


Result:

Flying a plane with more than 10 negative m/s (dive) does not pass.
Flying a plane between -10 and 10 m/s (level) does not pass.
Flying a plane with more than 10 positive m/s (climb) does not pass.
Flying a plane with more than 10 positive m/s and then diving below 10 positive m/s to negative infinity m/s passes. 

If I try to limit the infinity of the dive by doing the following:

			PARAMETER
			{
				name = ReachState
				type = ReachState
				
				targetBody = Kerbin
				situation = FLYING
				minRateofClimb = -10
				maxRateOfClimb = 10

				disableOnStateChange = false
				hideChildren = true
				hidden = true
				
			}

Result is exactly the same: 

Flying a plane with more than 10 negative m/s (dive) does not pass.
Flying a plane between -10 and 10 m/s (level) does not pass.
Flying a plane with more than 10 positive m/s (climb) does not pass.
Flying a plane with more than 10 positive m/s and then diving below 10 positive m/s to negative infinity m/s passes. 

Something's not working here.

**Comment by inigmatus** [comment]
I think this is why:

even when just using minRateofClimb, and no other attribute:

[Warning]: ContractConfigurator.ReachStateFactory: CONTRACT_TYPE 'Wright-Speed100', PARAMETER 'ReachState' of type 'ReachState': unexpected attribute 'minRateofClimb' found, ignored.

**Comment by inigmatus** [comment]
disregard. must have been a reloading bug with CC.  this works perfectly:

			PARAMETER
			{
				name = ReachState
				type = ReachState
				
				targetBody = Kerbin
				situation = FLYING
				minRateOfClimb = -10
				maxRateOfClimb = 10

				disableOnStateChange = false
				hideChildren = true
				hidden = true
				
			}

**Comment by inigmatus** [comment]
you can keep this issue closed.

**Comment by linuxgurugamer** [comment]
Thanks for the ping, but I have't yet used it so it's fine for me
