### ISSUE TITLE
PartValidation MODULE EngineType attribute not recognized

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#452]
From: https://github.com/jrossignol/ContractConfigurator/issues/449

After more testing, I think it's a problem with CC not recognizing EngineType?

After all, this works:

    PARAMETER
    {
        name = PartValidation
        type = PartValidation

        FILTER
        {
            MODULE
            {
                experimentID = mysteryGoo

            }
        }

        minCount = 1

    }
and accurately validates if i have a goo canister.

but this does not:
```
    PARAMETER
    {
        name = PartValidation
        type = PartValidation

        FILTER
        {
            MODULE
            {
                EngineType = SolidBooster
            }
        }

        minCount = 1
    }
```
and fails to validate, even if I have a Flea solid booster.

My ultimate goal is for this to work:
```
PARAMETER
{
    name = PartValidation
    type = PartValidation
    title = not have any solid rocket motors

    FILTER
    {
        partModule = ModuleEngines
    }

    NONE
    {
        MODULE
        {
            EngineType = SolidBooster
        }
    }
}
```
Which currently fails to pass on any engine, solid booster or not. I suspect the filter serves up a list of engines with ModuleEngines, and attempts to require none that have a module; rather than none that have a module with attribute EngineType set to SolidBooster.

**Comment by jrossignol** [comment]
There were two problems - a bug with the NONE + MODULE (you were right, the text didn't make sense).

However, for reasons that are unknown to me, the EngineType doesn't end up in the module config after loading (everything else does).  I got it working using this:
```
    PARAMETER
    {
        name = PartValidation
        type = PartValidation
        title = not have any solid rocket motors

        FILTER
        {
            partModule = ModuleEngines
        }

        NONE
        {
            MODULE
            {
                allowShutdown = False
            }
        }
    }
```
Fixed for 1.9.4

**Comment by inigmatus** [comment]
ty ill test it out

**Comment by inigmatus** [comment]
PARAMETER
		{
			name = PartValidation
			type = PartValidation
			title = not have any solid rocket motors

			FILTER
			{
				partModule = ModuleEngines
			}

			NONE
			{
				MODULE
				{
					allowShutdown = False
				}
			}
		}

has the interesting effect of showing the following in the contract app:

a craft without Solid Rockets produces -

(not passing) not have any solid motors
     (fail) With module: Engines
     (pass) None have module

and never completes.

if  a craft has SRBs, it produces -

(not passing) not have any solid motors
     (pass) With module: Engines
     (fail) None have module

and never completes.

darned if i do, darned if I don't. heh.

**Comment by inigmatus** [comment]
for some reason the intended result appears inverted on the NONE check. Can you confirm?

**Comment by jrossignol** [comment]
Well, I sort of fixed the text issue (it's a bit of a band-aid fix for now).  I reworked your parameter, and this worked for me - let me know if it doesn't for you:
```
        PARAMETER
        {
            name = PartValidation
            type = PartValidation
            title = not have any solid rocket motors

            NONE
            {
                MODULE
                {
                    name = ModuleEngines
                    allowShutdown = False
                }
            }
        }
```

**Comment by inigmatus** [comment]
testing...

**Comment by inigmatus** [comment]
argh... something still not working.

text shows up fine now (good job). but

        PARAMETER
        {
            name = PartValidation
            type = PartValidation
            title = not have any solid rocket motors

            NONE
            {
                MODULE
                {
                    name = ModuleEngines
                    allowShutdown = False
                }
            }
        }


produces on a craft with no SRBs:

(not passing) not have any solid rocket motors
      (pass) None have module: With Name Engines; With Allow Shutdown: False


produces on a craft with SRBs:

(not passing) not have any solid rocket motors
      (fail) None have module: With Name Engines; With Allow Shutdown: False

**Comment by inigmatus** [comment]
the PartValidation parent is not passing, even though the child NONE>MODULE is.

**Comment by jrossignol** [comment]
That one was a real pain to track down.  Now it should be working.

**Comment by inigmatus** [comment]
big difference a single word can make. :) 

newValues

confirmed fixed. thanks for tracking this down. any idea why EngineType not recognized? Is it an MM issue that we need to report?

**Comment by jrossignol** [comment]
Stock just doesn't expose it. Not much we can do.

**Comment by inigmatus** [comment]
Thanks again!  BTW, where are you checking to see if Stock exposes it? You said it doesn't "end up in the module config" - where is that exactly, so I can do my own checking and leave you alone and bring it to Squad if any other attributes are not recognized in my development?

**Comment by jrossignol** [comment]
Nowhere easy.  You can look at the .dll through visual studio and check if the field for the module in question has `[KSPField]` on it.  Or you can look at [PartModule.Fields](https://github.com/jrossignol/ContractConfigurator/blob/83d7edb66de72469de07f91bb55f34e1bd7eac62/source/ContractConfigurator/Parameter/VesselParameter/PartValidation.cs#L173-L193).

99% of the time, if it's in the config, it should work.  You found the exception.

**Comment by inigmatus** [comment]
Thanks for the info. And thanks again for all your hard work!
