### ISSUE TITLE
HasResource and HasResourceCapacity only recognizing tank values, but not engine presence

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#455]
This fails any craft that has even 0.1 of oxidizer (as expected), and passes when oxidizer tank levels are at 0.0 (as expected):

		PARAMETER
		{
			name = HasResource
			type = HasResource
			title = not have any liquid rocket engines
			
			resource = Oxidizer
			
			minQuantity = 0.0
			maxQuantity = 0.0
	
		}

But this only checks for fuel tanks, not engines. If I have no oxidizer tank on my craft, I can still attach a liquid fuel rocket engine to the craft, and it will pass. I don't want players to have a liquid fuel rocket engine on their craft at all, even for aesthetics.

Per http://forum.kerbalspaceprogram.com/index.php?/topic/91625-105-contract-configurator-v1931-2016-01-11/&do=findComment&comment=2369801 you suggested I use HasResource instead of submitting an enhancement requesting a CC coding for a PartValidation to recognize a MODULE>PROPELLANT node that would allow me to limit a player from mounting a liquid fuel rocket engine (based on the oxider propellant check), or any other type of engine based on its fuel type. Bear in mind that this is all because I simply want to limit the kind of engines a player can use for a craft and thus get around the current stock limitation where the MODULE>EngineType attribute is not available for CC to read and act on.

HasResource and HasResourceCapacity seem to only work when a craft has a measurable amount of resource such as when there is a fuel tank, but not when there is just engines and no fuel tank.

Granted, HasResource is a workaround, but it's not really clean to meet the actual design goal of limiting what a player's craft looks like.

Thoughts?

**Comment by jrossignol** [comment]
Okay - I misunderstood when you said that HasResource wasn't working.  This is working correctly as having a LFO engine doesn't mean that you have the Oxidizer resource (or capacity for it).  So far all the suggestions have been very high effort - so instead I just added a 3 line hack to make EngineType actually work.  Enjoy. :wink:

**Comment by jrossignol** [comment]
Oh, and I don't have the ability to test the change that I made at the moment...  but it's a super simple one and it should be safe.... let me know if you hit any issues.

**Comment by inigmatus** [comment]
I could hug you. Works perfect now. I tested all engine types. We can bury this one for now.
