### ISSUE TITLE
SpawnVessel spawning wrong locations when using PQS

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#457]
New critical issue with current CC dev version: any craft in a contract that has PQS values listed in SpawnVessel is spawning on the wrong side of the planet.

	BEHAVIOUR
	{
		name = SpawnVessel
		type = SpawnVessel

		VESSEL
		{
			name = Tool Shed
			craftURL = ContractPacks/GAP/Assets/Land/Tool Shed.craft
			flagURL = ContractPacks/GAP/Assets/Flags/WrightAeronautical
			vesselType = Base
			owned = true
			
			pqsCity = KSC
			pqsOffset = -721.424290228473, -401.674350365971, 25.594521292589
			heading = 198

		}
		
	}

This is supposed to spawn just to the south of the R and D Center. Instead its spawning in the desert on a different continent.

When using lat/long coordinates, the spawn location works fine.

The above code is from:

https://github.com/inigmatus/GAP/blob/master/Wright-Barnstorm.cfg

craft is:
https://github.com/inigmatus/GAP/blob/master/Assets/Land/Tool%20Shed.craft

This also currently breaks the Nightingale's Cay contract at the moment.

**Comment by jrossignol** [comment]
Can you confirm for absolute certain that this is only an issue on the dev version?  I ask because SpawnVessel hasn't been touched since 2015-12-08, and I can't think of anything else that would affect this.

**Comment by inigmatus** [comment]
testing... i replicated it with 1.9.3.1. im running some mods. pairing it down to vanilla..

**Comment by inigmatus** [comment]
wow. it's replicated in CC 1.9.3.1 and GAP 1.0.2.1 - i dont think anyone reported it, and i am a bit bewildered how it escaped my testing for GAP 1.0... unless it cropped up in CC 1.9.3. weird. anyways, yes, any SpawnVessel with PQS values are spawning on different side of Kerbin. vanilla.

**Comment by jrossignol** [comment]
Still seems odd as I haven't touched that stuff in some time - I'll try to reproduce this one as soon as I can tomorrow.

**Comment by jrossignol** [comment]
The problem was that the position is calculated at contract load time (on the main menu), and it looks like KSP is giving invalid positional data at that point.  Fixed it.  Two possibilities for how this snuck by:

 1. It never worked, except when you do a reload contracts (which I bet you do a lot when you're in development).
 1. 1.0.5 broke it - it's possible that KSP used to give the right positional data on the main menu.

Regardless, fixed for 1.9.4

**Comment by inigmatus** [comment]
confirmed fixed. thanks!
