### ISSUE TITLE
Massive frequent lag - climate & geological contract generation

### ISSUE THREAD

**Issue by Y3mo** [jrossignol/ContractConfigurator#458]
Hey,

the extremely frequent generation of contracts for this pack induces massive lag (cursor not moveable).
For example mission control is hardly useable since this closes displayed contracts when picking new ones, every time it generates a new contract. Just leaving it idle in MissionControl/R&D for a few minutes will generate dozens of entries in the log about climate and geological contracts being generated, often generating the same type 3 times in a row.

[Log]: [INFO] ContractConfigurator.ConfiguredContract: Generated contract: CONTRACT_TYPE [FS_GeologicalStudy]
[Log]: [INFO] ContractConfigurator.ConfiguredContract: Generated contract: CONTRACT_TYPE [FS_ClimateStudy]

Had to remove the pack for the time being to keep keep the game playable.

**Comment by Y3mo** [comment]
Whoops, I just realised that I misclicked, that bug reported was intended for the FieldResearch contract pack. Sorry about that.

But possibly CC itself could implement a failsafe mechanism to prevent too frequent contract generation?

**Comment by jrossignol** [comment]
Could you post a save file for me?

**Comment by Y3mo** [comment]
Will try to post a save file tomorrow.
I have further isolated the problem though:
When I have a CKAN install with
Community Tech Tree (dependecy of SETIctt),
Contract Configurator,
Contract Pack: Field Research,
KSP-AVC (dependeny of SETIctt),
Module Manager,
SETI-CommunityTechTree

and start a new career game, then it continuously spams the log with 
[Log]: [INFO] ContractConfigurator.ConfiguredContract: Generated contract: CONTRACT_TYPE [FS_ClimateStudy]

It does not do so with the stock tech tree.
The main difference is, that thermometer and barometer are available at the start in the SETIctt.

With my previous report above, I had more tech unlocked, among them the Accelerometer, and it also spammed the geological study.

I then tried with the stock tech tree and cheat unlocked the thermometer and barometer. While it did not spam right away, as soon as I went back to main menu and then resumed the save, it started spamming climate study contracts in the log as well.

Hope that helps for the moment.

**Comment by jrossignol** [comment]
That should be sufficient info, no save needed.

**Comment by jrossignol** [comment]
I haven't been able to reproduce this one, are you able to try it again on 1.9.4 and provide a log + save?

**Comment by jrossignol** [comment]
Finally figured this one out, one type of requirement (ExpressionRequirement) was getting bleedthrough from one generation to the next (which would incorrectly mark an offered contract as invalid, and cause another contract generation cycle).

Fixed for 1.9.5.
