### ISSUE TITLE
Inability to deactivate World First Milestones

### ISSUE THREAD

**Issue by Y3mo** [jrossignol/ContractConfigurator#459]
Hey,
I seem to be unable to deactivate those World First Milestones, however I m sure it worked before (though I do not remember in which version it worked last).

Neither through the old method:

CONTRACT_CONFIGURATOR
{
	disabledContractType = RecordTrackContract
	disabledContractType = ExploreBody
	disabledContractType = WorldFirstContract
}

nor using the new? method:

CONTRACT_GROUP
{
    name = SETIcontracts
    displayName = SETI Contracts

    minVersion = 1.7.3
	
	disabledContractType = RecordTrackContract
	disabledContractType = ExploreBody
	disabledContractType = WorldFirstContract
}

Have not checked for the explore body contracts so far.

**Comment by jrossignol** [comment]
No support for disabling them in 1.0.5 as they are no longer contracts. It
may still be possible via configuration, but it's not something I've looked
at. I'll take a peek tonight and (at a minimum) report back here.

**Comment by Y3mo** [comment]
Thank you!
For the time being I'll minimize the rewards from those as Svm420 suggested.

**Comment by jrossignol** [comment]
Np, you should also be able to zero then out via that method.
