### ISSUE TITLE
CollectScience recoveryMethod = Transmit - not completing when relayed through RemoteTech network

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#461]
from: https://github.com/inigmatus/GAP/issues/161

User reported the following does not complete when RemoteTech is installed and science is relayed through a comsat. I have not tested to confirm yet:

//Collect Science	
	PARAMETER
	{
		name = CollectScience
		type = CollectScience
		title = and then transmit barometric science from one of your buoys
		
		targetBody = Kerbin
		situation = SrfSplashed
		
		experiment = barometerScan
		recoveryMethod = Transmit
		
		completeInSequence = true
		hideChildren = true
		
	}

**Comment by jrossignol** [comment]
Nope, remotetech bug.  Details to be posted in thread.
