### ISSUE TITLE
Contracts with Spawned Kerbals in Command Seats as part of craft definition, fail to complete later VPG waypoint checks.

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#462]
From: https://github.com/inigmatus/GAP/issues/163

With TakeCommand and HyperEdit (to save time) installed, Command Seat only tourbuses are not able to complete any VPG waypoint where the VPG has a vessel attribute:  The first waypoint completes since it's in a VPG with a define attribute, but the remaining waypoints don't complete:

https://github.com/inigmatus/GAP/blob/master/Development/BugTest%23462

Steps:
1. using a craft with 7 m1 command pods (1 driver, 6 passengers), and 6 command seats (to fulfill contract reqs for six command seats).
2. hyperedit move the vessel to the astronaut complex - the waypoint completes fine (VPG define).
3. manually load the five of the six kerbals into the pods.
4. load the sixth kerbal in a command seat.
5. hyperedit move the vessel to the Space Center waypoint - the waypoint fails to complete (VPG vessel). F10 shows vessel is loaded and recognized for the parameter.
6. exit your command seat kerbal out of the seat, and board the remaining open pod - immediately the waypoint completes.

When I remove the VPG vessel param, the waypoint completes without issue. This appears to be an issue with VPG vessel parameters not working with a Kerbal in a command seat.

**Comment by inigmatus** [comment]
I tested KSP-IslandSurvey.cfg in GAP using a Command Seat only aircraft. Flew and passed all waypoints.

This issue appears to only be isolated to KSP-TourBus.cfg. The difference with KSP-TourBus.cfg is that the loaded passengers define the VPG vessel which is later called by the VPG vessel parameter on the Space Center waypoint.

I can't seem to narrow this down.

**Comment by inigmatus** [comment]
I think I'm narrowing this down. This appear to only affect craft that have loaded SpawnPassengers into Command Seats, as part of a craft's definition check. Then when craft vessel is called up to pass a VPG waypoint, it is unable to do so.

**Comment by jrossignol** [comment]
I don't get it:

![image](https://cloud.githubusercontent.com/assets/8717685/12689127/fd610d8a-c697-11e5-8bed-1376b0d3739f.png)

Note that I didn't hyperedit, I drove (wouldn't expect a significant difference though).

**Comment by inigmatus** [comment]
are you using the test contract https://github.com/inigmatus/GAP/blob/master/Development/BugTest%23462 ?

i updated GAP 1.1.1 to remove the VPG from the Space Center waypoint parameter so if you're testing the GAP 1.1.1 TourBus contract directly, it's a false negative.

**Comment by inigmatus** [comment]
btw, aw, that bus is so cute!

**Comment by jrossignol** [comment]
Yup, with the test contract (I should've changed the title to make it obvious, had to double check the save to be certain).

Hehe, was going for a minimum viable (drivable) car.

**Comment by inigmatus** [comment]
In my test, I used CC, GAP, TakeCommand and a few other mods. Do you have TakeCommand on your install?

if so, I'll retest it tonight and reduce my mods to just those three and report back.

**Comment by jrossignol** [comment]
Yup, this was with TakeCommand.  I know the completeInSequence can cause problems sometimes, but I fixed quite a few of those in 1.9.4 (but there might be a lingering case).  Maybe it was the fact that I didn't hyperedit - but for the waypoint checks it shouldn't really matter.  Or it's something to do with vessel construction.

If you can reproduce, toss up a save, and I'll see if I can figure out what makes it unique.

**Comment by inigmatus** [comment]
Reproduced consistently: http://www.mediafire.com/download/sylehy6oqlllmi4/bug462.sfs

**Comment by jrossignol** [comment]
Loaded that save, mission control one was already checked off (it may have checked off immediately on load).  Drove to the tracking station and that worked too.  Can you provide more issues on what needs to be done in that save to reproduce?

**Comment by inigmatus** [comment]
Oh that's just weird. When you load from a save, the waypoint completes, but when you launch from new contract and pick up the passengers and then drive to any waypoint, none of the waypoints complete... until I quicksave and load the quicksave.  So saving a quicksave won't work to test this, as it allows the waypoints to complete. I just tested this with just TakeCommand, CC, and GAP.

so... to duplicate you will need to accept a new contract: https://github.com/inigmatus/GAP/blob/master/Development/BugTest%23462

and then launch a vessel and drive the mission.  I think you could not duplicate it because your test craft had a pod. Use this craft file instead (command seats only): http://www.mediafire.com/download/xmd0jhh75nik2cf/TourBus.craft

**Comment by jrossignol** [comment]
Nope, tried this all kinds of ways, and it just works for me every time.  Using a new save, your contract and craft I:
 1. Accepted the contract
 1. Launched the bus
 1. Picked up the passengers at the first waypoint
 1. Drove to the second waypoint.  Watched it get checked off.

I just don't know what's different.  Can you:
 1. Turn on Verbose logging for VesselParameterGroup
 1. Turn on Verbose logging for VisitWaypoint
 1. Remove the hideChildren attributes in your contract
 1. Show me a screenshot of the contract in the bad state (after doing the above)
 1. Send a KSP.log

Sorry if that's a bit onerous, but I just can't seem to figure out how to reproduce this one, and nothing is jumping out that would cause this type of issue in the code.

**Comment by inigmatus** [comment]
thanks for checking. ill keep hunting this down. ill do the above and a vanilla game rather than my test environment.

**Comment by inigmatus** [comment]
I hope to test this tonight.

**Comment by jrossignol** [comment]
Okay, I think I'm finally getting a handle on this...  too many contracts all with the same title - I don't believe I was ever testing with one that showed the bug until now.  Seems like the vessel association isn't getting done.

**Comment by jrossignol** [comment]
Okay, fixed for 1.9.5.  Note the source only commit though - I've got a bunch of other stuff on the go, and rather than stashing them I've just got it all mixed together.  Once I get that all sorted out, 1.9.5 should be going out the door, so stay tuned.

**Comment by inigmatus** [comment]
confirmed fixed. thanks.
