### ISSUE TITLE
SpawnPassenger/Kerbals Not Removed from Command Seats on Contract Cancel of Failure (leads to erasure of entire craft from game and missing crews)

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#463]
Rather serious. Can be avoided by the player, so not critical, but certainly serious.

Steps to duplicate:

Mods: CC, GAP, TakeCommand

1. Accept contract https://github.com/inigmatus/GAP/blob/master/CoastGuard-RescueFishermen.cfg

2. Launch craft with at least one Command Seat.

3. Load SpawnPassenger Lt. Dan Kerman into Command Seat.

4. Exit to Space Center without recovering.

5. Cancel the contract.

6. From Space Center, fly your craft again. (which does not list SpawnPassenger Kerbal but only your own pilot)

7. See Ghosted Kerbal in seat on craft load. (I have Cetera's Suit pack installed revealing the ghosted Kerbal here with a purple visor)
http://i.imgur.com/Rbq68dX.png

8. Exit to Space Center, get error (referring to the unknown spawned Kerbal ghost no less):
http://i.imgur.com/qcQRSJ7.png

9. Craft is goners along with pilot per KSP's policy to remove such partless crafts from persistence:
http://i.imgur.com/Mm9HkHq.png

I think this is because CC is not coded to properly clean up/remove Kerbals on contract failure/cancel from Command Seats.

**Comment by jrossignol** [comment]
Fixed for 1.9.5

**Comment by inigmatus** [comment]
confirmed fixed. whew, that was a nasty one. thank you!

**Comment by inigmatus** [comment]
confirmed fixed when only one passenger is in the seat, but still bugged when more than one passenger.

Test this six passenger savefile from the 462 issue: http://www.mediafire.com/download/sylehy6oqlllmi4/bug462.sfs

1. load save
2. exit to Space Center
3. cancel contract
4. load tourbus
5. see 3 out of 6 passenger kerbal seats with ghosted Kerbals
6. exit to Space Center
7. get same error documented above: http://i.imgur.com/qcQRSJ7.png
8. craft is goners along with driver

**Comment by inigmatus** [comment]
and not to add more pain to the above, but I think is related:

With same the save file, if you recover the vessel before contract cancellation, and then go to cancel the contract, the passengers are not removed from Mission Control and remain persistent.  This was not happening before the 1.9.5 dev.

**Comment by jrossignol** [comment]
If they are staying behind in mission control, it probably means an exception is stopping stuff early - best to check the logs for stuff like that.  I'll retest in an hour or two regardless.

**Comment by jrossignol** [comment]
Ahhhh, such a stupid mistake.  It was leaving the females behind. :woman: 

Basically, they have a different part - kerbalEVAfemale, and I was only checking for kerbalEVA.

**Comment by inigmatus** [comment]
haha.
