### ISSUE TITLE
Enhancement: Add a Copy Craft File: EditorFacility attribute: Subassembly

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#465]
Would like the ability for copied crafts to be copied to the subassembly.

Use case: I have a number of contracts that require players to load pre-designed crafts such as buoys and specific cargoes, which the contract gives to them to load. Currently they show up in the SPH, but to avoid cluttering a player's SPH folder I would like the option to have it save to the Subassembly (Subassemblies?) folder.

**Comment by jrossignol** [comment]
Added SubAssembly as a valid value for CopyCraftFile.craftType.

**Comment by inigmatus** [comment]
Your wiki is incorrect. It's SubAssembly not Subassembly.  Subassembly fails, but SubAssembly passes. Tested. Please fix wiki or make case insensitive.
