### ISSUE TITLE
Add KerbalAlive parameter

### ISSUE THREAD

**Issue by Keniamin** [jrossignol/ContractConfigurator#470]
Hello! Now KerbalDeaths parameter tracks only count of deaths. It would be great to have KerbalAlive parameter to track (if it is possible) specified kerbal and fail contract in case of his death (while deaths of other kerbals are still allowed).

**Comment by jrossignol** [comment]
Not exactly what you're looking for, but probably works for many cases where you need this - if you have the RecoverKerbal parameter, it will fail the contract if the Kerbal in question dies (as obviously, they can't be recovered any more).  Let me know if that is sufficient for your use case.

**Comment by Keniamin** [comment]
Interesting variant, though I don't think I really want to require recovering. I tried to hack it using RecoverKerbal with "hidden" or "optional" flag (thinking this will make parameter not required, but still provide a check). But, unfortunately, this does not work. In both cases recovering is really required (by the way, it's strange in case then "optional = true" is set; I rather expected no check in this case).

So may be good workaround but, if it is not very difficult, I would be very grateful if you add described parameter.

**Comment by Keniamin** [comment]
Ok, finally I've hacked it :) I added All parameter for RecoverKerbal with ITERATOR, made RecoverKerbal hidden and All optional. This works (provides check but not requires recovering), the only problem is the "(Optional)" prefix in parameter's title. I see fakeOptional parameter in the code, may be you can just permit to set it via config.

But while experimenting I've noticed that recover with RecoverKerbal really recovering not whole vessel, but only passengers. Is it really so? Is this behavior introduced by Contract Configurator (or it is interference with some other mod I have)? If so RecoverKerbal is acceptable for me, but really, it is absolutely not clear from the documentation...

By the way, I'm trying to understand when "Load passengers" dialog appears? Only when launching new vessel (and have contract with passengers, of course)? Or at the selecting of any landed on Kerbin vessel too?

**Comment by jrossignol** [comment]
If a parameter is hidden, the title should be blank and the "(Optional)" prefix shouldn't appear.  Alternatively, if a `title` attribute is provided, the "(Optional)" text will not be used.

RecoverKerbal indeed only cares about whether a specific Kerbal is recovered, from the doco:
> The RecoverKerbal parameter is met when the named Kerbal is "recovered" (ie. goes back in to the available list at the astronaut complex).

Checking for recovery of an entire vessel is provided by RecoverVessel.

The passenger loader dialog only appears on the launchpad.  It would be possible to make changes to have it show up when loading other vessels that are landed on Kerbin, but I would want it to be something that the contract specifies (ie. via a vessel attribute or something like that), versus being global.

**Comment by Keniamin** [comment]
> Alternatively, if a title attribute is provided, the "(Optional)" text will not be used.

Really? I see another behavior. For now I have a structure like this:
```
PARAMETER
{
    name = Safely
    type = All
    title = Flight must be safe (avoid killing passengers)
    optional = true
    PARAMETER
    {
        name = RecoverKerbal
        type = RecoverKerbal
        hideChildren = true
        hidden = true
        ITERATOR
        {
            type = Kerbal
            kerbal = @/passengers
        }
    }
}
```
"All" group is optional (but not hidden), all it's children are hidden. And in the game I see description "(Optional) Flight must be safe (avoid killing passengers)".

> RecoverKerbal indeed only cares about whether a specific Kerbal is recovered, from the doco

No, I mean another thing. Suppose I've loaded kerbals to the vessel, completed all other contract parameters and then pressed "Recover". Then I see KSC screen with message "Contract completed", but not "Vessel recovered" dialog. And indeed, my vessel is still at the location there it was then I pressed the button. I can then press "Fly" in tracking station and do something else with vessel (though there is no more passengers aboard, of course – they are recovered). In stock KSP, as I remember, "Recover" always recovering whole vessel, regardless of having contracts about it's passengers.

> It would be possible to make changes to have it show up when loading other vessels that are landed on Kerbin

No, I think current behavior is ok. It was just a question. I'm interesting on how it works and trying to understand the code :) And from code I supposed, that it must be for any vessel, so decided to clarify this point.

**Comment by jrossignol** [comment]
Typically that type of recovery issue indicates that an exception occurred,
which could be due to a Contract Configurator bug. Toss me a KSP.log fine
and I'll take a look.

**Comment by Keniamin** [comment]
Ok, I have reproduced the bug on clear KSP install: only Contract Configurator and Waypoint Manager mods. Attaches is the log and the configuration of contract. Interestingly, when I removed "optional = true" from RecoverKerbal node, bug disappeared.

And also I want to mention here another strange thing about SpawnKerbal. Look at the SpawnKerbal behavior. As you can see, kerbals spawned in 8.5 meters above the surface of terrain. But actually they are staying on the surface of terrain, what in this case means "under the surface of airfield" (see screenshot). And in the log you can see some warnings around their spawning (`Crewmember Aldie Kerman found inside a part but status is set as missing. Vessel must have failed to save earlier. Restoring assigned status.`). I am not sure they are related to this effect, but they exists.

Interestingly, when between kerbal spawn and the surface of terrain there are more then one another surfaces, kerbal hits some of them but sometimes not all of them. (Checked by spawning kerbal on the Island, above the hangar. He appeared on the surface of airfield. So he is ignored the roof of hangar, but not ignored the airfield, i.e. not falled down to the terrain.) It is rather a bug in KSP, not Contract Configurator, but it would be great if you can do something with it.

And, anyway, if this is just a bug I'm still requesting either KerbalAlive parameter or ability to remove "(Optional)" prefix from optional parameter (to use my trick with "non-required recovering"). I'm doing my best to allow player to reuse the vessel he used to complete the contract for other purposes, so don't want to introduce required RecoverKerbal.

[KSP_bug.txt](https://github.com/jrossignol/ContractConfigurator/files/120976/KSP_bug.txt)
[BugContract.txt](https://github.com/jrossignol/ContractConfigurator/files/120975/BugContract.txt)
[BugScreenshot.png](https://cloud.githubusercontent.com/assets/10873738/12875889/fe22df22-ce04-11e5-910a-97e216b0c876.png)

**Comment by jrossignol** [comment]
It's the same stock issue as in #410 and #443:
```
[EXC 01:04:57.931] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[EventData`1+[ProtoVessel]].get_Item (Int32 index)
	EventData`1[ProtoVessel].Fire (.ProtoVessel data)
	VesselRetrieval.recoverVessel (.Vessel v)
	VesselRetrieval.recoverVessels ()
	VesselRetrieval+.MoveNext ()
```

That one's driving me nuts, but not much can be done aside from waiting to see if it's fixed in 1.1.

I'll take a look at the rest of the stuff.

**Comment by jrossignol** [comment]
> And also I want to mention here another strange thing about SpawnKerbal. Look at the SpawnKerbal behavior. As you can see, kerbals spawned in 8.5 meters above the surface of terrain. But actually they are staying on the surface of terrain, what in this case means "under the surface of airfield" (see screenshot). And in the log you can see some warnings around their spawning (Crewmember Aldie Kerman found inside a part but status is set as missing. Vessel must have failed to save earlier. Restoring assigned status.). I am not sure they are related to this effect, but they exists.

This is problem with how the buildings in KSP are done.  They have a big raised area above the ground (which is why you always have to take a ramp up to the building's surrounding).  So what you would expect to be the ground is actually about 2-3m above ground.  It's a situation where you just need to manually set the height above ground, unfortunately.  You can see me handling it [here](https://github.com/jrossignol/ContractPack-Tourism/blob/master/GameData/ContractPacks/Tourism/InvestorTour.cfg#L309-L316) by manually setting the altitude.

**Comment by jrossignol** [comment]
The Optional stuff is working as expected:
![image](https://cloud.githubusercontent.com/assets/8717685/12878664/f89a29a8-cde5-11e5-8f37-cdb004ff2ac5.png)

I'm guessing that you had an old version of the contract "stuck" in the pre-loader from before you changed.  Also, keep in mind that if you update a contract, active contracts will *not* reflect that update.

**Comment by jrossignol** [comment]
Done for 1.9.6.  Implemented as a new kerbal attribute on the existing KerbalDeaths parameter.

Also note that you can always grab the latest dev dll from [here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll) (click on the View Raw link to download).

**Comment by Keniamin** [comment]
First of all – great! Thank you very much for your responsiveness.

> That one's driving me nuts, but not much can be done aside from waiting to see if it's fixed in 1.1.

Okay... Well, will see.

> I'm guessing that you had an old version of the contract "stuck" in the pre-loader from before you changed. Also, keep in mind that if you update a contract, active contracts will not reflect that update.

Yes, I know about these features. That's why I'm always refreshing config using "Alt+F10 -> Reload contracts", then "Alt+F12 -> Contracts -> Tools -> Clear current contracts", and finally re-accepting the contract. And this particular issue I moreover checked in a new, clean save-game specially created for this purpose.
![screenshot0](https://cloud.githubusercontent.com/assets/10873738/12900432/61d5bb4e-cec7-11e5-8a52-c6385d6b18e0.png)
After all, in the code we can see
```
return (optional && !fakeOptional && !string.IsNullOrEmpty(title) ? "(Optional) " : "") + GetParameterTitle();
```
In my case optional = true, fakeOptional = false and title is not empty, thus condition is evaluated to true. So may be, vice versa, _you_ have some changes in your version, that have not been committed yet? ;)

> It's a situation where you just need to manually set the height above ground, unfortunately. You can see me handling it here by manually setting the altitude.

Oh! I think I've understood where the problem is. Note that I have altitude in my config:
```
BEHAVIOUR
{
    name = WaypointGenerator
    type = WaypointGenerator
    <...>
    RANDOM_WAYPOINT_NEAR
    {
        hidden = true
        nearIndex = 2
        // ---> Here it is:
        altitude = 8.51513423778
        count = 2
        minDistance = 1
        maxDistance = 2
    }
}
BEHAVIOUR
{
    name = SpawnPassengers
    type = SpawnKerbal
    KERBAL
    {
        kerbal = @/passengers.ElementAt(0)
        owned = false
        addToRoster = false
        lat = @/WaypointGenerator.Waypoints().ElementAt(3).Latitude()
        lon = @/WaypointGenerator.Waypoints().ElementAt(3).Longitude()
        // ---> And here is the "link":
        alt = @/WaypointGenerator.Waypoints().ElementAt(3).Altitude()
    }
    <...>
}
```
But, apparently, "altitude" for a WAYPOINT is above the terrain surface, while "alt" for a KERBAL is real altitude as it is shown at the vessel's gauge (i.e. from the sea level). Am I right? With this correction it seems to work, but I can't find any mentions about this difference in documentation to prove or refute my point.

**Comment by jrossignol** [comment]
> In my case optional = true, fakeOptional = false and title is not empty, thus condition is evaluated to true. So may be, vice versa, you have some changes in your version, that have not been committed yet? ;)

I have no idea why I seemed to get the right result (obviously I did something wrong) - the code you linked is clearly wrong.  Rather than worrying about it further, I've fixed the code.

> But, apparently, "altitude" for a WAYPOINT is above the terrain surface, while "alt" for a KERBAL is real altitude as it is shown at the vessel's gauge (i.e. from the sea level). Am I right? With this correction it seems to work, but I can't find any mentions about this difference in documentation to prove or refute my point.

Yep, that sounds about right.  FinePrint used a different convention when I was adding support for that stuff, and it's too late to easily change stuff without breaking lots of contract packs.  I'll update the documentation everywhere there is alt/altitude to try to make it more clear.

**Comment by Keniamin** [comment]
> I have no idea why I seemed to get the right result

Wait, you tested this point using BugContract config from my attach? If so, then the result is absolutely clean, because _there is no_ "optional = true" in the group parameter, only in it's children :)
```
PARAMETER
{
    name = Safely
    type = All
    title = Flight must be safe (avoid killing passengers)
    // --> Not optional.
    PARAMETER
    {
        name = RecoverKerbal
        type = RecoverKerbal
        hideChildren = true
        hidden = true
        // --> Optional is only here.
        optional = true
        ITERATOR
        {
            type = Kerbal
            kerbal = @/passengers
        }
    }
}
```

> it's too late to easily change stuff without breaking lots of contract packs

Of course. I don't think this is a big problem, considering that the parameters have different names. The same name in another meaning depending on context really is not good, but different names are ok. Clear documentation must be enough to understand that alt != altitude.

So, I just have to add terrain altitude everywhere in KERBAL nodes to make it works. Great!
Thank you again, your advices were very helpful.

**Comment by Keniamin** [comment]
Hmm... Something went wrong. Look at the "simplest contract ever" that I've attached.
Test 1: accept contract, launch a vessel with a kerbal, destroy it within 30 seconds. Contract fails, as expected.
Test 2: accept contract, launch a vessel and just wait a bit. Duration parameter becames done, but the KerbalDeath does not. As if it is still waiting for some actions. So the contract itself is not considered as completed.

It looks like after changes the KerbalDeath parameter becames "uncompletable".

**Comment by jrossignol** [comment]
Whoops, that was a silly mistake.  Fixed now.
