### ISSUE TITLE
HasCrewCapacity not working for probes

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#473]
``PARAMETER``
``{``
``name = HasCrewCapacity``
``type = HasCrewCapacity``
``maxCapacity = 0``
``}``

This will not check the "Crew Capacity: None" parameter when using a probe (specifically tested with a Stayputnik but I assume the others would be the same).

**Comment by jrossignol** [comment]
Partially a documentation issue (the default minCrewCapacity value was documented wrong), but added handling for case when min > max
