### ISSUE TITLE
Disable multiple Orbit Specifics notes in ReachSpecificOrbit

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#474]
Carried over from the forum - when using Iterators the "Orbit Specifics" notes get repeated for every vessel in the contract, which is not ideal. Screenshot of what I mean: http://imgur.com/GcgvPYO

Ideally, I'd like this to only flag up only once, but I can live with being able to disable it completely - I'll just put a note in my contract to check the tracking station instead.

**Comment by jrossignol** [comment]
Added ReachSpecificOrbit.displayNotes (default = true).  If you want to display the notes only once, you'll have to set this to true only for the first one (maybe based on an expression.
