### ISSUE TITLE
Enhancement Request: Orbit().LAN()

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#475]
One of my contracts requires syncing two (relatively) close satellites orbits. 

I can basically get what I need from OrbitApoapsis, OrbitPeriapsis() and OrbitInclination(), but without having the Longitude of Ascending Node available, the contracts are returning sats who's orbits don't seem to be very similar (although if you look at raw figures, they are, they just look wrong because the LAN is so far off).

**Comment by jrossignol** [comment]
Done for 1.9.6.

The method you'll want is Vessel.Orbit().LAN()
