### ISSUE TITLE
KerbalDeaths read Kerbal list from vessel

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#478]
Have the KerbalDeaths able to read the list of Kerbals that can't be killed from a VesselIdentifier.  Update it dynamically as the vessel association changes, but do not remove Kerbals from the list if they leave the vessel (supports checks for Kerbals that have wandered off on EVA and met their demise).

**Comment by inigmatus** [comment]
perfect.

**Comment by jrossignol** [comment]
Done for 1.9.7
