### ISSUE TITLE
VesselParameterGroup-defined vessels and REQUIREMENTs

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#481]
One way to ensure that a send-up-new-station contract doesn't trigger unless there are no stations in orbit is to check vessels of that display type. That's how it's done in the stations contract pack. 

However, what I would prefer to do is to check the existence of a defined vessel from a vessel parameter group. If the station is deorbited, that define will go null and we'll know to send up another. Further, that will store what station(s) (plural if using a vessel list) we can send expansion/crew rotation/resupply missions to.

**Comment by severedsolo** [comment]
You should be able to do this using a expression requirement and a list. I used to do this in the early days of Bases and Stations.

```   
 DATA
    {
        type = Vessel
        requiredValue = false
        targetVessel = [ LKOStationNEW ].Random()
    }
    REQUIREMENT
    {
        name = NoStation
        type = Expression

        expression = (!@/targetVessel.IsOrbiting())
    }
```

More examples here: https://github.com/severedsolo/KerbinSpaceStation/releases/tag/2.1

**Comment by NathanKell** [comment]
@severedsolo Ah, so you switched away from that to what you do now. May I inquire why? Seems the current method is much more prone to edge cases, although it does catch stations the player launches herself.

**Comment by severedsolo** [comment]
Three main reasons :

1) as you said, it picks up players stations that weren't launched as part of the pack.

2) this may have changed now, but CC was never very good at guessing which vessel is the root vessel when you dock/undock (I understand this is a stock problem though) This resulted in the definition getting lost sometimes on docking extra modules, and the player farming free money when the contract got reoffered. I could have offered a no value contract to redefine but I dislike this, as essentially you are holding up a sign which says "yeah this doesn't work very well" 

3) this was before definition lists were a thing,  so each vessel definition needed its own contract. It was just less work to have everything under one contract.

**Comment by jrossignol** [comment]
@NathanKell, can this one be closed?  My IRC logs don't go back that far (need to change those settings), but I thought we'd worked out the necessary expressions to get this the way you wanted it.  If not, let me know and I'll keep this open.

**Comment by NathanKell** [comment]
Yep!
