### ISSUE TITLE
One more for you: Reach state at any body

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#483]
As I mentioned I'm adding crew count records and crew in-space duration records. And as we discussed to catch all states I'm using an All of an Any of the three possible states (ESCAPING, ORBITING, SUB_ORBITAL). The problem is that--and I forgot this--ReachState requires a targetBody.

In fact, I can't seem to find any way to do this--the parameters that take situation require a body, and there isn't an expression for parameters (AFAIK).

Halp? (again :D )

**Comment by NathanKell** [comment]
Example:
`	PARAMETER
	{
		name = crewCountInSpace
		type = All
		title = Have @/crewedTargetCount on the same vessel.
		
		PARAMETER
		{
			name = InSpace
			type = Any
			title = Be in Space
			hideChildren = true
			
			PARAMETER
			{
				name = ReachState
				type = ReachState
				situation = ORBITING
			}
			PARAMETER
			{
				name = ReachState
				type = ReachState
				situation = SUB_ORBITAL
			}
			PARAMETER
			{
				name = ReachState
				type = ReachState
				situation = ESCAPING
			}
		}
		PARAMETER
		{
			name = HasCrew
			type = HasCrew
			minCrew = @/crewedTargetCount
		}
	}`

**Comment by NathanKell** [comment]
Bah, it keeps messing the formatting. Ah well.

**Comment by jrossignol** [comment]
This is a design decision that from one of the first releases that I want to change but can't due to backwards compatibility - right now it'll default to body on ReachState to the targetBody of the contract, which gives no way to set it to none/any.  I'm trying to decide the best way to add this functionality.  Two choices are:

1. Allow multiple Celestial Bodies.  Then you can just go targetBody = AllBodies() and it'll work the way you want.  Leaning towards this, as it could be useful for other purposes
1. Have a separate bool parameter hasTargetBody that can be turned off.  Kind of a hack, so think I'll go the other route.

A couple other things.  Right now, multiple situations as allowed (I forgot about this when we were chatting).  So what you have above can be greatly simplified to:
```
PARAMETER
{
    name = crewCountInSpace
    type = All
    title = Have @/crewedTargetCount on the same vessel.

    PARAMETER
    {
        name = ReachState
        type = ReachState
        situation = ORBITING
        situation = SUB_ORBITAL
        situation = ESCAPING
    }

    PARAMETER
    {
        name = HasCrew
        type = HasCrew
        minCrew = @/crewedTargetCount
    }
}
```

The other thing to be aware of is new functionality since the last time you were doing heavy RP-0 contract work - [Iterators](https://github.com/jrossignol/ContractConfigurator/wiki/Iterators).  You could hypothetically use that to get the "any planet" logic.

```
PARAMETER
{
    name = crewCountInSpace
    type = All
    title = Have @/crewedTargetCount on the same vessel.

    PARAMETER
    {
        name = InSpace
        type = Any
        title = Be in Space
        hideChildren = true

        PARAMETER
        {
            name = ReachState
            type = ReachState
            situation = ORBITING
            situation = SUB_ORBITAL
            situation = ESCAPING

            ITERATOR
            {
                type = CelestialBody
                targetBody = AllBodies()
            }
        }
    }

    PARAMETER
    {
        name = HasCrew
        type = HasCrew
        minCrew = @/crewedTargetCount
    }
}
```

This is simple from a config point of view, but need to keep in mind that this is copying the parameter for each Celestial Body - which means you'd have 10-15 (or however many) ReachState parameters, each subscribing to events, doing OnUpdate checks, etc.  I don't think it would be *severe*, but given they are milestone contracts that are always on, I'd prefer one of the solutions above.  Give me a day or two and I should be able to make the change.

(Also, three backticks on a single line to start/end a block of preformatted text) :wink:

**Comment by NathanKell** [comment]
Yep, a list of bodies is great, and rather more flexible. For now I'll use the (wow that's cool) iterator thing, that will make things rather simpler there and elsewhere. As always, many thanks!

And...github suggested merely a leading backtick and trailing backtick, which didn't work so well. :D

A semi-related question, since it still applied to count/duration records. I converted the floats to ints but CC threw on trying to do that, so I switched back to floats for index and crew count, and (since it also couldn't cast float -> duration, unless there's an explicit cast operator now?) two lists, one of Duration and one of float (since I need both the duration and the duration-as-integer-days, the latter for use multiplying rewards). Am I missing something here?

Thanks as always! :)

**Comment by NathanKell** [comment]
(I mention because I thought I recalled the reason for using floats was fixed)

**Comment by jrossignol** [comment]
What was the exception?  Maybe the cast doesn't work (if so I will fix).  You can also do stuff like "30d" to have it read directly as a Duration - which if you cast to int will give you number of seconds.  If you want number of days, then it's pretty easy for to to write methods to the Duration class to get the years/days/h/m/s components out as ints (or perhaps fractionally as float, but that might be less useful).

(Single `back ticks` if used inline in a paragraph - triple for a block).

**Comment by NathanKell** [comment]
Ah, right, re: the formatting.

I'll look into that when I have a sec--I probably just didn't handle the conversion right. In testing, I ran into another wrinkle, actually--and I'm not sure it's easily fixable or worth fixing, but eh, here it is: unlike altitude and speed records, which are stateless, ideally duration records would keep in mind prior state. That is, if you stay in space for 7 days, you should get 1,2,3,7 as the records. However, due to how the duration parameter works and due to how the records contract is completed and then re-accepted when a record breaks, the timer resets after every record break. That means on a 7 day mission you will only break records 1, 2, and 3. It's not that big of a problem, but I wondered if you had any idea. Short of, say, having 15 (or however many record steps there are) duration record contracts all simultaneously active.

**Comment by jrossignol** [comment]
Yeah, that's kind of ugly.  I can't think of very many clean ways to fix it within Contract Configurator.  What I'd suggest isn't trivial, but in my opinion would be worthwhile.  What you need to do is completely decouple the record tracking from contracts.  Write your own ScenarioModule that does the actual tracking of how long someone is in space for (aside - it would be nice for this kind of thing if stock KSP had public ConfigNode members on classes like ProtoCrewMember that a modder could just add stuff to and have it saved/loaded automatically).  After that's done, create a [custom parameter](https://github.com/jrossignol/ContractConfigurator/wiki/Extending#extending-parameters) that just periodically checks for a Kerbal with the required in-space duration.

Next best idea is having 15 contracts (which is terrible).

**Comment by NathanKell** [comment]
Yeah, I actually was just thinking about that (stock KSP extensibility) approach today :D But it's rather late in the cycle to do that, I think, though I do have various other doo-dads in. That's the sort of record keeping one would want anyway (total time in space and concurrent time in space) for each kerbal.

**Comment by jrossignol** [comment]
Very cool.  Well for KSP 1.2, you should totally do something like this:
```
    interface ExtensiblePersistentObject
    {
        ConfigNode this[string s] { public get; }
    }
```
Which then just returns a reference to the ConfigNode (with data if it was already there, a new one if it wasn't).  No stepping on each others stuff, nice and simple.  Then go add it to *everything* that gets saved to the persistence file (ProgressNode stuff, I'm looking at you).

Anyway, regardless of the approach you decide on, I'll make the multi-targetBody change on ReachState, as I think that one could've come in useful a few times by now.

**Comment by NathanKell** [comment]
Sounds good! I'll chat with you on this when 1.2 starts. :)

**Comment by jrossignol** [comment]
Done for 1.9.7

**Comment by NathanKell** [comment]
Hurray! :)
