### ISSUE TITLE
Investigate waypoint offset issues

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#487]
Need to investigate possible waypoint offset issues.  The user doesn't appear to have Kopernicus (so it's not https://github.com/Kopernicus/Kopernicus/issues/109), but maybe it's possible they had it and then uninstalled?

From sardia [here](http://forum.kerbalspaceprogram.com/index.php?/topic/98666-105-contract-pack-anomaly-surveyor-v142-2015-09-14/&do=findComment&comment=2434868):
[KSP.log.txt](https://github.com/jrossignol/ContractConfigurator/files/152161/KSP.log.txt)

Will also want to consider creating a workaround for the Kopernicus issue (store the offset and then generate the actual coordinates when in flight/tracking station.

**Comment by sardia** [comment]
Just to clarify, I have never installed Kopernicus so that precludes that option.
~Sardia

**Comment by jrossignol** [comment]
Long time coming, but got a fix for this one.
