### ISSUE TITLE
Duration and crew count records firing instantly

### ISSUE THREAD

**Issue by NathanKell** [jrossignol/ContractConfigurator#488]
Sorry, yet another one of these.
The contracts:
Count: https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/Human%20Records/CrewedCountRecord.cfg
Duration: https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/Human%20Records/CrewedDurationRecord.cfg

I launch my [supersonic plane + mothership](http://i.imgur.com/EF7CmHz.png) and...the initial records for both complete. It's very odd.

**Comment by NathanKell** [comment]
A bit more on this: The duration record contract, ingame, claims that the ANY (be in space) is complete despite all its sub-checks showing Incomplete. The Duration parameter also shows complete.

Same story with crew count: the ANY shows complete despite its children all being incomplete.

**Comment by jrossignol** [comment]
Sounds like these are all issues with the contracts, but raised #489 for the documentation issue around disableOnStateChange.
