### ISSUE TITLE
Allow use of KSC latitude in contracts

### ISSUE THREAD

**Issue by jwvanderbeck** [jrossignol/ContractConfigurator#495]
Would be very handy to have the latitude of KSC available as a variable for use in contracts

**Comment by jrossignol** [comment]
What I'll do is expose the PQSCity elements of a CelestialBody and give it some methods.  Then you'll be able to do something like this:
```
HomeWorld().PQSCities().Where(pqs => pqs.Name() == "KSC").First().Location().Latitude()
```

**Comment by NathanKell** [comment]
Never a hammer when a toolbox will do, eh? :)

**Comment by jrossignol** [comment]
Haha, it's the Contract Configurator way.

**Comment by jrossignol** [comment]
One important thing to note is that regardless of the solution I use (assuming it's based off the PQSCity location), then you'll be subject to a pretty serious open issue in Kopernicus that may offset/shift the location by hundreds of meters:
https://github.com/Kopernicus/Kopernicus/issues/109

**Comment by jrossignol** [comment]
Done.  I also added a function to skip directly to KSC, so you can just do:
```
KSC().Location().Latitude()
```
Also note that if you look at the location in the debug window while on the main menu, it'll be wrong.  But it'll get recalculated whenever a contract gets generated, so aside from the above Kopernicus issue, you should always get the right value in contracts.
