### ISSUE TITLE
Vessel identifiers can become unassigned between generation and acceptance

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#496]
It's possible for a vessel identifier that was valid when a contract was generated to become unassigned by the time the contract is accepted.  Because of the way stuff in data nodes and requirements get checked, it's not currently possible to write a contract that will properly check stuff like this after generation.

My current thoughts on a solution would involve targeting this specific case, and adding a ValidVessel requirement that takes a vessel identifier, replacing the expression entirely.

Raised based on the [RP-0 Crew Rotation Contract](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/Human%20Spaceflight/Station%20Crew%20Rotation.cfg) and [this discussion](http://forum.kerbalspaceprogram.com/index.php?/topic/93045-105-realistic-progression-zero-rp-0-lightweight-realismoverhaul-career-v046-mar-12/&do=findComment&comment=2470056).

**Comment by jrossignol** [comment]
@inigmatus  and @severedsolo should probably also check this one out as it may come in useful for their contract packs.

**Comment by NathanKell** [comment]
ValidVessel seems a reasonable solution, yeah.

**Comment by severedsolo** [comment]
That would be very useful as long as I can still use expressions to check I've got a vessel that makes sense

**Comment by jrossignol** [comment]
Of course!

**Comment by inigmatus** [comment]
interesting.

**Comment by severedsolo** [comment]
This worries me:
``If at any point the vessel is no
    // longer valid, this will return false and fail the contract.``
When you say "fails" does that mean penalties get applied (even if it isn't the players fault) or will the contract just go away.

**Comment by jrossignol** [comment]
Penalties will get applied.

Long term I'd like to do a revamp to improve contract requirements to allow more flexibility (allow flags to specify whether checks are done for active contracts, whether failure penalties apply and messages in #464).  If you have specific stuff that you want (or specific details for the ones mentioned before), then raise an issue to track it.

**Comment by severedsolo** [comment]
Feel like this can be included in #464 I'll add my concerns to that one.
