### ISSUE TITLE
1.1 - noRandomContractMentality seems to be ignored.

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#499]
![alt text](http://i.imgur.com/8yT1gjX.jpg)

**Comment by jrossignol** [comment]
How consistent is this?  I've seen instances even in 1.0.5 where it still seemed to get assigned to a random contract.

**Comment by severedsolo** [comment]
Hmm, never mind. I regenerated contracts 10 times and it didn't re-occur. Must be one of those things, like you said. I'll re-open if needed.
