### ISSUE TITLE
seatExternalCmd not recognized in HasCrewCapacity parameter

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#505]
From: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-112-contract-configurator-v1113-2016-04-30/&do=findComment&comment=2551580

**Comment by jrossignol** [comment]
Response from the thread:

> Checked, and all Contract Configurator does here is tally up the part.CrewCapacity values.  For a stock command seat that will be zero (and as far as I can tell always has been).  If TakeCommand isn't setting that value when it adds itself then I'd take the issue over there.

I don't think that there's anything wrong with what Contract Configurator is doing here, this is just how stock KSP treats seats (and one of the things that TakeCommand changes/fixes).

**Comment by inigmatus** [comment]
What is HasCrewCapacity counting specifically from KSP that I need to bring back to TakeCommand to have Sean confirm it is making the seat available to CC for counting?

**Comment by jrossignol** [comment]
Part.CrewCapacity

**Comment by jrossignol** [comment]
Not sure if this is fixed in TakeCommand yet, but going to close out this issue.  Can re-open if it turns out there is something for CC to do.
