### ISSUE TITLE
Exception using Expression Behaviours

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#508]
From here: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-112-contract-configurator-v1115-2016-05-06/&do=findComment&comment=2568677

**Comment by jrossignol** [comment]
I'm not 100% confident that I fixed this (wasn't able to get the data setup to reproduce it fully.  Can you test the dev version and let me know?

**Comment by severedsolo** [comment]
Seems to be fixed. The second contract isn't generating, but that's probably a logic issue on my end.
