### ISSUE TITLE
Exception in ContractVesselTracker

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#509]
Raised by Lennartos on [the forum](http://forum.kerbalspaceprogram.com/index.php?/topic/91625-112-contract-configurator-v1115-2016-05-06/&do=findComment&comment=2569749):

```
[EXC 22:43:43.795] NullReferenceException: Object reference not set to an instance of an object
    ProtoVessel..ctor (.Vessel VesselRef)
    ContractConfigurator.ContractVesselTracker+<>c__DisplayClass17_1.<OnVesselDestroy>b__0 (.Vessel v)
    System.Collections.Generic.List`1[Vessel].GetIndex (Int32 startIndex, Int32 count, System.Predicate`1 match)
    System.Collections.Generic.List`1[Vessel].Find (System.Predicate`1 match)
    ContractConfigurator.ContractVesselTracker.OnVesselDestroy (.Vessel vessel)
    EventData`1[Vessel].Fire (.Vessel data)
    Vessel.OnDestroy ()
    UnityEngine.Object:DestroyImmediate(Object)
    Part:Couple(Part)
    ModuleDockingNode:DockToVessel(ModuleDockingNode)
    ModuleDockingNode:<SetupFSM>m__368()
    KerbalFSM:RunEvent(KFSMEvent)
    KerbalFSM:updateFSM(KFSMUpdateMode)
    KerbalFSM:UpdateFSM()
    ModuleDockingNode:Update()
```

**Comment by enceos** [comment]
Here's my report.
https://www.dropbox.com/s/5l95fgujkag1isa/output_log5.rar?dl=1
https://youtu.be/aru3VLVK2XM

**Comment by Galenmacil** [comment]
Similar exception found in the log:

[EXC 02:04:53.230] NullReferenceException: Object reference not set to an instance of an object
	ProtoVessel..ctor (.Vessel VesselRef)
	ContractConfigurator.ContractVesselTracker+<>c__DisplayClass17_1.<OnVesselDestroy>b__0 (.Vessel v)
	System.Collections.Generic.List`1[Vessel].GetIndex (Int32 startIndex, Int32 count, System.Predicate`1 match)
	System.Collections.Generic.List`1[Vessel].Find (System.Predicate`1 match)
	ContractConfigurator.ContractVesselTracker.OnVesselDestroy (.Vessel vessel)
	EventData`1[Vessel].Fire (.Vessel data)
	Vessel.OnDestroy ()

**Comment by jrossignol** [comment]
Shoudl be fixed, but posted on the forums to get some additional verification.
