### ISSUE TITLE
Add "exclude" option to HasCrew parameter

### ISSUE THREAD

**Issue by Keniamin** [jrossignol/ContractConfigurator#512]
Based on the discussion in [Kerbin Side GAP forum topic](http://forum.kerbalspaceprogram.com/index.php?/topic/133545-10x-kerbin-side-gap/&page=2#comment-2573872).

> May be you can add some kind of "Exclude" option to HasCrew parameter with the meaning opposite to "kerbal" option (that is, player must have specified amount of crew except for those kerbals who are explicitly excluded)?

**Comment by jrossignol** [comment]
Added 'excludeKerbal' (works as you described it).
