### ISSUE TITLE
USI Sounding Rocket parts not recognized for Destroyed Vessel

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#513]
Unable to get a qualifying Sounding Rocket to trigger Vessel Destruction contract failure:

https://github.com/inigmatus/ContractPack-SoundingRockets/blob/master/Core/KSP-SR-2500m.cfg

**Comment by jrossignol** [comment]
I can take a look into this, but I'll need some more detail, as the vessel destroyed stuff checks for lots of different conditions.  The (typically) sure-fire way to get it to fire is to make sure the probe core is destroyed.  I'm assuming with the sounding rocket there isn't one?  Can you describe how the vessel is getting destroyed (impacting terrain vs water, how hard its hitting) and provide a KSP.log covering the desctruction of the vessel?

**Comment by inigmatus** [comment]
USI only has one probe core. The test is total destruction falling from 2100m. I'll get a log shortly.

**Comment by inigmatus** [comment]
Ok so I tested using this Sounding Rocket made from USI Sounding Rockets mod: http://www.mediafire.com/download/jbff03tc86cf227/Sounding_Rocket.craft

using this contract: https://github.com/inigmatus/ContractPack-SoundingRockets/blob/master/Core/KSP-SR-2000m.cfg

Issue: Launched it, did not deploy parachute intentionally, and let it crash to the ground, resulting in total destruction of vehicle, all parts.  The VesselNotDestroyed parameter is not triggering a contract failure.

Log: 
[LOG 15:07:42.279] ------------------- initializing flight mode... ------------------
[LOG 15:07:42.284] [MessageSystem] Save Messages
[LOG 15:07:42.285] Loading ship from file: C:/Users/Administrator/Documents/KSP/KSP_win_DEV/KSP_x64_Data/../saves/Development/Ships/VAB/Auto-Saved Ship.craft
[LOG 15:07:42.318] Sounding Rocket loaded!
[LOG 15:07:43.232] putting ship to ground: 11.26774
[LOG 15:07:43.233] [Sounding Rocket]: Ready to Launch - waiting to start physics...
[LOG 15:07:43.234] [FLIGHT GLOBALS]: Switching To Vessel Sounding Rocket ---------------------- 
[LOG 15:07:43.235] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[LOG 15:07:43.235] Reference Frame: Rotating
[LOG 15:07:43.238] Vessel assembly complete!
[LOG 15:07:43.238] all systems started
[LOG 15:07:43.247] QuickBrake(1.12): Settings Loaded
[LOG 15:07:43.453] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 15:07:43.454] [ScenarioUpgradeableFacilities]: Loading... 0 objects registered
[LOG 15:07:43.489] [DEBUG] ContractConfigurator.ContractDisabler: Disabling contract types...
[LOG 15:07:43.490] [INFO] ContractConfigurator.ContractDisabler: Disabled 0 ContractTypes.
[ERR 15:07:43.530] Cannot find a Module of typename 'HoloDeck'

[ERR 15:07:43.530] ScenarioModule is null.

[LOG 15:07:43.531] Loading Depletion Nodes
[LOG 15:07:43.531] DepNodeCount:  0
[LOG 15:07:43.532] Loading Biome Nodes
[LOG 15:07:43.532] BiomeNodeCount:  0
[LOG 15:07:43.532] Loading Planet Nodes
[LOG 15:07:43.533] PlanetNodeCount:  0
[WRN 15:07:43.534] [UiApp] Awake: CurrencyWidgetsApp
[WRN 15:07:43.534] [UiApp] Awake: ContractsApp
[WRN 15:07:43.534] [UiApp] Awake: ResourceDisplay
[WRN 15:07:43.535] [UiApp] Awake: KSPedia
[LOG 15:07:43.535] [ApplicationLauncher] OnSceneLoadedGUIReady: scene FLIGHT ShouldBeVisible() True ShouldBeOnTop() True iIsPositionedAtTop False
[LOG 15:07:43.536] [ApplicationLauncher] SpawnSimpleLayout: VerticalTopDown
[LOG 15:07:43.538] ScaleModList: listSize 41 maxListSize 879
[LOG 15:07:43.539] ScaleModList: listSize 41 maxListSize 870
[WRN 15:07:43.539] [KnowledgeBase] OnAppLauncherReady 33047
[LOG 15:07:43.546] ScaleModList: listSize 82 maxListSize 870
[LOG 15:07:43.636] ScaleModList: listSize 123 maxListSize 870
[LOG 15:07:43.637] ScaleModList: listSize 164 maxListSize 870
[LOG 15:07:43.637] ScaleModList: listSize 123 maxListSize 870
[LOG 15:07:43.646] DragCubeSystem: Rendering procedural drag for SR.Rocket.35.01
[LOG 15:07:43.674] [FlightIntegrator]: Vessel Sounding Rocket has been unloaded 1.79769313486232E+308, applying analytic temperature 312.157204515162
[LOG 15:07:43.682] [Progress Node Reached]: RecordsAltitude
[LOG 15:07:43.682] [Progress Node Reached]: RecordsSpeed
[LOG 15:07:43.682] [Progress Node Reached]: RecordsDistance
[LOG 15:07:43.694] [MessageSystem] Reposition 0.02 33048
[LOG 15:07:43.781] [PlanetariumCamera]: Focus: Sounding Rocket
[LOG 15:07:43.801] [UIApp] Adding ResourceDisplay to Application Launcher
[LOG 15:07:43.802] ScaleModList: listSize 123 maxListSize 829
[LOG 15:07:43.803] [UIApp] Adding ResourceDisplay to Application Launcher
[LOG 15:07:43.804] ScaleModList: listSize 123 maxListSize 788
[WRN 15:07:43.821] [ResourceDisplay] OnAppStarted(): id: -451204
[LOG 15:07:43.822] [GenericAppFrame] Reposition 0.1459277 33052
[LOG 15:07:43.823] [UIApp] Adding ContractsApp to Application Launcher
[LOG 15:07:43.824] ScaleModList: listSize 123 maxListSize 747
[WRN 15:07:43.824] [ResourceDisplay] OnAppStarted(): id: 224324
[LOG 15:07:43.825] ResourceDisplay already exist, destroying this instance
[LOG 15:07:43.825] [UIApp] OnDestroy: ResourceDisplay
[LOG 15:07:43.825] ScaleModList: listSize 123 maxListSize 747
[LOG 15:07:43.848] [GenericAppFrame] Reposition 0.1680019 33053
[LOG 15:07:43.855] CURRENCY WIDGET True True True
[LOG 15:07:43.856] [UIApp] Adding CurrencyWidgetsApp to Application Launcher
[LOG 15:07:43.858] ScaleModList: listSize 123 maxListSize 747
[LOG 15:07:43.882] [UIApp] Adding KSPedia to Application Launcher
[LOG 15:07:43.884] ScaleModList: listSize 123 maxListSize 706
[LOG 15:07:44.033] UIMasterController: ShowUI
[LOG 15:07:44.035] Flight State Captured
[LOG 15:07:44.036] Saving Achievements Tree...
[LOG 15:07:44.037] [MessageSystem] Save Messages
[LOG 15:07:44.044] Game State Saved as persistent
[LOG 15:07:44.057] WiderContractsApp: Making adjustments to contract frame!
[LOG 15:07:44.058] [GenericAppFrame] Reposition 0.3524253 33061
[LOG 15:07:45.050] Unpacking Sounding Rocket
[LOG 15:07:45.266] [Progress Node Reached]: Landing
[LOG 15:07:45.267] [Progress Node Reached]: Kerbin
[LOG 15:07:45.285] [Progress Node Complete]: Landing
[LOG 15:07:47.543] [F: 33263]: [00:00:02]: Liftoff!!
[LOG 15:07:47.637] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 0426fead-7c0d-4e3c-8d0f-6ec9574538ea
[LOG 15:07:47.639] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:07:47.641] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: bb6a72cc-1f5f-46e7-bb5d-a9604bdc2981
[LOG 15:07:47.643] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:07:47.645] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: e6c14b71-bb2b-4fdc-bb2e-9fd51926f0b7
[LOG 15:07:47.647] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:07:47.815] Added 1.999999 (2) reputation: 'Progression'.
[LOG 15:07:48.265] Added 1.999999 (2) reputation: 'Progression'.
[LOG 15:07:49.166] [F: 33361]: SR.LaunchStick collided into collider - relative velocity: 7.608205 - no impact momentum (no RB)
[LOG 15:07:49.166] SR.LaunchStick Exploded!! - blast awesomeness: 0.1
[LOG 15:07:49.167] [SR.LaunchStick]: Deactivated
[LOG 15:07:49.167] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: e6c14b71-bb2b-4fdc-bb2e-9fd51926f0b7
[LOG 15:07:49.168] [F: 33361]: [00:00:03]: Launch Stick collided into Launch Pad.
[LOG 15:07:49.168] [F: 33361]: SR.LaunchStick collided into collider - relative velocity: 7.609018 - no impact momentum (no RB)
[LOG 15:07:49.169] [Explosion] Combined.
[LOG 15:07:49.169] SR.LaunchStick Exploded!! - blast awesomeness: 0.1
[LOG 15:07:49.170] [SR.LaunchStick]: Deactivated
[LOG 15:07:49.170] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 0426fead-7c0d-4e3c-8d0f-6ec9574538ea
[LOG 15:07:49.173] 1 explosions created.
[LOG 15:07:49.198] [F: 33363]: SR.LaunchStick collided into collider - relative velocity: 7.698964 - no impact momentum (no RB)
[LOG 15:07:49.198] SR.LaunchStick Exploded!! - blast awesomeness: 0.1
[LOG 15:07:49.198] [SR.LaunchStick]: Deactivated
[LOG 15:07:49.199] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: bb6a72cc-1f5f-46e7-bb5d-a9604bdc2981
[LOG 15:07:49.200] [F: 33363]: [00:00:04]: Launch Stick collided into Launch Pad.
[LOG 15:07:49.202] 1 explosions created.
[LOG 15:07:49.565] Added 1.999999 (2) reputation: 'Progression'.
[LOG 15:07:50.248] Added 1.999999 (2) reputation: 'Progression'.
[LOG 15:08:03.266] Added 1.999999 (2) reputation: 'Progression'.
[LOG 15:08:37.896] [F: 36243]: [SR.PayloadTruss.35] Collision Enhancer Punch Through - vel: 82.86034
[LOG 15:08:37.897] [F: 36243]: [00:00:52]: Payload Truss (0.35m) collided into the surface.
[LOG 15:08:37.897] SR.PayloadTruss.35 Exploded!! - blast awesomeness: 0.1
[LOG 15:08:37.898] [SR.ProbeCore]: Deactivated
[LOG 15:08:37.898] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:08:37.899] [SR.Battery]: Deactivated
[LOG 15:08:37.899] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:08:37.902] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 8e69dc10-4fb5-424b-8242-ad55da89b2f4
[LOG 15:08:37.902] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:08:37.903] [SR.PayloadTruss.35]: Deactivated
[LOG 15:08:37.904] [DEBUG] ContractConfigurator.ContractVesselTracker: OnVesselWasModified: 48adb548-61ef-42f7-944b-61bd55427e54
[LOG 15:08:37.904] [F: 36243]: [SR.Nosecone.35] Collision Enhancer Punch Through - vel: 82.88506
[LOG 15:08:37.905] [F: 36243]: [00:00:52]: Nosecone Parachute (0.35m) collided into the surface.
[LOG 15:08:37.905] [Explosion] Combined.

**Comment by jrossignol** [comment]
Okay, VesselNotDestroyed has had a fair bit of improvements, but it didn't work in all tests for your contract.  The problem is that your VesselParameterGroup can un-assign the vessel right before it's destroyed (for example, if the avionics is knocked loose and *then* destroyed).  I'd suggest moving the "reach 2000m" bit into the same VPG and setting it to disableOnStateChange = true (once they hit 2000m with a valid vessel they must either pass or fail the contract).

**Comment by inigmatus** [comment]
Thanks. Setting VPG definition to disableOnStateChange = true resolved it in the latest dev build.

unrelated: latest dev build apparently duplicates CC contract offerings now.

**Comment by jrossignol** [comment]
Could you raise a new issue with more specifics and I'll take a look
tomorrow?
