### ISSUE TITLE
Expression Parser won't validate ExperienceTrait()

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#516]
Using the following expression in a DATA node:

``AllKerbals().Where(m => m.ExperienceTrait() == Pilot).Random()``

Will not validate. The other AllKerbals() stuff (like Type(), RosterStatus() etc) are all fine, but this one comes up with an error that basically says the StringParser doesn't support it. I can provide logs if needed but it's pretty easy to reproduce.

**Comment by jrossignol** [comment]
Unsure if this works in this case, but for a lot of these you can do a
'cast' of the constant:
```

AllKerbals().Where(m => m.ExperienceTrait() ==
ExperienceTrait(Pilot)).Random()
```

Either way, I'd expect the expression as you wrote it to work, so will
consider it a bug.

**Comment by severedsolo** [comment]
Nah, just crapped out a different way. Said it can't find a function for ExperienceTrait in string (or something like that, I guess it means "I don't know what you want me to do with this")

**Comment by jrossignol** [comment]
Took a quick peek and it's because it's documented wrong.
ExperienceTrait() actually returns a string, so the correct expression
would be:
```

AllKerbals().Where(m => m.ExperienceTrait() == "Pilot").Random()

```

**Comment by severedsolo** [comment]
Ok that seems to have worked. I'll leave this open though, as you probably want to update the docs. It says it returns an ExperienceTrait not a string.

**Comment by jrossignol** [comment]
Documentation is now fixed.
