### ISSUE TITLE
hideOnCompletion not working in VisitWaypoint parameter

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#519]
As above. Waypoints don't disappear when the VisitWaypoint is completed. 

Can provide a contract if you need it, but I've removed them for now and turned showMessages on instead to work around it, so would need a little work to put them back (but happy to do it if you need it)

Edit: example contract with hideOnCompletion missing due to workaround: https://github.com/severedsolo/KerbalAcademy/blob/master/KerbalAcademyFlightSchool.cfg

**Comment by jrossignol** [comment]
Worked fine in Anomaly Surveyor's Kerbin monolith contract.  I'll need a more detailed test case to understand what's going on for you.  Also, it's not clear how showMessages is a workaround here.

**Comment by severedsolo** [comment]
showMessages was more "Let's get something that basically works, and I can see when I've hit that waypoint and move on to the next one". 

With no other parameters, (and hideOnCompletion not working for me) just using "VisitWaypoint" the only way to see if you'd hit it was watch the contract window, so not watching the plane, which is inadvisable when you are doing high G turns above KSC.

Alright I'm not convinced this is a bug in CC - it seems to be connected to a problem im Waypoint Manager I've been having (which I'm not sure is WPM for the stock system) - I'll post on the WPM forum thread and explain.

**Comment by jrossignol** [comment]
Note that WPM doesn't really "select" a waypoint (it's just a passthrough to the stock mechanic of the active waypoint).  So it shouldn't change anything here.  I'll do another test with the waypoint selected.

**Comment by jrossignol** [comment]
Right, now I get it.  It doesn't disappear from the list in Waypoint Manager, so it's a bug there.

If you want some auto-select logic to select the "next" waypoint, raise an enhancement and I'll implement that.

**Comment by jrossignol** [comment]
Raised https://github.com/jrossignol/WaypointManager/issues/47, closing this issue.

**Comment by severedsolo** [comment]
Ok that would be awesome, do you want the issue raised under this or WPM?

**Comment by jrossignol** [comment]
It would need to be Contract Configurator logic, so here.
