### ISSUE TITLE
Next Kerbal Hire Cost

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#520]
Would it be possible to get next hire cost in expression format? I was thinking something like Global Functions (where Science() and things are) would be perfect. I want to be able to re-imburse the player half of their hire costs basically.

**Comment by jrossignol** [comment]
Added NextKerbalHireCost() (documented in the Kerbal wiki page).

**Comment by severedsolo** [comment]
Your a gent, cheers!
