### ISSUE TITLE
AwardExperience doesn't award straight away if contract completes on a scene change.

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#521]
If you use a parameter like CollectScience and the recovery method is Recovery - you recover the vessel and the contract completes.

However, AwardExperience does not kick in straight away. In order for the kerbal to get their experience, you have to load them into a vessel, and recover them again, at which point the experience will be given.

Basically, what i think is happening is that AwardExperience is happening after the Kerbal has been recovered (which makes sense, because the contract can't complete until recovery has happened)

Example contract: https://github.com/severedsolo/KerbalAcademy/blob/master/KerbalAcademyScientificPrinciples.cfg (at the moment recovery is set to Transmit to work around this, but if you change it back to Recovery you'll see what I mean)

**Comment by jrossignol** [comment]
Fixed for next release.
