### ISSUE TITLE
1.11.6 dev build: Duplicate Contracts

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#523]
using latest dev build, all Contract Configurator contracts in the GAP contract pack (and in my Sounding Rockets contract pack https://github.com/inigmatus/ContractPack-SoundingRockets) show up as doubled, tripled or even quadrupled in Mission Control Available Contracts page.

http://i.imgur.com/cE7L9OY.png

**Comment by inigmatus** [comment]
I think also related is that when I select a contract and make it active, sometimes randomly when I load a craft to a launch pad (in this case the sounding rocket from a previous issue I raised) the contract is removed by CC altogether.

http://i.imgur.com/hxloOtf.png

**Comment by jrossignol** [comment]
If you have a log on this one it may help.

**Comment by inigmatus** [comment]
[WRN 23:51:39.670] [HighLogic]: =========================== Scene Change : From SPACECENTER to FLIGHT (Async) =====================
[LOG 23:51:40.028] ScaleModList: listSize 82 maxListSize 1713
[LOG 23:51:40.136] [UIApp] OnDestroy: ContractsApp
[LOG 23:51:40.137] ScaleModList: listSize 82 maxListSize 1713
[LOG 23:51:40.137] [UIApp] OnDestroy: KSPedia
[LOG 23:51:40.137] ScaleModList: listSize 82 maxListSize 1713
[LOG 23:51:40.280] AddonLoader: Instantiating addon 'TitleTrackerHelper' from assembly 'ContractConfigurator'
[LOG 23:51:40.282] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[LOG 23:51:40.283] UIMasterController: HideUI
[WRN 23:51:40.910] The referenced script on this Behaviour is missing!
[WRN 23:51:40.911] The referenced script on this Behaviour is missing!
[WRN 23:51:41.068] [UiApp] Awake: ResourceDisplay
[LOG 23:51:41.069] UICanvasPrefabSpawner FlightUI spawning Flight
[LOG 23:51:41.208] AddonLoader: Instantiating addon 'NavWaypoint' from assembly 'KSP'
[LOG 23:51:41.210] AddonLoader: Instantiating addon 'AeroGUI' from assembly 'KSP'
[LOG 23:51:41.213] AddonLoader: Instantiating addon 'TitleTrackerHelper' from assembly 'ContractConfigurator'
[LOG 23:51:41.214] AddonLoader: Instantiating addon 'QuickBrake' from assembly 'QuickBrake'
[LOG 23:51:41.215] AddonLoader: Instantiating addon 'VesselMove' from assembly 'VesselMover'
[LOG 23:51:41.215] AddonLoader: Instantiating addon 'VesselSpawn' from assembly 'VesselMover'
[LOG 23:51:41.215] AddonLoader: Instantiating addon 'VesselMoverToolbar' from assembly 'VesselMover'
[LOG 23:51:41.216] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[LOG 23:51:41.218] UIMasterController: HideUI
[LOG 23:51:41.239] ------------------- initializing flight mode... ------------------
[LOG 23:51:41.250] [MessageSystem] Save Messages
[LOG 23:51:41.250] Loading ship from file: C:\Users\Administrator\Documents\KSP\KSP_win_DEV\saves\Development\Ships\VAB\Auto-Saved Ship.craft
[LOG 23:51:41.284] Sounding Rocket loaded!
[LOG 23:51:42.191] putting ship to ground: 11.26774
[LOG 23:51:42.193] [Sounding Rocket]: Ready to Launch - waiting to start physics...
[LOG 23:51:42.194] [FLIGHT GLOBALS]: Switching To Vessel Sounding Rocket ---------------------- 
[LOG 23:51:42.195] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[LOG 23:51:42.195] Reference Frame: Rotating
[LOG 23:51:42.197] Vessel assembly complete!
[LOG 23:51:42.197] all systems started
[LOG 23:51:42.207] QuickBrake(1.12): Settings Loaded
[LOG 23:51:42.508] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 23:51:42.511] [ScenarioUpgradeableFacilities]: Loading... 0 objects registered
[LOG 23:51:42.562] [DEBUG] ContractConfigurator.ContractDisabler: Disabling contract types...
[LOG 23:51:42.563] [INFO] ContractConfigurator.ContractDisabler: Disabled 0 ContractTypes.
[ERR 23:51:42.598] Cannot find a Module of typename 'HoloDeck'

[ERR 23:51:42.598] ScenarioModule is null.

[LOG 23:51:42.599] Loading Depletion Nodes
[LOG 23:51:42.600] DepNodeCount:  0
[LOG 23:51:42.600] Loading Biome Nodes
[LOG 23:51:42.600] BiomeNodeCount:  0
[LOG 23:51:42.601] Loading Planet Nodes
[LOG 23:51:42.601] PlanetNodeCount:  0
[WRN 23:51:42.602] [UiApp] Awake: CurrencyWidgetsApp
[WRN 23:51:42.602] [UiApp] Awake: ContractsApp
[WRN 23:51:42.603] [UiApp] Awake: ResourceDisplay
[WRN 23:51:42.603] [UiApp] Awake: KSPedia
[LOG 23:51:42.603] [ApplicationLauncher] OnSceneLoadedGUIReady: scene FLIGHT ShouldBeVisible() True ShouldBeOnTop() True iIsPositionedAtTop False
[LOG 23:51:42.604] [ApplicationLauncher] SpawnSimpleLayout: VerticalTopDown
[LOG 23:51:42.606] ScaleModList: listSize 41 maxListSize 879
[LOG 23:51:42.607] ScaleModList: listSize 41 maxListSize 870
[WRN 23:51:42.607] [KnowledgeBase] OnAppLauncherReady 43729
[LOG 23:51:42.614] ScaleModList: listSize 82 maxListSize 870
[LOG 23:51:42.619] ScaleModList: listSize 123 maxListSize 870
[LOG 23:51:42.620] ScaleModList: listSize 164 maxListSize 870
[LOG 23:51:42.620] ScaleModList: listSize 123 maxListSize 870
[LOG 23:51:42.623] DragCubeSystem: Rendering procedural drag for SR.Rocket.35.01
[LOG 23:51:42.651] [FlightIntegrator]: Vessel Sounding Rocket has been unloaded 1.79769313486232E+308, applying analytic temperature 312.68566321495
[LOG 23:51:42.668] [MessageSystem] Reposition 0.02 43730
[LOG 23:51:42.683] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type SSI-Start (Join SSI Aerospace!): Too many active contracts.
[LOG 23:51:42.684] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type SSI-Start (Join SSI Aerospace!): Too many active contracts.
[LOG 23:51:42.684] [INFO] ContractConfigurator.ContractType: Cancelling contract of type KSP-SR-2000m (Fly a sounding rocket to 2000m.): Too many active contracts.
[WRN 23:51:42.685] ContractConfigurator.ConfiguredContract: Removed contract 'Fly a sounding rocket to 2000m.', as it no longer meets the requirements.
[LOG 23:51:42.686] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type KSP-SR-2000m (Fly a sounding rocket to 2000m.): Too many active contracts.
[LOG 23:51:42.687] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type KSP-SR-2000m (Fly a sounding rocket to 2000m.): Too many active contracts.
[LOG 23:51:42.728] [INFO] ContractConfigurator.ConfiguredContract16: Generated contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:51:42.731] [INFO] ContractConfigurator.ConfiguredContract6: Generated contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:51:42.764] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:51:42.767] [INFO] ContractConfigurator.ConfiguredContract9: Generated contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:51:42.773] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:51:42.774] [INFO] ContractConfigurator.ConfiguredContract10: Generated contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:51:42.815] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:51:42.818] [INFO] ContractConfigurator.ConfiguredContract10: Generated contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:51:42.820] [PlanetariumCamera]: Focus: Sounding Rocket
[LOG 23:51:42.836] [UIApp] Adding ResourceDisplay to Application Launcher
[LOG 23:51:42.837] ScaleModList: listSize 123 maxListSize 829
[LOG 23:51:42.837] [UIApp] Adding ResourceDisplay to Application Launcher
[LOG 23:51:42.838] ScaleModList: listSize 123 maxListSize 788
[WRN 23:51:42.850] [ResourceDisplay] OnAppStarted(): id: -334838
[LOG 23:51:42.851] [GenericAppFrame] Reposition 0.1545677 43734
[LOG 23:51:42.851] [UIApp] Adding ContractsApp to Application Launcher
[LOG 23:51:42.852] ScaleModList: listSize 123 maxListSize 747
[WRN 23:51:42.853] [ResourceDisplay] OnAppStarted(): id: 174390
[LOG 23:51:42.853] ResourceDisplay already exist, destroying this instance
[LOG 23:51:42.854] [UIApp] OnDestroy: ResourceDisplay
[LOG 23:51:42.854] ScaleModList: listSize 123 maxListSize 747
[LOG 23:51:42.862] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:51:42.864] [GenericAppFrame] Reposition 0.1706722 43735
[LOG 23:51:42.865] CURRENCY WIDGET True True True
[LOG 23:51:42.865] [UIApp] Adding CurrencyWidgetsApp to Application Launcher
[LOG 23:51:42.866] ScaleModList: listSize 123 maxListSize 747
[LOG 23:51:42.878] [UIApp] Adding KSPedia to Application Launcher
[LOG 23:51:42.880] ScaleModList: listSize 123 maxListSize 706
[LOG 23:51:42.988] UIMasterController: ShowUI
[LOG 23:51:42.991] Flight State Captured
[LOG 23:51:42.993] Saving Achievements Tree...
[LOG 23:51:42.993] Saving Achievements Tree...
[LOG 23:51:42.994] [MessageSystem] Save Messages
[LOG 23:51:43.003] Game State Saved as persistent
[LOG 23:51:43.014] WiderContractsApp: Making adjustments to contract frame!
[LOG 23:51:43.015] [GenericAppFrame] Reposition 0.2925269 43743
[LOG 23:51:43.202] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:51:43.984] Unpacking Sounding Rocket
[LOG 23:51:44.215] [Progress Node Reached]: RecordsDistance
[LOG 23:52:46.031] [DEBUG] ContractConfigurator.ContractPreLoader: Contract attribute took too long (0.1486206 seconds) to generate: CoastGuard-DropBuoys-Carrier[kerbal]
[LOG 23:53:13.883] SCREENSHOT!!
[LOG 23:56:42.229] UIMasterController: ShowUI
[LOG 23:56:42.229] Game Paused!
[LOG 23:56:43.710] [FlightDriver]: Flight State Reverted to Prelaunch.
[LOG 23:56:43.725] Game State Saved as persistent
[LOG 23:56:43.728] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:43.730] UIMasterController: ShowUI
[LOG 23:56:43.730] Game Unpaused!
[WRN 23:56:43.731] Can not play a disabled audio source
[LOG 23:56:43.732] UIMasterController: HideUI
[WRN 23:56:43.740] [HighLogic]: =========================== Scene Change : From FLIGHT to EDITOR =====================
[LOG 23:56:43.753] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:43.755] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:44.305] KbApp.OnDestroy Planet Resources
[LOG 23:56:44.305] KbApp.OnDestroy Planet Info
[LOG 23:56:44.306] KbApp.OnDestroy Vessel Info
[LOG 23:56:44.307] [UIApp] OnDestroy: ContractsApp
[LOG 23:56:44.307] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:44.308] KbApp.OnDestroy Planet Parameters
[LOG 23:56:44.308] KbApp.OnDestroy Unowned Info
[LOG 23:56:44.309] [PlanetariumCamera]: Focus: Kerbin
[LOG 23:56:44.309] KbApp.OnDestroy NullName
[LOG 23:56:44.310] KbApp.OnDestroy Vessel Crew
[LOG 23:56:44.310] [UIApp] OnDestroy: ResourceDisplay
[LOG 23:56:44.311] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:44.311] [UIApp] OnDestroy: KSPedia
[LOG 23:56:44.312] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:44.312] [UIApp] OnDestroy: CurrencyWidgetsApp
[LOG 23:56:44.312] ScaleModList: listSize 123 maxListSize 706
[LOG 23:56:44.326] UICanvasPrefabSpawner SceneLogic spawning Editor
[LOG 23:56:44.348] No Input Locks in effect right now
[LOG 23:56:44.476] AddonLoader: Instantiating addon 'TitleTrackerHelper' from assembly 'ContractConfigurator'
[LOG 23:56:44.477] AddonLoader: Instantiating addon 'QEditor' from assembly 'QuickSearch'
[LOG 23:56:44.478] AddonLoader: Instantiating addon 'HotkeyManager' from assembly 'Scale'
[LOG 23:56:44.480] AddonLoader: Instantiating addon 'TechUpdater' from assembly 'Scale'
[LOG 23:56:44.480] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[LOG 23:56:44.486] UIMasterController: ShowUI
[WRN 23:56:44.728] The referenced script on this Behaviour is missing!
[WRN 23:56:44.728] The referenced script on this Behaviour is missing!
[WRN 23:56:44.729] The referenced script on this Behaviour is missing!
[LOG 23:56:44.914] ------------------- initializing editor mode... ------------------
[LOG 23:56:44.914] editor started
[LOG 23:56:44.929] IconLoader awake
[LOG 23:56:45.013] Sounding Rocket loaded!
[WRN 23:56:45.168] HighlightingSystem : Framebuffer depth data is not available and can't be used to occlude highlighting. Highlighting occluders enabled.
[LOG 23:56:45.222] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 23:56:45.222] [ScenarioUpgradeableFacilities]: Loading... 0 objects registered
[ERR 23:56:45.223] Cannot find a Module of typename 'HoloDeck'

[ERR 23:56:45.223] ScenarioModule is null.

[LOG 23:56:45.224] Loading Depletion Nodes
[LOG 23:56:45.224] DepNodeCount:  0
[LOG 23:56:45.224] Loading Biome Nodes
[LOG 23:56:45.225] BiomeNodeCount:  0
[LOG 23:56:45.225] Loading Planet Nodes
[LOG 23:56:45.225] PlanetNodeCount:  0
[WRN 23:56:45.226] [UiApp] Awake: EngineersReport
[WRN 23:56:45.227] [UiApp] Awake: ContractsApp
[WRN 23:56:45.227] [UiApp] Awake: KSPedia
[LOG 23:56:45.227] [ApplicationLauncher] OnSceneLoadedGUIReady: scene EDITOR ShouldBeVisible() True ShouldBeOnTop() False iIsPositionedAtTop True
[LOG 23:56:45.228] [ApplicationLauncher] SpawnSimpleLayout: HorizontalRightLeft
[LOG 23:56:45.230] ScaleModList: listSize 41 maxListSize 1545
[LOG 23:56:45.231] ScaleModList: listSize 41 maxListSize 1536
[LOG 23:56:45.232] ScaleModList: listSize 82 maxListSize 1536
[LOG 23:56:45.233] ScaleModList: listSize 41 maxListSize 1536
[LOG 23:56:45.284] *****Adding icon for Rovers
[LOG 23:56:45.285] *****Adding icon for Kolonization Lite
[LOG 23:56:45.286] *****Adding icon for Freight
[LOG 23:56:45.287] *****Adding icon for Kolonization
[LOG 23:56:45.301] [MessageSystem] Reposition 0.02 54057
[WRN 23:56:45.303] UIList: RemoveItem didn't find any item to remove.
[WRN 23:56:45.303] UIList: RemoveItem didn't find any item to remove.
[WRN 23:56:45.304] UIList: RemoveItem didn't find any item to remove.
[WRN 23:56:45.304] UIList: RemoveItem didn't find any item to remove.
[LOG 23:56:45.404] [UIApp] Adding ContractsApp to Application Launcher
[LOG 23:56:45.406] ScaleModList: listSize 41 maxListSize 1495
[LOG 23:56:45.427] [GenericAppFrame] Reposition 0.1547556 54062
[LOG 23:56:45.430] [UIApp] Adding EngineersReport to Application Launcher
[LOG 23:56:45.431] ScaleModList: listSize 41 maxListSize 1454
[LOG 23:56:45.449] WiderContractsApp: Making adjustments to contract frame!
[LOG 23:56:45.450] [GenericAppFrame] Reposition 0.1547556 54062
[LOG 23:56:45.455] [UIApp] Adding KSPedia to Application Launcher
[LOG 23:56:45.457] ScaleModList: listSize 41 maxListSize 1413
[LOG 23:56:45.458] [GenericAppFrame] Reposition 0.1838971 54063
[LOG 23:56:51.030] [MessageSystem] Save Messages
[LOG 23:56:51.037] Game State Saved to saves/Development/persistent
[LOG 23:56:51.039] ScaleModList: listSize 41 maxListSize 1413
[LOG 23:56:51.039] UIMasterController: HideUI
[WRN 23:56:51.046] [HighLogic]: =========================== Scene Change : From EDITOR to SPACECENTER =====================
[LOG 23:56:51.046] [DEBUG] ContractConfigurator.ContractConfigurator: Desired ConfiguredContract weight is 359.504373676446
[LOG 23:56:51.047] [INFO] ContractConfigurator.ContractConfigurator: Finished Adjusting ContractTypes, 12 entries with weight 30 added.
[WRN 23:56:51.056] The referenced script on this Behaviour is missing!
[WRN 23:56:51.056] The referenced script on this Behaviour is missing!
[WRN 23:56:51.056] The referenced script on this Behaviour is missing!
[WRN 23:56:51.057] The referenced script on this Behaviour is missing!
[WRN 23:56:51.057] The referenced script on this Behaviour is missing!
[WRN 23:56:51.057] The referenced script on this Behaviour is missing!
[LOG 23:56:51.225] [UIApp] OnDestroy: EngineersReport
[LOG 23:56:51.225] ScaleModList: listSize 41 maxListSize 1413
[LOG 23:56:51.226] [UIApp] OnDestroy: KSPedia
[LOG 23:56:51.226] ScaleModList: listSize 41 maxListSize 1413
[LOG 23:56:51.227] [UIApp] OnDestroy: ContractsApp
[LOG 23:56:51.227] ScaleModList: listSize 41 maxListSize 1413
[LOG 23:56:51.369] AddonLoader: Instantiating addon 'CustomConfigsManager' from assembly 'ModuleManager'
[LOG 23:56:51.370] AddonLoader: Instantiating addon 'TitleTrackerHelper' from assembly 'ContractConfigurator'
[LOG 23:56:51.371] AddonLoader: Instantiating addon 'CustomBarnKit' from assembly 'CustomBarnKit'
[LOG 23:56:51.372] AddonLoader: Instantiating addon 'QRnD' from assembly 'QuickSearch'
[LOG 23:56:51.374] AddonLoader: Instantiating addon 'WiderContractsApp' from assembly 'WiderContractsApp'
[LOG 23:56:52.345] UIMasterController: ShowUI
[LOG 23:56:52.616] [CustomBarnKit] Loading new upgrades prices
[LOG 23:56:52.623] [CustomBarnKit] VehicleAssemblyBuilding Copying level 0 for level 1
[LOG 23:56:52.624] [CustomBarnKit] VehicleAssemblyBuilding Copying level 1 for level 2
[LOG 23:56:52.624] [CustomBarnKit] VehicleAssemblyBuilding Copying level 2 for level 3
[LOG 23:56:52.633] [CustomBarnKit] TrackingStation Copying level 0 for level 1
[LOG 23:56:52.634] [CustomBarnKit] TrackingStation Copying level 1 for level 2
[LOG 23:56:52.634] [CustomBarnKit] TrackingStation Copying level 2 for level 3
[LOG 23:56:52.645] [CustomBarnKit] SpaceplaneHangar Copying level 0 for level 1
[LOG 23:56:52.645] [CustomBarnKit] SpaceplaneHangar Copying level 1 for level 2
[LOG 23:56:52.646] [CustomBarnKit] SpaceplaneHangar Copying level 2 for level 3
[LOG 23:56:52.656] [CustomBarnKit] Runway Copying level 0 for level 1
[LOG 23:56:52.657] [CustomBarnKit] Runway Copying level 1 for level 2
[LOG 23:56:52.657] [CustomBarnKit] Runway Copying level 2 for level 3
[LOG 23:56:52.666] [CustomBarnKit] ResearchAndDevelopment Copying level 0 for level 1
[LOG 23:56:52.666] [CustomBarnKit] ResearchAndDevelopment Copying level 1 for level 2
[LOG 23:56:52.667] [CustomBarnKit] ResearchAndDevelopment Copying level 2 for level 3
[LOG 23:56:52.679] [CustomBarnKit] MissionControl Copying level 0 for level 1
[LOG 23:56:52.680] [CustomBarnKit] MissionControl Copying level 1 for level 2
[LOG 23:56:52.680] [CustomBarnKit] MissionControl Copying level 2 for level 3
[LOG 23:56:52.692] [CustomBarnKit] LaunchPad Copying level 0 for level 1
[LOG 23:56:52.692] [CustomBarnKit] LaunchPad Copying level 1 for level 2
[LOG 23:56:52.693] [CustomBarnKit] LaunchPad Copying level 2 for level 3
[LOG 23:56:52.704] [CustomBarnKit] AstronautComplex Copying level 0 for level 1
[LOG 23:56:52.704] [CustomBarnKit] AstronautComplex Copying level 1 for level 2
[LOG 23:56:52.705] [CustomBarnKit] AstronautComplex Copying level 2 for level 3
[LOG 23:56:52.729] [CustomBarnKit] Administration Copying level 0 for level 1
[LOG 23:56:52.729] [CustomBarnKit] Administration Copying level 1 for level 2
[LOG 23:56:52.729] [CustomBarnKit] Administration Copying level 2 for level 3
[LOG 23:56:52.744] [CustomBarnKit] New upgrades prices are Loaded
[LOG 23:56:52.774] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 23:56:52.776] [ScenarioUpgradeableFacilities]: Loading... 0 objects registered
[LOG 23:56:52.779] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract12 (ContractConfigurator.dll)
[LOG 23:56:52.779] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract13 (ContractConfigurator.dll)
[LOG 23:56:52.780] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract14 (ContractConfigurator.dll)
[LOG 23:56:52.780] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract15 (ContractConfigurator.dll)
[LOG 23:56:52.781] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract16 (ContractConfigurator.dll)
[LOG 23:56:52.782] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract17 (ContractConfigurator.dll)
[LOG 23:56:52.782] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract18 (ContractConfigurator.dll)
[LOG 23:56:52.783] [DEBUG] ContractConfigurator.ContractDisabler: Enabling ContractType: ContractConfigurator.ConfiguredContract19 (ContractConfigurator.dll)
[LOG 23:56:52.810] [DEBUG] ContractConfigurator.ContractDisabler: Disabling contract types...
[LOG 23:56:52.811] [INFO] ContractConfigurator.ContractDisabler: Disabled 0 ContractTypes.
[ERR 23:56:52.846] Cannot find a Module of typename 'HoloDeck'

[ERR 23:56:52.847] ScenarioModule is null.

[LOG 23:56:52.847] Loading Depletion Nodes
[LOG 23:56:52.848] DepNodeCount:  0
[LOG 23:56:52.848] Loading Biome Nodes
[LOG 23:56:52.848] BiomeNodeCount:  0
[LOG 23:56:52.848] Loading Planet Nodes
[LOG 23:56:52.849] PlanetNodeCount:  0
[WRN 23:56:52.906] [UiApp] Awake: ContractsApp
[WRN 23:56:52.906] [UiApp] Awake: KSPedia
[LOG 23:56:52.906] [ApplicationLauncher] OnSceneLoadedGUIReady: scene SPACECENTER ShouldBeVisible() True ShouldBeOnTop() False iIsPositionedAtTop False
[LOG 23:56:52.908] ScaleModList: listSize 41 maxListSize 1795
[LOG 23:56:52.909] ScaleModList: listSize 82 maxListSize 1795
[LOG 23:56:52.910] ScaleModList: listSize 41 maxListSize 1795
[LOG 23:56:52.914] ScaleModList: listSize 82 maxListSize 1795
[LOG 23:56:52.952] [MessageSystem] Reposition 0.02 54401
[LOG 23:56:52.990] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type SSI-Start (Join SSI Aerospace!): Too many active contracts.
[LOG 23:56:52.991] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type SSI-Start (Join SSI Aerospace!): Too many active contracts.
[LOG 23:56:52.992] [INFO] ContractConfigurator.ContractType: Cancelling contract of type KSP-SR-2000m (Fly a sounding rocket to 2000m.): Too many active contracts.
[WRN 23:56:52.992] ContractConfigurator.ConfiguredContract: Removed contract 'Fly a sounding rocket to 2000m.', as it no longer meets the requirements.
[LOG 23:56:52.993] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type KSP-SR-2000m (Fly a sounding rocket to 2000m.): Too many active contracts.
[LOG 23:56:52.995] [DEBUG] ContractConfigurator.ContractType: Cancelling contract of type KSP-SR-2000m (Fly a sounding rocket to 2000m.): Too many active contracts.
[LOG 23:56:53.019] [INFO] ContractConfigurator.ConfiguredContract8: Generated contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:56:53.022] [INFO] ContractConfigurator.ConfiguredContract15: Generated contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:56:53.160] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:56:53.163] [INFO] ContractConfigurator.ConfiguredContract14: Generated contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:56:53.170] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:56:53.170] [INFO] ContractConfigurator.ConfiguredContract10: Generated contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:56:53.303] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:56:53.305] [INFO] ContractConfigurator.ConfiguredContract13: Generated contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:56:53.346] [UIApp] Adding ContractsApp to Application Launcher
[LOG 23:56:53.347] ScaleModList: listSize 82 maxListSize 1754
[LOG 23:56:53.363] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [SSI-Start]
[LOG 23:56:53.364] [GenericAppFrame] Reposition 0.1669425 54406
[LOG 23:56:53.375] WiderContractsApp: Making adjustments to contract frame!
[LOG 23:56:53.375] [GenericAppFrame] Reposition 0.1669425 54406
[LOG 23:56:53.378] [UIApp] Adding KSPedia to Application Launcher
[LOG 23:56:53.380] ScaleModList: listSize 82 maxListSize 1713
[LOG 23:56:53.680] [DEBUG] ContractConfigurator.ConfiguredContract: Initializing contract: CONTRACT_TYPE [KSP-SR-2000m]
[LOG 23:56:58.480] UIMasterController: ShowUI
[LOG 23:56:58.481] Game Paused!
[LOG 23:57:02.292] [KSPUpgradePipeline]: Development updated from 1.0.5 to 1.1.2.
[LOG 23:57:02.298] ScenarioTypes: List Created 21 scenario types loaded from 18 loaded assemblies.
[LOG 23:57:02.298] [Game]: ScenarioModule ResourceScenario already exists in save, but saved target scenes do not match module definition. Updating...
[LOG 23:57:02.299] [MessageSystem] Load Messages
[LOG 23:57:02.302] [MessageSystem] Save Messages
[LOG 23:57:02.311] Game State Saved to saves/Development/persistent
[LOG 23:57:02.313] ScaleModList: listSize 82 maxListSize 1713
[LOG 23:57:02.314] UIMasterController: ShowUI
[LOG 23:57:02.315] Game Unpaused!
[LOG 23:57:02.316] UIMasterController: HideUI
[WRN 23:57:02.318] [HighLogic]: =========================== Scene Change : From SPACECENTER to SPACECENTER =====================
[LOG 23:57:02.319] [DEBUG] ContractConfigurator.ContractConfigurator: Desired ConfiguredContract weight is 359.504373676446
[LOG 23:57:02.319] [INFO] ContractConfigurator.ContractConfigurator: Finished Adjusting ContractTypes, 12 entries with weight 30 added.
[LOG 23:57:02.321] UIMasterController: ShowUI
[LOG 23:57:02.321] Game Unpaused!

**Comment by jrossignol** [comment]
Thanks for this.  Fixed.
