### ISSUE TITLE
Rendezvous vessel definition

### ISSUE THREAD

**Issue by danielguo** [jrossignol/ContractConfigurator#524]
I faced the issue that I cannot complete the RP-0 First Space Station contract. I traced the contract definition and state.

What happened is that in the Rendezvous step, crewCapsule got defined as the same vehicle as spaceStation. When using Rendezvous with Define, is there a guarantee that the "defined vessel" is different from the "target vessel"?

Contract definition: https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/Milestones/Station.cfg#L117

[fromSavefile.zip](https://github.com/jrossignol/ContractConfigurator/files/288051/fromSavefile.zip)

**Comment by danielguo** [comment]
I did a similar contract: https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/Human%20Spaceflight/Station%20Crew%20Rotation.cfg#L45

But it worked fine this time, so not sure if there is some special condition triggering this.

**Comment by jrossignol** [comment]
Fixed for next release.
