### ISSUE TITLE
SpawnVessel issues

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#525]
Sorry for the non-descript title not really sure how to describe this succinctly.

Ok, so I spawn a vessel on contract creation at the KSC PQS City (which seems to be on the crawlerway) - the vessel is spawned upside down.

So I manually set pitch to 180. When you launch your vessel after the vessel spawns and walk over to it, the craft is upside down, and half of it is either destroyed or missing under the crawlerway (not 100% sure which due to this next bit).

EVA kerbal jumps into the vessel, suddenly the vessel "respawns" at the correct place, the right way up, and a little off the ground (as I understand it this bit is correct).

So technically this is workable but it's a little strange to watch.

Contract:
https://github.com/severedsolo/KerbalAcademy/blob/master/KerbalAcademyBootCamp.cfg
Necessary craft file: https://github.com/severedsolo/KerbalAcademy/blob/master/Ships/Driller.craft

**Comment by jrossignol** [comment]
I hate quaternions.  I have no idea why you had to pitch your craft 180 degrees, but I had a couple quaternions reversed in an operation that sets the rotation before physics kicks in (once physics kicks in, it's a different rotation that matters, but these things can't be simple).  Anyway, should be just cosmetic, but fixed now.
