### ISSUE TITLE
Enhacement: PartPurchased

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#526]
Currently PartUnlocked seems to only be checking if a part is researched, but not purchased.  A player is forced to purchase parts when they deselect the the pre-game option "No Entry Purchase Required on Research". 

What happens currently is that my requirement check for if a player has a PartUnlocked isn't tripping if someone has researched the part but not yet purchased it. Since the contract I have is intended to sell the part at a discount, it renders the contract from ever being offered to the player in games where "No Entry Purchase Required on Research" is deselected.

PartPurchased would allow us contract mod authors to code for conditions if the part has been neither researched nor purchased the part yet by the player.

Thoughts?

**Comment by jrossignol** [comment]
It's supposed to consider part unlocking, so this sounds like a bug.

**Comment by inigmatus** [comment]
Bug then. Can you test with https://github.com/inigmatus/GAP/blob/master/Economy/SSI-Inigma-CommandSeat.cfg ?  vanilla game.

**Comment by jrossignol** [comment]
Not sure how this one snuck by, I know at one point in time I had it looking at part purchase...  not sure how that got broken.  Oh well, should be good for next release.
