### ISSUE TITLE
Contract Pack "Interplanetary Mountaineer" feature a mission that cannot be completed...

### ISSUE THREAD

**Issue by Galenmacil** [jrossignol/ContractConfigurator#528]
I am reporting this here because I am quite sure the contract CFG file is properly created. The problem is with a particular mission on the Mun that require you to go to both the highest and the lowest point on the moon. The highest part completed successfully but the lowest part pose a problem:

At those particular coordinates defined in the contract, the height of the terrain is below zero: -242 or so meter. The in-game altimeter report just 242 but, when you jump/go up on the surface, the counter decrease instead of increasing as it should be. All other mod altimeter counter report the correct sub-zero value.

In my opinion, the condition for the contract cannot be met correctly even though the distance from the waypoint in waypoint manager is reported correctly. You have to get within 15 meter of it, which I did but still, the indicator for the waypoint did not flash to indicate you are in range. The sub-zero altitude at this point is probably the culprit...

[2MunIPM.txt](https://github.com/jrossignol/ContractConfigurator/files/306191/2MunIPM.txt)

**Comment by Galenmacil** [comment]
I tested the following and the contract completed:

1 - I edited the contract file and replaced, for the Mun_BE section, the waypoint distance from 15 to 150000.

2 - Back in the game, the waypoint appeared above the ground at altitude level 0 but I still did not receive a message telling I was nearby. I was right under it at an altitude around -225m standing next to the initial flag I planted there without success.

3 - I turned on the EVA pack and progressed directly upward to the navpoint. Once I reached it at around 0m altitude, the contract completed successfully.

**Comment by jrossignol** [comment]
I won't have access to KSP for about another week and a half so I can't reproduce this one for a while.  In the meantime, can you try leaving the altitude out of the WaypointGenerator completely?  It could be that the documentation is wrong and it's not defaulting the altitude correctly.

**Comment by jrossignol** [comment]
Fixed for next release.
