### ISSUE TITLE
Allow partModuleType in PartValidation (enhancement)

### ISSUE THREAD

**Issue by pap1723** [jrossignol/ContractConfigurator#530]
This would make it easier for people having to use a ton of extra logic in the writing of the code.
Thanks!

**Comment by jrossignol** [comment]
Done for next release.

**Comment by jrossignol** [comment]
@pap1723 - Just so you know the policy on enhancements, my expectation is that you continue your contract pack development from the dev version of Contract Configurator (https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true).  That way, you're not waiting on me to release it to continue development, and I'm not forced into releasing too frequent changes to support contract authors.

If you're ready to release and are relying on changes that exist only in the development branch, then just ping me and I'll do a release (within 24 hours, unless I'm out of town).  But usually I release frequently enough that it isn't an issue.

**Comment by pap1723** [comment]
@jrossignol I REALLY appreciate your constant support and consistent upgrades and responses to issues that modders and myself in particular have had. You are a great asset to the community. I very much appreciate your help in all aspects of Contracts.

**Comment by pap1723** [comment]
Just ran into an error using the newest build of the .DLL in trying to use the new functionality you built in:
`[ERR 17:09:25.350] ContractConfigurator.PartValidationFactory: CONTRACT_TYPE 'Sputnik-1', PARAMETER 'HasAntenna' of type 'PartValidation': A validation error occured while loading the key 'partModuleType' with value 'System.Collections.Generic.List`1[System.String]'.

[EXC 17:09:25.351] ArgumentException: No PartModules found for type 'Antenna'.
	ContractConfigurator.Validation.ValidatePartModuleType (System.String name)
	System.Linq.Enumerable.All[String] (IEnumerable`1 source, System.Func`2 predicate)
	ContractConfigurator.PartValidationFactory+<>c.<Load>b__3_8 (System.Collections.Generic.List`1 x)
	ContractConfigurator.ConfigNodeUtil.ParseValue[List`1] (.ConfigNode configNode, System.String key, System.Action`1 setter, IContractConfiguratorFactory obj, System.Collections.Generic.List`1 defaultValue, System.Func`2 validation)
	UnityEngine.Debug:LogException(Exception)
	ContractConfigurator.LoggingUtil:LogException(Exception)
	ContractConfigurator.ConfigNodeUtil:ParseValue(ConfigNode, String, Action`1, IContractConfiguratorFactory, List`1, Func`2)
	ContractConfigurator.PartValidationFactory:Load(ConfigNode)
	ContractConfigurator.ParameterFactory:GenerateParameterFactory(ConfigNode, ContractType, ParameterFactory&, ParameterFactory)
	ContractConfigurator.ParameterFactory:GenerateParameterFactory(ConfigNode, ContractType, ParameterFactory&, ParameterFactory)
	ContractConfigurator.ContractType:Load(ConfigNode)
	ContractConfigurator.<LoadContractConfig>d__26:MoveNext()
	ContractConfigurator.ContractConfigurator:Update()`

The parameter that I used:
PARAMETER
	{
		name = HasAntenna
		type = PartValidation
		partModuleType = Antenna
		minCount = 1
	}

It is very possible I did something wrong.

**Comment by jrossignol** [comment]
Gotta run to pick up my kids, so will look at this tonight.

The only thing that could be wrong on your side is if you have a messed up stock GameData/Squad/Contract/Contracts.cfg.  Can you double check that (if you're on steam, do a game validation).

**Comment by jrossignol** [comment]
Whoops, I was checking with Wheel, which had some logic that made it an exception.  Works for all documented cases now.

**Comment by pap1723** [comment]
You are the man! I will test later today.
