### ISSUE TITLE
Duplicate and unarchievable contracts

### ISSUE THREAD

**Issue by raycar5** [jrossignol/ContractConfigurator#532]
The 18 km contract shows duplicated a bunch of times in contract window + and I'm not able to complete it, here's a log:
http://pastebin.com/Kgwi9Dim
(pretty long log, search for _[Altitude18km]_ to see when the contracts get created)

**Comment by jrossignol** [comment]
More than likely an issue with the contract pack in question. On mobile so I can't really check - where is the contract from?

**Comment by raycar5** [comment]
I think it's from seti-contracts

**Comment by jrossignol** [comment]
I think what's happening is that you have either Cryonic Engines or Kerbal Atomics.  The version released today have some extra files.  Nertea is aware of the problem so it should be fixed soon.

Let me know whether I'm right or not, as I wasn't able to confirm for certain from the portion of the logs that you send.

**Comment by raycar5** [comment]
Yes, I have both installed

**Comment by raycar5** [comment]
It works thanks :)
