### ISSUE TITLE
1.15.1 experimental: Exception occured while loading ScenarioModule 'ContractPreLoader': System.ArgumentException: Missing required value 'contract'.

### ISSUE THREAD

**Issue by Y3mo** [jrossignol/ContractConfigurator#533]
Exception occured while loading ScenarioModule 'ContractPreLoader':
System.ArgumentException: Missing required value 'contract'.
  at ContractConfigurator.ConfigNodeUtil.ParseValue[List`1] (.ConfigNode configNode, System.String key, Boolean allowExpression) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractPreLoader.OnLoad (.ConfigNode node) [0x00000] in <filename unknown>:0 

Mods:
Just Contract Configurator 1.15.1

Situation: After scene change of launching first vessel (from VAB to launch pad)

[KSP-log.zip](https://github.com/jrossignol/ContractConfigurator/files/357977/KSP-log.zip)

**Comment by jrossignol** [comment]
Drat, that's annoying.  I'll fix the code, but not sure when I'll be able to actually get it released.  At the very least, the only impact of this is that you may lose _offered_ contracts (anything active is safe).  So other than the nuisance factor it's not too terribble.

**Comment by jrossignol** [comment]
Actually, let me leave this one open so others see it.
