### ISSUE TITLE
Resource Consumption Parameter

### ISSUE THREAD

**Issue by hargn** [jrossignol/ContractConfigurator#534]
A new contract parameter would be welcome to add a new contract objective on a resource consumption rate.
For example, the objective for a contract I want to write is to check if the power storage is growing due to the solar panels.

I think, the flow rate should be mesured in unit/s, and then the value to set would be positive for a growing resource storage and negative for a decreasing storage.

To be able to set a range [min, max] for this rate would be a plus.

**Comment by jrossignol** [comment]
The parameter will have the following attributes (need to confirm the keys to make sure they are consistent with other parameters):
* resource
* minRate (optional)
* maxRate (optional)

The rates should be in the range (-∞, ∞) with reasonable defaults to account for positive/negative resource consumption.

I'll need to confirm what's available, but more than likely will need to sample over several ticks to calculate (and possibly average) the consumption).  May need to account for (ie. discard) sudden spikes from docking/undocking/decoupling.

Need to validate that it works with both loaded and unloaded vessels.

**Comment by hargn** [comment]
OK, do you plan to integer it into the next release (1.16.x) ?
Else I also can work on it, but I need to set the ksp dev environment that I never did before.

**Comment by jrossignol** [comment]
I'll likely look at this for 1.15.2.  I'm travelling this week, so I may not be able to get to it until the weekend.

**Comment by hargn** [comment]
OK, I'm leaving on vacation too for the next 10 days so I'll probably not work during this period

**Comment by jrossignol** [comment]
Completed for next release.
