### ISSUE TITLE
Enhancement: Allow Waypoints to be generated in specific biomes

### ISSUE THREAD

**Issue by pap1723** [jrossignol/ContractConfigurator#535]
Hey Nightingale,
I am looking for a feature to create a Random Waypoint in a specific biome. It seems like a lot of the functionality is there so it might be an easy implementation?

Thanks,
Pap

**Comment by jrossignol** [comment]
It's possible, but generating a random waypoint for a specific biome isn't easy.  I'd have to generate a waypoint, check the biome and discard if it's not the right one, which could be performance intensive.

Is it not possible to generate a random waypoint and then use the biome of the waypoint?  In other words, do you need it to be biome => waypoint and not waypoint => biome?

**Comment by jrossignol** [comment]
Just FYI - I'll need a response before I action anything on this issue.

**Comment by pap1723** [comment]
I understand the limitations that you are saying. It is not that important of an issue to implement. If it was really easy then no problem, but it isn't worth the possible performance hit.

Thanks for looking into it.
