### ISSUE TITLE
Allow PARAMETER to check for staging

### ISSUE THREAD

**Issue by Zarbizaure** [jrossignol/ContractConfigurator#536]
I tried to create a simple SSTO contract but this mean I'll have to check for any staging event (or to compare the part count on the runway and in orbit).

Could you add a staging parameter check? Or is there another way to check if any part of the vessel has been decoupled or if the part count has been lowered? Could DATA nodes be children of PARAMETER nodes?

**Comment by jrossignol** [comment]
No to DATA nodes being a child of a PARAMETER.

I can look at a parameter that fails the contract if a decoupling/undocking happens.

**Comment by jrossignol** [comment]
Added a new [NoStaging](https://github.com/jrossignol/ContractConfigurator/wiki/NoStaging-Parameter) parameter for the next release.
