### ISSUE TITLE
Rewarding experience for completing contracts/optional parameters

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#54]
Just got the idea. Don't know this could work. Would be nice!

**Comment by jrossignol** [comment]
Relevant comment from @magico13:

> As for giving Kerbals XP, it's not as trivial as it should be. Take a look at [Field Experience](http://forum.kerbalspaceprogram.com/threads/107663-Magico13-s-Modlets?p=1676818) (source is in download, sorry) to see how I handle automatic leveling. XP is tied directly into the Flight Log and is recalculated every time the game is loaded, so whatever XP you give you'll have to keep giving every time the save is loaded. MKS/OKS has an "Academy" or something like that that might do something different but my guess is that it writes a "simulated" flight log based on the "instructor" Kerbal's Career Log.

I don't like the idea of having to have another scenario module to just keep re-rewarding XP, although that may be necessary.  I'll have to see if it's possible to add some fake info to the flight log, but since I'd imagine both the CelestialBody and the situation need to validate against their respective lists of values that isn't actually possible.

**Comment by jrossignol** [comment]
Done for 1.6.0

**Comment by magico13** [comment]
Interesting. So it looks like you're creating a custom entry in the flight log, and are somehow setting the amount of experience you get for it. I may end up finding some use for that method myself later on down the line.

**Comment by jrossignol** [comment]
Yup....  hack doesn't begin to describe this one, but it seemed to work well.  It used to be the flight log would crash and burn if there was invalid entries (thinking of the scenario where Contract Configurator is uninstalled), but it seems to just silently drop them instead in 1.0.

**Comment by magico13** [comment]
> it seems to just silently drop them instead in 1.0

Now if only the rest of the Contract system did that when it encountered something wrong ;)

**Comment by jrossignol** [comment]
Indeed...  you should see how much exception handling code I've inserted into Contract Configurator to prevent that as best as possible...
