### ISSUE TITLE
1.15.x Behavior Enhancement

### ISSUE THREAD

**Issue by Whitecat106** [jrossignol/ContractConfigurator#541]
Hello again! 
I have been working on making my pack compatible with the upcoming CC version, almost finished but I was wondering if you would be able to include some small additions to the Behavior function to allow for my pack to have a few 'settings' contracts.
 My aim is to reduce the number of files I have to redistribute each time for players, for instance many people request that I produce an American/Russian missions only component of HM or only missions from a certain point (Space Shuttle era/ Apollo etc), this would also make for some more interesting variations in the way contracts can be presented.

I have a plan of automatically completing certain prerequisite contracts and disabling others  when the user accepts a certain settings contract, for example accepting an 'American missions only' contract would automatically complete any predefined interlocked american/russian missions (where a russian mission is required to be completed before an american mission is unlocked), and subsequently disable any other predefined russian mission. To do this I would require a behavior such as:

```
ParameterComplete / Contract Accepted
{
    Parameter = blah

    CompleteContract 
    {
        contractType = blahblah
    }

    DisableContract     // Which I believe exists to some extent in the ContractConfigurator{} miscellaneous function but I am unsure how this would interact within a behavior. 
    {
        contractType = blahblahblah 
    }
}
```

It would also be useful to have a function such as:
```
SetFunds
{
    amount = blah
}

SetScience
{
    amount = blah
}

SetRep
{
    amount = blah
} 
```
Since by automatically completing a contract (such as via the alt-f12), the rewards are automatically added and would need to be removed by the start of a new playthough.  If I get some more time I will send a pull request for this! 

Thanks! 
Whitecat106

**Comment by jrossignol** [comment]
This can already be done through the Expression Behaviour/Requirement.  I'd suggest something like this in your "Settings" contract:
```
    BEHAVIOUR
    {
        name = Expression
        type = Expression

        CONTRACT_COMPLETED_SUCCESS
        {
            type = bool
            HM_AmericanMissionsDisabled = true
        }
    }
```
Then in the contract with American missions:
```
REQUIREMENT
{
    type = Expression
    expression = bool($HM_AmericanMissionsDisabled) == false
    title = American Missions must be enabled
}
```
If you want to use that to fast-forward progression (eg. either complete the last American mission or disable them to access something like STS), you could do :
```
REQUIREMENT
{
    type = Any

    REQUIREMENT
    {
        type = CompleteContract
        <...>
    }

    REQUIREMENT
    {
        type = Expression
        expression = bool($HM_AmericanMissionsDisabled) == true
        title = American Missions must be disabled
    }
}
```

Of course, I think this may be uncessary with the changes in 1.15.x.  If people are asking to only play through specific mission sets, I think their issue is the other mission sets are clogging up the list in Mission Control.  Having it in separate child groups means that it's very easy for a player to ignore the ones they don't want to play.

If you do use the above method, keep in mind that the default value for a bool is false (which is why I have it as explicitly disabled instead of explicitly enabled.

**Comment by Whitecat106** [comment]
I did not realise so much could be done with the Expression system already! Thanks for the info; really useful! :) I will try this out and see what I can come up with!

**Comment by Whitecat106** [comment]
Hi again @jrossignol , 
I followed the method you described and it had the desired effect! Thanks for that! 

I then decided to try extending the behavior function myself to see if this could be a little quicker (since the method above requires me to change a lot of contracts). I have tried to extend the Behaviour function but to no avail, with the CC debug menu stating 'Unknown Behaviour: 'CompleteContract'', I followed the instructions on the wiki but it doesn't look like CC recognizes my new behaviour, here is my code: 

> 
 `
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using KSP.IO;

using Contracts;
using ContractConfigurator;
using ContractConfigurator.Parameters;
using ContractConfigurator.ExpressionParser;

namespace WhitecatIndustries
{
    public class HMBehaviorExtensions : BehaviourFactory
    {
        public override bool Load(ConfigNode configNode)
        {
            bool valid = base.Load(configNode);

            configNode.AddValue("contractType", "");
            
            return valid;
        }

        public override ContractBehaviour Generate(ConfiguredContract contract)
        {
            return new CompleteContract();
        }
    }

    public class CompleteContract : ContractBehaviour
    {
        ConfigNode node = new ConfigNode();

        protected override void OnAccepted()
        {
            base.OnAccepted();

            double FundsInitial = (Funding.Instance.Funds);
            float RepInitial = Reputation.Instance.reputation;
            float SciInitial = ResearchAndDevelopment.Instance.Science;

            Contracts.Contract HMContract = new Contracts.Contract();

            foreach (Contracts.Contract contract in Contracts.ContractSystem.Instance.Contracts)
            {
                if (contract.Title == node.GetValue("contractType"))
                {
                    HMContract.Complete();
                }
            }

            double NewFunds = Funding.Instance.Funds;
            float NewRep = Reputation.Instance.reputation;
            float NewSci = ResearchAndDevelopment.Instance.Science;

            Funding.Instance.AddFunds(-(NewFunds - FundsInitial), TransactionReasons.Progression); // Reset funds etc. 
            Reputation.Instance.AddReputation(-(NewRep - RepInitial), TransactionReasons.Progression);
            ResearchAndDevelopment.Instance.AddScience(-(NewSci - SciInitial), TransactionReasons.Progression);
        }

        protected override void OnLoad(ConfigNode configNode)
        {
            base.OnLoad(configNode);
            node = configNode; 
        }

        protected override void OnSave(ConfigNode configNode) 
        {
            base.OnSave(configNode);
        }
    }
}
`
<

Might just be me being dumb but I would be grateful if you could take a look! Cheers, 
Whitecat :)

**Comment by jrossignol** [comment]
Sorry I missed this originally because of the closed issue. :cry: 

Anyway, the behaviour name comes from the factory (it's the same name as the factory, but with the Factory removed from the end if present).  So you'd need to use the name 'HMBehaviorExtensions' in your config (or rename the factory class to CompleteContractFactory).  That being said, I don't have any namespacing logic in the cfg load code, so could you use a name like HM_CompleteContractFactory instead?  Just in case I end up with a similarly named behaviour in the future.  Also helps people looking at your config to realize why the behaviour isn't documented in my stuff.

**Comment by Whitecat106** [comment]
Ahh no worries! Thanks for the reply! Fixed my issue with that, should have HM out in the next few hours! :)
