### ISSUE TITLE
Mission Control Limits are being ignored.

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#543]
I reported this a while back, but is still present in the release:

It is possible to select more contracts than you should be "allowed" to in Mission Control. To reproduce: start a new Career, and accept all the World FIrst contracts. You should only be able to select 2, but you can select all.

On exiting/reentering Mission Control, the contracts are correctly locked from any more being accepted.

**Comment by jrossignol** [comment]
Whoops, I knew there was something I forgot...  I'll get that for this next release.
