### ISSUE TITLE
Error log spam for lack of ResearchBodies

### ISSUE THREAD

**Issue by KSAMissionCtrl** [jrossignol/ContractConfigurator#549]
This shows up in my log once a second with the latest version of CC:

`[ERR 16:08:11.924] ContractConfigurator.Util.Version: Couldn't find assembly for 'ResearchBodies'!`

It's correct at least - I don't have ResearchBodies installed so it indeed cannot be found :)

**Comment by jrossignol** [comment]
Fixed in latest release.
