### ISSUE TITLE
Kolniya orbits generated sometimes have Ap outside planet's SOI

### ISSUE THREAD

**Issue by linuxgurugamer** [jrossignol/ContractConfigurator#554]
I've had reports that contracts are being generated for Kolniya orbits which have the Ap outside the planet's SOI, which obviously means it can't be finished since once the vessel leaves the SOI, it won't return.
This is the code doing the generating (copied from current version of UnmannedContracts):
```
        BEHAVIOUR
        {
                name = EquatorialOrbitGenerator
                type = OrbitGenerator

                RANDOM_ORBIT
                {
                        targetBody = @/targetBody
                        type = KOLNIYA
                        // difficulty = 1
                }
        }
```

**Comment by jrossignol** [comment]
Fixed for next release, will post more details in the forum thread.
