### ISSUE TITLE
Add partModule and partModuleType to TechResearched requirement

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#555]
Report from Waz here: http://forum.kerbalspaceprogram.com/index.php?/topic/102390-113-contract-pack-bases-and-stations-34-060816-formerly-kerbin-space-station/&page=28#comment-2713908

Basically, looks like the xUnlocked requirements need the part to be purchased (and thus available in the VAB too). Would like a new flag such as mustBePurchased = false; so it can be offered even if the part is just unlocked in R&D but not bought

**Comment by jrossignol** [comment]
By definition, the part must be purchased for these.  If you want to check the tech, then you should use [TechResearched](https://github.com/jrossignol/ContractConfigurator/wiki/TechResearched-Requirement).

However, that only supports checking by techID or part - not partModule or partModuleType.  So I can add those there to meet this request.

**Comment by severedsolo** [comment]
That will be fine, cheers.

**Comment by jrossignol** [comment]
Done for next release.
