### ISSUE TITLE
Mass constraint for the HasResource parameter

### ISSUE THREAD

**Issue by hargn** [jrossignol/ContractConfigurator#556]
If available for the specified resource (not for the ElectricCharge eg.), enhance the HasResource parameter to specify the minimum or maximum resource mass instead the quantity to respect the contract's clause.
This is an example :
```
PARAMETER
{
   name = HasHydrazine
   type = HasResource
   resource = Hydrazine
   minMass = 500   // For the unit, always in kg, or the parser can allow to specify it like this : 500kg, 0.5t, ...
   maxMass = 1000
}
```
This enhancement may be added to the HasResourceCapacity too, I think.

**Comment by jrossignol** [comment]
Fixed via bbbdc5c.

Instead of adding a min/max mass (it's confusing to the player, as resource mass isn't displayed in an obvious way), I've added a density function.  So you can achieve the above this way:
```
PARAMETER
{
   name = HasHydrazine
   type = HasResource
   resource = Hydrazine
    minQuantity = 500 / @resource.Density()
    maxQuantity = 1000.0 / @resource.Density()
}
```
