### ISSUE TITLE
HasCrewCapacity fails contract completely if vessels meet all other parameters.

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#559]
Raised by tomf on the forums:

The affected contract is  [BaseCreate](https://github.com/severedsolo/KerbinSpaceStation/blob/master/Core%20Missions/BaseCreate.cfg), but I've got a few others that may be affected too.

So it looks like if the player switches to a vessel which meets all the other requirements (or is in physics range of a vessel that does) - but doesn't have enough Crew Capacity, the contract will fail instead of just marking it as unmet.

**Comment by jrossignol** [comment]
Can you provide more steps to reproduce?  I've got a hacked down version of base create, and I'm not able to reproduce.  What I've done is is put a stack of 4 mk1 pods on, eva'd a Kerbal and just swapped between the two vessels.  The crewCapacity = 4 parameter gets an x or checkmark correctly based on which vessel is selected, but I've yet to get it to fail the contract.

**Comment by tomforwood** [comment]
To reproduce -  load the attached save file, click rename on testBase and change it's craft type to Base. The build a base contract is instantly failed

[testfail.zip](https://github.com/jrossignol/ContractConfigurator/files/439383/testfail.zip)
