### ISSUE TITLE
Max Completions = 0 prevents other contracts in same group from generating

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#560]
A critical bug.

Take any group of contracts, all with same requirements, and max completions = 0, the first listed contract in Mission Control will be the only contract that ever generates. 

Setting max completion to something other than 0 simply causes the next sorted contract to be offered forever until it too has its max completion changed greater than 0.

**Comment by jrossignol** [comment]
Can you provide a config that shows this behaviour?

**Comment by inigmatus** [comment]
Here is my persistence file.
You can install the dev version of GAP from here: https://github.com/inigmatus/GAP/archive/master.zip

[persistent.zip](https://github.com/jrossignol/ContractConfigurator/files/435279/persistent.zip)

try to get any other Charter flight to generate except Flight 4.  Also anything but buoy contract in KSC Coast Guard.  All repeatable (max completions = 0) contracts in GAP are only loading the first sorted contract on contract generation and not allowing any others to generate instead.

**Comment by jrossignol** [comment]
You have maxSimultaneous set to 1 for those groups - so it will only offer one contract.  What I can do is make that requirement more clear (so there's a line item for it), but still offer more than 1 (and the others will immediately be withdrawn when you select the one that you want active).

**Comment by inigmatus** [comment]
I am not sure i understand. 

I only want one contract in the group to be active at any one time.

But each contract should be offered randomly, and not always the same contract, when max completions is set to 0 for multiple contracts in the same group (and all requirements for those contracts all being equal).

**Comment by jrossignol** [comment]
Okay - based on that I decide to go with just changing the generator to step through stuff in a random order.  You'll only get one offered, but it'll which one will be random.

**Comment by inigmatus** [comment]
Tested with your updated dll. 

Charter Flight 4 is all that remains offered. Even after cancelling it multiple times. 

Charter Flights 45 or 5 never get generated still: 

https://www.dropbox.com/s/mgobqt4x28iw70b/Screenshot%202016-08-25%2017.45.25.png?dl=0

**Comment by jrossignol** [comment]
Nope, working correctly.  When you decline a contract, it's the first one back in the list to get a chance to generate.  In this scenario, it prevents a player from just declining to get the contract they want (because if that's the behaviour you want to see, then I might as well just make them all offered like I was intending).

Try instead accepting it and force completing - you should see a new one get generated in that instance (or at least, a 2/3 change of a different one).

**Comment by inigmatus** [comment]
It's working correctly. I think I understand now. I was cancelling the contract in my testing before accepting it, but I assume CC is still working off the list in that instance, and doesn't generate a randomly different contract to prevent slot machining contracts. Instead to prove it works I had to accept the contract, and then decline, which forces CC to generate a new offering. I was able to get other contracts to randomly generate as a result.

You can close this as resolved.
