### ISSUE TITLE
Unexpected exception after upgrading from 1.17.0

### ISSUE THREAD

**Issue by CecilFF4** [jrossignol/ContractConfigurator#562]
While on 1.17.0, my career ran just fine (KSP v1.1.3). After upgrading, I got an exception error. It was reproducible (just loading my save did it) and crashed my game half the time. I've attached the crash report, a picture of the exception, and my current save file. The list of mods I use are in the favs.ckan file as well. Pretty much all files had .txt appended to get them to upload.

[favs.ckan.txt](https://github.com/jrossignol/ContractConfigurator/files/440413/favs.ckan.txt)
[persistent.sfs.txt](https://github.com/jrossignol/ContractConfigurator/files/440412/persistent.sfs.txt)
[crash.dmp.txt](https://github.com/jrossignol/ContractConfigurator/files/440410/crash.dmp.txt)
[error.log.txt](https://github.com/jrossignol/ContractConfigurator/files/440411/error.log.txt)
![error](https://cloud.githubusercontent.com/assets/12663305/18024421/588eba36-6bcf-11e6-89f3-1b2833a35f2d.png)
[output_log.txt](https://github.com/jrossignol/ContractConfigurator/files/440409/output_log.txt)

**Comment by jrossignol** [comment]
Kind of a scary one - the crash doesn't point to anything Contract Configurator related, although the timing makes it obviously suspect.

I've got a guess as to the cause of the exception, although I wasn't able to reproduce with your save.  Can you try the dev dll [here](https://github.com/jrossignol/ContractConfigurator/blob/master/GameData/ContractConfigurator/ContractConfigurator.dll?raw=true) and let me know if that one works for you?

**Comment by CecilFF4** [comment]
Not sure what you did, but that DLL cured things right up. I've been testing and can't reproduce that error any more.

**Comment by jrossignol** [comment]
Still not confident that the crash is fixed, as I don't really think it was related, but I'll assume all is good here and release the fix.
