### ISSUE TITLE
Duration parameter does not count or end in Space Center screen

### ISSUE THREAD

**Issue by 5thHorseman** [jrossignol/ContractConfigurator#567]
This may affect all timer parameters, or even all parameters though some of them can't be completed in the Space Center screen. Also, this may affect all screens (Such as the Tracking Station).

If you set up a Duration parameter, accept the contract, and then sit on the space center screen, the timer stays at the maximum time. It does not count down.

If you set the timer for 0s, it does not auto complete, it just sits stating that there are 0:00:00 left in the timer.

As soon as you control a vessel, the timer counts down as normal.

**Comment by 5thHorseman** [comment]
In a perfect world, I'd like it if setting the timer for 0s would auto-complete even in Mission Control where time does not seem to pass in-game.

**Comment by severedsolo** [comment]
I'm seeing this on Duration too - but it seems to correctly account for the passed time when you jump to a scene where it does work (like in flight)

For example - I did the Tito tourism contract, and jumped back to the space centre for 3h 30m - then I came back to Titos craft, the duration said I only had 30 minutes to do (but before the scene change, it was saying 4 hours).

**Comment by jrossignol** [comment]
Fixed for next release.

**Comment by 5thHorseman** [comment]
Not sure if this needs opened again or if it's just not possible, but while this fix does allow 0s durations to complete in the Space Center scene, they do not complete in mission control. If that is not possible, no problem. I just wanted to make sure you didn't expect it to work and it doesn't.

**Comment by inigmatus** [comment]
Try a 1 second parameter. It works for GAP.

**Comment by 5thHorseman** [comment]
You may have misunderstood. The 0s parameter works ONCE I'VE LEFT MISSION CONTROL but it does not work while still in Mission Control. I just tried 1s and that also does not work until you leave Mission Control.

I understand why this is occurring: In Mission Control time does not pass. I was hoping there was a way for Contract Configurator to realize that a duration of 0s would occur even though no time is passing, and auto-complete the contract right after it was accepted.

**Comment by jrossignol** [comment]
KSP 1.1.3 changed it so that it's paused in mission control, and that's a side effect.  Maybe raise another enhancement and I'll see about making contracts work with no parameters (it might be a stock limitation there, not 100% sure).
