### ISSUE TITLE
NRE in ReachState.CheckBiome

### ISSUE THREAD

**Issue by SamLex** [jrossignol/ContractConfigurator#569]
**Problem**
A NullReferenceException is thrown within _ContractConfigurator.Parameters.ReachState.CheckBiome_ because _Vessel.landedAt_ is null when passed to _Vessel.GetLandedAtString_.

**Situation**
This bug manifested while using the [Extraplanetary-Launchpads](https://github.com/taniwha/Extraplanetary-Launchpads) mod to create a vessel in orbit.

**Log**
Relevant fragment of log file is attached: [nre.txt](https://github.com/jrossignol/ContractConfigurator/files/454849/nre.txt)

**Potential Solution**
Add a null check for _Vessel.landedAt_ at ReachState.cs:220:
`if (vessel.landedAt != null && Vessel.GetLandedAtString(vessel.landedAt) == biome)`

**Alternative**
Extraplanetary-Launchpads should be ensuring that _Vessel.landedAt_ is non-null, even when the vessel is in orbit.

**Comment by jrossignol** [comment]
Fixed for next release, but I'd consider it a EL bug.
