### ISSUE TITLE
[KSP1.2pre] CC Error in latest pre-build

### ISSUE THREAD

**Issue by ajventer** [jrossignol/ContractConfigurator#577]
As of the most recent pre-release build contract configurator seems to have broken. One can no longer accept new contracts, and contracts cannot complete. Problem appears to be using an api call that has been removed.
Log entries:

[EXC 07:07:47.602] ReflectionTypeLoadException: The classes in the module cannot be loaded.
        System.Reflection.Assembly.GetTypes ()
        ContractConfigurator.ContractConfigurator+<GetAllTypes>d__27`1[ContractConfigurator.ParameterFactory].MoveNext ()
        Rethrow as Exception: Error loading types from assembly AnomalySurveyor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
        UnityEngine.Debug:LogException(Exception)
        ContractConfigurator.LoggingUtil:LogException(Exception)
        ContractConfigurator.<GetAllTypes>d__27`1:MoveNext()
        System.Linq.<CreateWhereIterator>c__Iterator1D`1:MoveNext()
        ContractConfigurator.ContractConfigurator:RegisterParameterFactories()
        ContractConfigurator.ContractConfigurator:Update()

[EXC 07:31:51.098] MissingFieldException: Field '.GameEvents.onPartJointBreak' not found.
	ContractConfigurator.Parameters.HasCrewCapacity.OnUnregister ()
	Contracts.ContractParameter.Unregister ()
	Contracts.Contract.Unregister ()
	Contracts.ContractSystem.OnDestroy ()
	UnityEngine.Object:DestroyImmediate(Object)
	ScenarioRunner:OnGameSceneLoadRequested(GameScenes)
	EventData`1:Fire(GameScenes)
	HighLogic:LoadScene(GameScenes)
	KSCPauseMenu:<draw>m__81C()
	DialogGUIButton:OptionSelected()
	DialogGUIButton:<Create>m__6E4()
	UnityEngine.EventSystems.EventSystem:Update()

**Comment by jrossignol** [comment]
This one's already fixed, just needs a release.  I was hoping to get a few
more issues resolved, but haven't had the free time to spend on mods.  Will
hopefully get a release out tomorrow

**Comment by ajventer** [comment]
Oh cool. I'll be happy to wait for a release, was just reporting it in case you didn't know about it yet. I tried building a fix for you myself and sending a pull request but unfortunately your sln file is not compatible with monodevelop on linux as it depends on the windows only copy /y command and I don't know the formatting of sln files well enough to fix that myself :P
Since it's already fixed the point is moot anyway.

**Comment by jrossignol** [comment]
Closing this one out - note though that Anomaly Surveyor hasn't yet been recompiled in 1.2, so that won't work.
