### ISSUE TITLE
[KSP1.2pre] Major bug in new release

### ISSUE THREAD

**Issue by ajventer** [jrossignol/ContractConfigurator#578]
Strange bug which magically unlocks all tech tree nodes, upgrades every building to max level and then causes complete save file corruption.
Log entries:
[LOG 21:39:47.734] [GenericAppFrame] Reposition 8.872499 7908
[EXC 21:39:47.735] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ContractsApp.CreateContractsList ()
	System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
	Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
	System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
	System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
	ContractConfigurator.WiderContractsApp.OnPreCull ()

**Comment by ajventer** [comment]
I did some more testing. I used an install with no other mods in it (to rule out a bad interaction with another mod) - and the problem still happened. So I started stripping down on settings changes from default. 
I managed to determine that the problem only happens if you disable some stock contracts. If you leave them all enabled - then the problem does not occur. And this allowed me to get another relevant log message:

[LOG 06:55:59.592] [UIMasterController]: ShowUI
[EXC 06:56:03.328] NullReferenceException: Object reference not set to an instance of an object
	ContractConfigurator.ContractDisabler.SetContractState (System.Type contractType, Boolean enabled)
	ContractConfigurator.StockContractParametersTemplate.OnLoad (.ConfigNode node)
	GameParameters+ParameterNode.Load (.ConfigNode node)
	GameParameters.LoadCustomNode (.ConfigNode node)
	GameParameters.Load (.ConfigNode node)
	GameParameters..ctor (.ConfigNode node)
	Game..ctor (.ConfigNode root)
	GamePersistence.LoadGameCfg (.ConfigNode node, System.String saveName, Boolean nullIfIncompatible, Boolean suppressIncompatibleMessage)
	GamePersistence.LoadGame (System.String filename, System.String saveFolder, Boolean nullIfIncompatible, Boolean suppressIncompatibleMessage)
	SpaceCenterMain+
                         .MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
[WRN 06:56:03.346] [UiApp] Awake: ContractsApp
[WRN 06:56:03.346] [UiApp] Awake: KSPedia

**Comment by jrossignol** [comment]
Fixed for next release.
