### ISSUE TITLE
There are `canHaveKolniya`, but not `canHaveSynchronous`?

### ISSUE THREAD

**Issue by luiges90** [jrossignol/ContractConfigurator#581]
I was reading this page https://github.com/jrossignol/ContractConfigurator/wiki/CelestialBody-Type and found that that are `CanHaveKolniyaOrbit` and `CanHaveTundraOrbit` but not `CanHaveSynchronousOrbit`, despite the latter is also potentially useful (esp. for moons)

**Comment by jrossignol** [comment]
It's a stock thing - those are hooks into the stock methods.  Basically, the CanHaveSynchronousOrbit doesn't exist because in the stock solar system there are no bodies that can't have a synchronous orbit (at least, I *think* that is the case, but seriously wondering if that is true for Gilly...)

**Comment by jrossignol** [comment]
Oh yeah, definitely possible on Gilly, just verified.  If you're able to find a body (stock or mod) that cannot support a Synchronous orbit (due to rotating too fast or having too small of an SOI), then I'll reopen this.

**Comment by Kerbas-ad-astra** [comment]
According to the Wiki, Moho, the Mun, Ike, and all the moons of Jool have synchronous orbits outside their SOIs.

**Comment by jrossignol** [comment]
Though I reopened this already.  Will be looked at in a future release.

**Comment by jrossignol** [comment]
Added CelestialBody.CanHaveSynchronousOrbit() to next release.
