### ISSUE TITLE
Expression for available part mass (dry and wet)

### ISSUE THREAD

**Issue by luiges90** [jrossignol/ContractConfigurator#583]
Not sure if I missed anything, but we can't get the Mass of an `AvailablePart`? `@part.Mass()` does not work...

**Comment by jrossignol** [comment]
Doesn't look like it's there right now, can't remember if there was a limitation that made it difficult.  Will look into it once 1.2 work quiets down.

**Comment by jrossignol** [comment]
Added Mass() and MassWet() for next release.
