### ISSUE TITLE
[1.2 PRE] Evacuate Station/Dock with station not working

### ISSUE THREAD

**Issue by SonnyJim** [jrossignol/ContractConfigurator#584]
I've got an evacuate station contract, but it seems the vessel definition is lost/not working:
http://forum.kerbalspaceprogram.com/index.php?/topic/102390-113-contract-pack-bases-and-stations-34-060816-formerly-kerbin-space-station/&do=findComment&comment=2788959

(Save has KER mod installed)
[Evacuate Station not working.zip](https://github.com/jrossignol/ContractConfigurator/files/518299/Evacuate.Station.not.working.zip)

**Comment by jrossignol** [comment]
Fixed for next release.
