### ISSUE TITLE
CC affecting others mods' toolbar functionality and/or UIs

### ISSUE THREAD

**Issue by plague006** [jrossignol/ContractConfigurator#586]
CC's 1.2 dev branch (using https://github.com/jrossignol/ContractConfigurator/commit/98d4b639f8e05f73b50aa24a4217eb82c4849720) seems to create issues for other mods and their interactions with toolbars.

Namely several mods' buttons are absent from the toolbars (both stock and blizzy) and some mods' UIs are adversely affected.

Image showing when CC is installed: http://puu.sh/rOoF5/b482f8e1ab.jpg
Image showing when CC is not installed: http://puu.sh/rOp2A/860a50e79b.jpg

Exceptions thrown when CC is installed seem to all be `NotSupportedException: The invoked member is not supported in a dynamic module.` and come from multiple mods including but not limited to: USITools, Kolonization, DockingPortAlignmentIndicator, Tac.FuelBalanceController, HotSpot, PartCommander, AmpYear.

Full logs attached of both with and without CC installed.

Log without CC: https://gist.github.com/plague006/9fa43d8ad759d11e0c8c2cda13a5a16b
Log with CC installed: https://gist.github.com/plague006/7f7a637a82c6d65f36333171e6a0868b

**Comment by jrossignol** [comment]
The issue is with the toolbar wrapper - it's the other mods that need to be updated unfortunately.

See [this post](http://forum.kerbalspaceprogram.com/index.php?/topic/55420-120-toolbar-1713-common-api-for-draggableresizable-buttons-toolbar/&do=findComment&comment=2770188).

**Comment by plague006** [comment]
Thanks for the quick follow-up.
