### ISSUE TITLE
conflicts with docking port alignment indicator

### ISSUE THREAD

**Issue by ksp-psk** [jrossignol/ContractConfigurator#588]
installed 1.20.2 and the docking port alignment indicator icon was not there. uninstalled and the docking port alignment indicator icon came back. thanks for all the work you do!

EDIT: Thanks Dave,
RE: https://github.com/blizzy78/ksp_toolbar/pull/39

**Comment by DavoedM** [comment]
Hi,

I'm seeing the same issue with other mods as well, with both the stock toolbar and Blizzys Toolbar.

Icons appear just fine untill I install contract configurator, then the icons dissapear from both toolbars. Ive attached a couple of screenshots; one with CC installed and one without. I've also attached my log file.

Cheers,
Dave 
![20161022164638_1](https://cloud.githubusercontent.com/assets/23000858/19620663/fb328750-9879-11e6-8554-44722214b5ff.jpg)
![20161022165136_1](https://cloud.githubusercontent.com/assets/23000858/19620664/fb4408c2-9879-11e6-8495-4c5a6db56504.jpg)
[KSP.txt](https://github.com/jrossignol/ContractConfigurator/files/545877/KSP.txt)

**Comment by jrossignol** [comment]
Issue is with DPAI's toolbar compatibility code - please raise issue
against DPAI.
