### ISSUE TITLE
Contracts Under Nested Groups Not Generating

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#591]
From: http://forum.kerbalspaceprogram.com/index.php?/topic/91625-12-contract-configurator-v1202-2016-10-21/&page=149

**Comment by jrossignol** [comment]
Resolved by 8f3b8a0d50b2d2a7dd6f152711074ec97ac7a2e6

**Comment by inigmatus** [comment]
Glad to report that your 500th closed issue is fixed. :)
