### ISSUE TITLE
Feature Request: Expose FinePrint.Utilities.ProgressUtilities.GetNextUnreached

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#594]
I might want this for my next project, and I know you are a busy man so getting the request in early.

I'm assuming that this grabs the "next" body in the progression (so if you've orbited Mun, it would grab you Minmus etc.) - cause that's what I want to use it for.

**Comment by jrossignol** [comment]
Added the following two expressions:

| Function Signature| Description |
| :--- | :--- |
| [`CelestialBody`](CelestialBody-Type) `NextUnreachedBody()` | Returns the next unreached body in a logical progression. |
| [`List`](List-Type)`<`[`CelestialBody`](CelestialBody-Type)`> NextUnreachedBodies(`[`int`](Numeric-Type)` count)` | Returns the next `count` unreached bodies in the logical progression. |
