### ISSUE TITLE
Duration timer issue

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#595]
Reported against Tourism by Mordrehl:

> First Tourism contract on CC and TPlus 1.2 shows up ... but won't complete, the counter for time doesnt' change at all

**Comment by inigmatus** [comment]
i haven't tested, but did you fix this? I was noticing this in GAP too in CC 1.20.3 where the countdown timers are running, but not displaying a countdown.

**Comment by jrossignol** [comment]
Not yet, this is the major outstanding issue to be fixed for the next
release.

**Comment by jrossignol** [comment]
Fixed for next release.
