### ISSUE TITLE
HasAntennaRelay/Transmit Parameters (and related Expressions)

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [jrossignol/ContractConfigurator#597]
As I'm updating my AntennaRange Relays mod to the new stock CommNet system, I'm faced with the prospect of creating part patches for each part mod that adds relay antennas as it updates, which does not appeal to me.  (There were very few part mods that shipped natively with AntennaRange patches back before 1.2.)  Since the only thing that really matters is ensuring that the ship has enough relay antennas with enough range, it would be great if ContractConfigurator had a function or two to handle that.

I'm working on coding this up myself, but I want to pick your brain on style/implementation so I get it right with the first PR.  Currently, I've got two parameters (HasAntennaRelay and HasAntennaTransmit), because KSP stores them separately like that (Vessel.connection.Comm.antennaRelay and Vessel.connection.Comm.antennaTransmit), and while I can't imagine why anyone would want to levy different requirements on them at the same time, who am I to judge?

Their arguments are:
* minAntennaPower (default = 0)
* maxAntennaPower (default = Double.MAX) -- not sure why this would be important, but having a "min" makes me feel like there should be a "max", and I'm sure some bright spark will come up with a contract pack that needs it.

I'm also implementing Vessel.AntennaTransmitPower() and Vessel.AntennaRelayPower() Expressions, so that instead of just counting vessels in orbit and hoping that there's enough antennas on them to make a network, I can add another list filter and count the number of vessels with enough AntennaRelayPower to be useful relays:

```
validRelays = @validVessels.Where(v => v.AntennaRelayPower() >= @/minRelayPower)

[...]

title = Fewer than five relays orbiting the moon(s)
targetBody1 = @validBodies.Where(b => (@validRelays.Where(v => (v.CelestialBody() == b)).Count() < 5)).Random()
```

**Comment by jrossignol** [comment]
Changes look good, this was on my todo list to eventually look at.

Can we combine the HasAntennaRelay  and HasAntennaTransmit into one parameter and just have an enum attribute on it with values of RELAY, TRANSMIT or EITHER?  That gives maximum flexibility (and minimum code duplication).

As for the name, you can use HasAntenna, but that will conflict with the RemoteTech stuff.  I do consider that + CommNet to be mutually exclusive though, so I'm fine with the overload (I just need to add logic to make it actually work properly when RemoteTech is installed).

**Comment by Kerbas-ad-astra** [comment]
I'd hesitated to combine since KSP does seem to treat them as two parallel-ish antennas (and the range combination logic seems a little strange to me -- from experimentation with a craft with a probe core [and INTERNAL antenna], a deployable direct antenna, and a fixed relay dish, the relay only 'counts' for antennaTransmit when the direct antenna is open), but from a contract perspective, I think it does make sense that there should be one parameter for both. I'll make that change and get back to you.

**Comment by jrossignol** [comment]
Hmm... If the EITHER option doesn't make sense from a contract point of
view feel free to leave that bit out (other than working on it a little
with Mike and Nathan, I haven't played with it very much myself .

**Comment by Kerbas-ad-astra** [comment]
Yeah, folks'll just want one or the other, right?  I know that's what I'm after.  (I guess if anyone really did want 'either', they could use an ANY parameter with one of each.)  I'm thinking there will be a 'reqAntennaType' enum that takes RELAY or TRANSMIT.

**Comment by Kerbas-ad-astra** [comment]
Alright, update is in.  HasAntenna, minAntennaPower, maxAntennaPower, antennaType = TRANSMIT or RELAY.  Didn't seem to cause trouble with CCRT, but I don't use RT so that module probably disabled itself.

**Comment by jrossignol** [comment]
PR merged, sorry this took so long.
