### ISSUE TITLE
Exploration contracts can't be disabled

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/ContractConfigurator#600]
Sol Invictus writes:

> Problem is that despite of "exploration" ballot box being unchecked, stock exploration contracts, like "Escape the atmosphere!" and "Orbit Kerbin!", are still appearing alongside their SETI equivalents. It starts happening as soon as I finish first SETI contract (reach 18km unmanned). I believe it has nothing to do with SETI Contracts, and all with how Contract Configurator is dealing with contracts in KSP 1.2.1.

**Comment by severedsolo** [comment]
No problems disabling Exploration contracts here. I would guess they are disabling ExploreBody and not ExplorationContract

**Comment by jrossignol** [comment]
Assuming this is fine, closing.
