### ISSUE TITLE
About the distance of VisitWaypoint

### ISSUE THREAD

**Issue by luiges90** [jrossignol/ContractConfigurator#603]
https://github.com/jrossignol/ContractConfigurator/wiki/VisitWaypoint-Parameter The `distance` field under VisitWaypoint Parameter appears to consider the straight line distance between the vessel and the waypoint, at least if the waypoint is not on the surface. This is different to stock behaviour which considers lateral distance instead.

I would guess both could be useful. The former is actually more suited for survey contracts imo, but latter would definitely useful to recreate "put satellite onto stationary orbit with position above somewhere" contracts in stock. Could we have both distances? 😊

**Comment by jrossignol** [comment]
I'll add a field for horizontal distance (using the stock method, not sure I if that's great circle distance or horizontal with respect to a tangent at the waypoint).

**Comment by jrossignol** [comment]
Added for next release.
