### ISSUE TITLE
Orbit Requirement: checkType throws Error

### ISSUE THREAD

**Issue by luiges90** [jrossignol/ContractConfigurator#604]
both `Manned` and `Unmanned` throws error for this value, contrary to what the wiki says

```
REQUIREMENT
	{
		name = NotOrbit
		type = Orbit
		
		checkType = Manned

                invertRequirement = true
	}
```

---

Looks like `MANNED` and `UNMANNED` works, issue of not using `ignoreCase`? hm... 🤔

**Comment by jrossignol** [comment]
Fixed the wiki, but also made it case insensitive for good measure.
