### ISSUE TITLE
Title and Synopsis cannot start with Identifiers

### ISSUE THREAD

**Issue by luiges90** [jrossignol/ContractConfigurator#606]
i.e. 
`title = @/HaulTestStr @part into the space of @targetBody.` results in error.

But 
`title = .@/HaulTestStr @part into the space of @targetBody.` does work (note the period in front of the title)

**Comment by jrossignol** [comment]
This is a known limitation.  There's two modes of string parsing: strict
and loose.  Starting with a symbol will put it in strict mode.  The
workaround is to use:
title = "@/HaulTestStr @part into the space of @targetBody."
