### ISSUE TITLE
Sun hardcoded in SolarScience.cfg

### ISSUE THREAD

**Issue by SirBriguy** [jrossignol/ContractConfigurator#607]
When using the ContractConfigurator with Galileo's Planet Pack, it throws errors about Sun not being a CelestialBody.

This is coming from the science\SolarScience.cfg where the Sun is hard coded. for GPP it needs to be Ciro or HomeWorld().Parent().

Ideally, it would be nice to have a GlobalFunction that would return the sun's CelestialBody (like Sun() or something). 

I am working on making the SETI contracts more generic and have to spam HomeWorld.Parent() everywhere to get the sun which works fine for many systems, but still is broken for weird systems where the homeworld is not directly orbiting the sun (like New Horizons).

**Comment by severedsolo** [comment]
You could try: AllBodies().Where(b=>b.IsSun()).First() (syntax may be off, doing it from memory)

**Comment by cherrydev** [comment]
Yup, you got here ahead of me. I finally figured out I needed to comment out contracts that that referenced the sun otherwise I get log spam.

**Comment by jrossignol** [comment]
Removed Sun references.
