### ISSUE TITLE
VesselValid requirement doesn't exist

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#608]
When trying to use the VesselValid requirement I get:

ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'ExplorationPlus-DockingSetup',REQUIREMENT 'VesselValid' of type 'VesselValid': Unknown requirement 'VesselValid'.

**Comment by jrossignol** [comment]
Code looks fine at a glance - can you provide the full contract?

**Comment by severedsolo** [comment]
Going to assume user error (probably forgot a brace or something) I just re-created the contract (because I'd already written an expression to get around it) and it loaded this time.
