### ISSUE TITLE
Some bugs in Parameters

### ISSUE THREAD

**Issue by Keniamin** [jrossignol/ContractConfigurator#620]
Hello!

I've reported one bug in this post at KSP forum:
http://forum.kerbalspaceprogram.com/index.php?/topic/133545-12x-kerbin-side-gap/&do=findComment&comment=2929317
I mentioned you there, but decided to make an "official" issue here to track bug state.

Also it seems that VisitWaypoint parameter now ignores "distance" value. I'm not very familiar with C#, but looked through your last commits and I think the problem is here:
https://github.com/jrossignol/ContractConfigurator/commit/20d2196748073418fd941ae97a7a9f5f37d449eb#diff-a73fe8233ce005907376be98d340ec3cR32
You're parsing "horizontalDistance" after normal "distance" and uses "x => distance = x", so when there is no "horizontalDistance" normal one is replaced with default 0.

**Comment by jrossignol** [comment]
Fixed for next release.
