### ISSUE TITLE
Contracts with no parameters still try to generate

### ISSUE THREAD

**Issue by severedsolo** [jrossignol/ContractConfigurator#621]
An example contract where this can happen (not 100%):
https://github.com/severedsolo/ExplorationPlus/blob/master/ExplorationPlus-MoppingUp.cfg

Where a contracts parameters all have requirements, if all of those requirements validate as false occasionally the contract will still generate with no parameters, but can't be completed.

**Comment by jrossignol** [comment]
Good catch, fixed for next release.
