### ISSUE TITLE
Enhancement: Get the Delta-v of a Vessel

### ISSUE THREAD

**Issue by pap1723** [jrossignol/ContractConfigurator#627]
Hi @jrossignol !

I have redesigned all of the contracts from RP-0 for Realism Overhaul and an interesting contract idea was to move an existing Geostationary Satellite into a Graveyard Orbit and to replace it with a different satellite.

The issue I have come across is that there are so many different types of fuels that are used in RO, it is not realistic to check for a certain amount of LFO or MP like in stock and divide by the Mass of the craft. Would it be possible to add a check to return the Delta-v of a vessel?

Thanks!

**Comment by jrossignol** [comment]
Getting the Delta-v is very far from trivial for any vessel with more than
one stage, so this enhancement is very unlikely.  The only way to do it
(short of d-v getting added to stock) would be to have a hard dependency on
KER or MechJeb (even then, the integration requires a bit of sworn).

**Comment by pap1723** [comment]
OK, that makes sense is what I expected the answer to be. Good to hear from you!
