### ISSUE TITLE
partModuleType = Power never passes as true

### ISSUE THREAD

**Issue by muppet9876** [jrossignol/ContractConfigurator#629]
"partModuleType = Generator" has replaced "partModuleType = Power". See 

https://kerbalspaceprogram.com/api/class_fine_print_1_1_contract_defs.html

You may want to update 

https://github.com/jrossignol/ContractConfigurator/wiki/PartModuleTypeUnlocked-Requirement

with the above link, "Values (defined in Squad/Contracts/Contracts.cfg under MODULE_DEFINITIONS)" is now incorrect. There are only SURVEY_DEFINITIONS in that file currently.

**Comment by jrossignol** [comment]
Fixed the documentation, added an error in the code for using the old value.
