### ISSUE TITLE
Rendezvous Completing on EVA

### ISSUE THREAD

**Issue by pap1723** [jrossignol/ContractConfigurator#630]
Hey @jrossignol 
As per our exchange through PM, the contract completes when the player EVA's a Kerbal counting as a rendezvous. Thanks!

        PARAMETER
	{
		name = Rendezvous
		type = VesselParameterGroup
		title = First Rendezvous
		define = Rendezvous

		PARAMETER
		{
			name = NewVessel
			type = NewVessel
			title = Launch a New Vessel
			hideChildren = true
		}
		PARAMETER
		{
			name = HasCrew
			type = HasCrew
			minCrew = 1
			maxCrew = 99
			title = Have at least 1 crewmember on board
			hideChildren = true
		}
		PARAMETER
		{
			name = Orbit
			type = Orbit
			minPeA = @targetBody.AtmosphereAltitude()
			title = Orbit @targetBody
			disableOnStateChange = true
			hideChildren = true
		}
		PARAMETER
		{
			name = Rendezvous
			type = Rendezvous
			distance = 100
			title = Rendezvous two craft in Orbit
			hideChildren = true
			disableOnStateChange = true
		}
		PARAMETER
		{
			name = ReturnHome
			type = ReturnHome
			targetBody = HomeWorld()
			title = Return Home Safely
			hideChildren = true
			completeInSequence = true
		}
	}

**Comment by jrossignol** [comment]
Fixed for next release.
