### ISSUE TITLE
Many contracts completely broken in 1.23.2 (work on 1.23)

### ISSUE THREAD

**Issue by ElimGarak** [jrossignol/ContractConfigurator#636]
Something is hosed in the latest configurator version.  Most contracts are missing, although some show up randomly, flickering in and out.  RemoteTech works if I downgrade to 1.23.0, but only two contracts show up if I am on 1.23.2.  The ksp.log is showing tons of configurator errors when parsing the remote tech contracts.

Attached ksp.log file.

[KSP.log.txt](https://github.com/jrossignol/ContractConfigurator/files/1207077/KSP.log.txt)

**Comment by joflashstudios** [comment]
I'm having the same flickering issue.

**Comment by jrossignol** [comment]
This should be fixed in the RemoteTech Contract Pack.  If you continue to have problems, please re-open this issue.
