### ISSUE TITLE
Contracts changed to failed when upgrading ContractConfigurator from 1.23.1 to 1.23.2

### ISSUE THREAD

**Issue by zmpeg** [jrossignol/ContractConfigurator#637]
I recently upgraded from 1.23.1 to 1.23.2 and several remotetech contracts were moved from active to completed with a failed status (lots of funds gone too). The contracts were:
- Create a network for Moho
- Create a network for Duna
- Create a network for Dres
- Create a network for Jool
- Create a network for Eeloo

Unfortunately I didn't notice right away and the original ksp log file is gone. I was able to reproduce by editing the contract in the log file back to active. Please let me know if I can provide any more help or information. I could try reproducing on a clean game install.

    [LOG 09:48:25.116] [INFO] ContractConfigurator.ContractType: Cancelling contract of type RT_InnerPlanetRelay.Duna (Create a network for Duna): Too many completed/active/offered contracts.
    [WRN 09:48:25.117] ContractConfigurator.ConfiguredContract: Removed contract 'Create a network for Duna', as it no longer meets the requirements.

The full log file after editing: [KSP_log.zip](https://github.com/jrossignol/ContractConfigurator/files/1208781/KSP_log.zip)

**Comment by jrossignol** [comment]
This was fixed in the latest RemoteTech Contract Pack, so closing this issue.  Let me know if you're still having issues and we can re-open this.
