### ISSUE TITLE
Git hub download problem

### ISSUE THREAD

**Issue by AkihiroKisaragi** [jrossignol/ContractConfigurator#638]
I cant download from the github...i press clone and download as zip but they wont start download instead there is just a refresch icon on the title...pls help me

**Comment by jrossignol** [comment]
What exactly are you trying to do?  The clone is to get a copy of the source code.  You probably want to look at the [Releases Page](https://github.com/jrossignol/ContractConfigurator/releases).

**Comment by AkihiroKisaragi** [comment]
im trying to download the mod tho but idk how to download doe

**Comment by jrossignol** [comment]
Please use the [Release Page](https://github.com/jrossignol/ContractConfigurator/releases) for downloading the mod (or use [CKAN](https://github.com/KSP-CKAN/CKAN/releases)).
