### ISSUE TITLE
unlockCriteria being overwritten by accepting and failing science node

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#641]
This is a fun one.

See SFS here: https://ufile.io/b14yp

Conditions: 
Wing Connector E is already unlocked via accepting contract in GAP's contract here: https://github.com/inigmatus/GAP/blob/master/Economy/SSI-Wright-Wing.cfg

Works just fine.  Part can be used.

But the unlock status is being overwritten when doing the following after loading the SFS above:

1. Go to Research and Development building
2. Attempt to research the Aviation node
3. You don't have sufficient science so the node does not unlock, however the green highlight indicating the Wing Connector E is unlocked, is now removed - and the part is therefore no longer available in SPH. 

Essentially whenever someone attempts to research the next node that contains a previously unlocked (experimental) part by ContractConfigurator, the unlock flag for that part is removed and the part is no longer accessible to builders - even when the player has insufficient science to research the node. Could be KSP bug or the way CC is triggering removal of the experimental/unlocked part flag?

Confirmed happening to any unlocked part by CC, and only when attempting to research the node, but failing for insufficient science points.

**Comment by jrossignol** [comment]
Hmmm...  this is going to be a stock bug.  I'll take a look and raise it - we'll see if it's possible to get a fix in 1.3.1.

**Comment by jrossignol** [comment]
Nope, your instinct was right - this was a CC bug.  Fixed for next release.
