### ISSUE TITLE
BUG: Parsing celestialbody names with non alphanumeric characters results in an exception

### ISSUE THREAD

**Issue by Chemox** [jrossignol/ContractConfigurator#642]
**Partial Logfile:**
[https://pastebin.com/KCWKpc3U](https://pastebin.com/KCWKpc3U)

**Full Logfile**
Can be delivered on request to large for pastebin (although partial logfile should make it clear already)

**Expected behaviour:** 
Create new contract without throwing errors

**Present behaviour:**
As seen in a part from the log file the parser that handles celestialbody names doesn't work well with non-alphanumeric characters like / or -. An error is being trown

**Mods**
ModuleManager v2.8.1.0
ContractConfigurator v1.23.2
Galactic Neighbourhood v0.4.4 + all planet packs except for stock-alike solar system
Kopernicus v1.3.0-8
Sigma-Dimensions v0.9.3
Sigma-Binary v1.6.6

Most likely reproducible with MM, CC, Kopernicus and [Other_worlds planet pack](https://forum.kerbalspaceprogram.com/index.php?/topic/115917-131211-kopernicus-other_worlds-starplanet-pack-v102/) as those contain some of the oddly named planets/moons

For making the contracts you could use [cacteye](https://forum.kerbalspaceprogram.com/index.php?/topic/141298-130-cacteye-optics-community-takeover-updated-7182017/&) as it tries to generate contracts for each available planet and/or moon.

**Why this should be fixed**
When using galactic neighbourhood (and some of the supported planet packs) it would be nice to have the possibility to make contracts for those planets and moons as well without the need of renaming them.

**Comment by jrossignol** [comment]
This was particularly nasty to track down, but got the proper fix in.
