### ISSUE TITLE
Newlines in description?

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#65]
Don't know how Unity is working there, I tried to add \n for newline, that didn't worked. If you know how to add newlines, please add it to the wiki. I will take a look at the problem tomorrow.

**Comment by jrossignol** [comment]
Fixed this so that newlines can be entered as \n in the config values.  I couldn't find a way to make it work in stock, but this was an easy fix since I moved all the loading/validation into one class. :smile:
