### ISSUE TITLE
TargetBody1 NRE spam

### ISSUE THREAD

**Issue by theonegalen** [jrossignol/ContractConfigurator#656]
With nothing but CC, MM, and various contract packs installed, CC throws a nullref while on the main Space Center screen every minute or so, I assume on contract generation.

It seems to relate to something called TargetBody1 not existing. A cursory search of my contracts revealed that Field Research and Career Evolution both have TargetBody1 in a few different places.

https://drive.google.com/file/d/1BvP4G0eCECpkzOVYruVMa1vk4oyiA948/view?usp=drivesdk

**Comment by jrossignol** [comment]
This should already be fixed by ee8e6e78b6b0d1693ee27e44dcfd593942f4cd28.  Let me know if the next release doesn't fix this issue and we can re-open this.
