### ISSUE TITLE
RemoteTech problem...

### ISSUE THREAD

**Issue by Bliczz** [jrossignol/ContractConfigurator#658]
RemoteTech contract doesnt show.

[ERR 00:09:34.155] ContractConfigurator.HasAntennaFactory: CONTRACT_TYPE 'RT_OuterSat', PARAMETER 'HasAntenna' of type 'HasAntenna': Either minAntennaPower or maxAntennaPower is required.

[ERR 00:09:34.169] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.180] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.189] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.197] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.204] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.212] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.220] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.228] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.235] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.244] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_OuterSat',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[WRN 00:09:34.257] ContractConfigurator.ContractType: Errors encountered while trying to load CONTRACT_TYPE 'RT_OuterSat'
[LOG 00:09:34.266] [INFO] ContractConfigurator.ContractType: Loading CONTRACT_TYPE: 'RT_PlanetMoonRelay'
[ERR 00:09:34.273] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_PlanetMoonRelay',PARAMETER '' of type 'CelestialBodyCoverage': Unknown parameter 'CelestialBodyCoverage'.

[ERR 00:09:34.284] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_PlanetMoonRelay',REQUIREMENT 'CelestialBodyCoverage' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.294] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_PlanetMoonRelay',REQUIREMENT '' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[ERR 00:09:34.304] ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_PlanetMoonRelay',REQUIREMENT '' of type 'CelestialBodyCoverage': Unknown requirement 'CelestialBodyCoverage'.

[WRN 00:09:34.344] ContractConfigurator.ContractType: CONTRACT_TYPE 'RT_PlanetMoonRelay': Not expanding DATA_EXPAND node as the contract had validation errors.
[ERR 00:09:34.346] ContractConfigurator.ContractType: CONTRACT_TYPE 'RT_PlanetMoonRelay': Error parsing targetBody
[KSP.log](https://github.com/jrossignol/ContractConfigurator/files/1905112/KSP.log)

**Comment by Bliczz** [comment]
Or that because of mods?
[DeadEnd.zip](https://github.com/jrossignol/ContractConfigurator/files/1905118/DeadEnd.zip)

**Comment by Bliczz** [comment]
[ERR 17:43:38.221] AssemblyLoader: Exception loading 'CC_RemoteTech': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'ContractConfigurator.RemoteTech.RemoteTechProgressTracker+FakeSatellite' from assembly 'CC_RemoteTech, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<get_Antennas>d__31' from assembly 'CC_RemoteTech, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<FindNeighbors>d__35' from assembly 'CC_RemoteTech, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jrossignol** [comment]
Fixed by #659, this is due to a change in RemoteTech.  The linked issue has a copy of CC_RemoteTech.dll that you can use until the official release.
