### ISSUE TITLE
Parameter: Site (For DLC Compatibility)

### ISSUE THREAD

**Issue by inigmatus** [jrossignol/ContractConfigurator#663]
I suggest adding a new parameter called LaunchSite:

PARAMETER:NEEDS[SquadExpansion/MakingHistory]
{
name = Site
type = Site

site = LaunchPad
}

The sites would be:

site = LaunchPad
site = Runway
site = IslandAirfield
site = WoomerangLaunchSite
site = DessertLaunchSite
site = DessertAirfield
site = SPH
site = VAB
site = AdministrationBuilding

The parameter would check the player is in the proper bounds of the location.

**Comment by inigmatus** [comment]
Maybe just call the parameter Site instead of LaunchSite. This is to allow for checking both launch and landing locations.

**Comment by jrossignol** [comment]
Hmmm, would using [VisitWaypoint](https://github.com/jrossignol/ContractConfigurator/wiki/VisitWaypoint-Parameter) with a way to easily generate a waypoint for the above sites be better?  You can then use the various waypoint "features" (and things like Waypoint Manager).

**Comment by inigmatus** [comment]
Would that check if you are launching from one of the locations?

**Comment by jrossignol** [comment]
It could if you combine it with ReachState with situation=PRELAUNCH.

**Comment by inigmatus** [comment]
im cool with whatever syntax you come up with. :)

**Comment by inigmatus** [comment]
Looking forward to whatever solution is arrived at. Been itching to code contracts for the other destos.

**Comment by jrossignol** [comment]
Sorry about the delay here - life got in the way.  I have the rough idea sketched out:
- Add a new block called LAUNCH_SITE to [WaypointGenerator](https://github.com/jrossignol/ContractConfigurator/wiki/WaypointGenerator-Behaviour)
  - Most likely this will be modelled off PQS_CITY
- Still need to figure out what a Launch Site actually is, code-wise (I haven't gone spelunking for that yet).

Should be able to get it prototyped within the next couple days.

**Comment by inigmatus** [comment]
> Sorry about the delay here - life got in the way. I have the rough idea sketched out:
> 
> * Add a new block called LAUNCH_SITE to [WaypointGenerator](https://github.com/jrossignol/ContractConfigurator/wiki/WaypointGenerator-Behaviour)
>   
>   * Most likely this will be modelled off PQS_CITY
> * Still need to figure out what a Launch Site actually is, code-wise (I haven't gone spelunking for that yet).
> 
> Should be able to get it prototyped within the next couple days.


In looking at my contracts, I make most use of pqsCity and the pqsOffset. If you simply added pqs numbers for the new locations, it should be enough to simply run a waypoint check in a contract's parameter section.

**Comment by inigmatus** [comment]
Not working. or I'm missing something.

Here's a prototype contract that doesn't seem to trigger: https://text-share.com/view/1cb0715e#OuwqVMUZe7tfTetvXDeXZ4NBjQmQakBh

**Comment by Gordon-Dry** [comment]
This could also be interesting for RSS ... I guess.

**Comment by inigmatus** [comment]
One thing I noticed is that your load passenger routine always loads on launch, before any parameter checks. I wonder if you could code your load passenger routine to check for the Waypoint Generator LAUNCH_SITE block and if exists then hold asking to load passengers until the parameter VisitWaypoint passes the LAUNCH_SITE waypoint.

**Comment by inigmatus** [comment]
In addition you should consider adding biome = Dessert Airfield to your Parameter ReachState options.

**Comment by jrossignol** [comment]
Oh right, Module Manager...  I guess I didn't need to add that requirement.  Oops.

Other changes are on the way to support this one.
