### ISSUE TITLE
CC doesn't show days to expire on RSS install

### ISSUE THREAD

**Issue by Gordon-Dry** [jrossignol/ContractConfigurator#669]
Only hours, minutes, seconds are shown.

The days are completely cut off:
https://i.imgur.com/q8gpyKu.png

**Comment by Kerbas-ad-astra** [comment]
That's not Contract Configurator, that's Contracts Window Plus by @DMagic1: https://github.com/DMagic1/KSP_Contract_Window

**Comment by Gordon-Dry** [comment]
Right, I'm overwhelmed by the different things I'm actually going through ...

**Comment by Gordon-Dry** [comment]
Closed, removed to https://github.com/DMagic1/KSP_Contract_Window/issues/45
