### ISSUE TITLE
Wiki Doc:  Behaviour UnlockTech  techId should be techID

### ISSUE THREAD

**Issue by histalonia** [jrossignol/ContractConfigurator#680]
After writing new contracts and running them through the debugger, I found out that the syntax in the docs is incorrect.  techId in the doc should be techID as that's what the code recognizes.

see:  https://github.com/jrossignol/ContractConfigurator/wiki/UnlockTech-Behaviour

FYI my contract group has minVersion = 1.22.0

**Comment by jrossignol** [comment]
Confirmed and fixed.  Thanks for the report.
