### ISSUE TITLE
Facility requirements of maxLevel=2 produces requirement text like minLevel=1

### ISSUE THREAD

**Issue by histalonia** [jrossignol/ContractConfigurator#681]
Facility requirement check of maxLevel=2, produces the following requirement text:
The Mission Control Building must be at least level one:

This should be something like:  no higher than level two   or   not level 3.

Here is config code from the contract:
    REQUIREMENT
    {
      name = FacilityMissionControl
      type = Facility
      facility = MissionControl
      maxLevel = 2
      checkOnActiveContract = false
    }

**Comment by jrossignol** [comment]
Fixed via 5889c212057fcf7bd987868622c850e704810f98.  Technically it's still bugged if someone has minLevel=1 and maxLevel=3, but that's a bit of a silly case.

**Comment by jrossignol** [comment]
Also, if you grab the ContractConfigurator.dll from the link above you can test the fix for yourself (although it's only a display bug).

**Comment by histalonia** [comment]
Will 1.28 work in 1.7.3?
If not can you release a 1.27.2 version with the fix for KSP 1.7.3?
Thanks so much for maintaining this mod.

**Comment by jrossignol** [comment]
It won't work in older versions of KSP, and I won't release for old
versions unless there's a major issue.  In this case is a display issue,
and you should be able to work around it by providing your own requirement
text.
