### ISSUE TITLE
Some agents no longer loading since 1.28.1 - new agent parser suspected cause

### ISSUE THREAD

**Issue by Morphisor244** [jrossignol/ContractConfigurator#687]
The 'History of Spaceflight' contract pack is no longer loaded ingame, after the update. Meaning, none of its contracts show up. Not even in the debug menu.

It appears related to the new agent parser; it is somehow interfering with loading in certain agents. I suspect a number of contract groups related to these agents therefore fail to load as a result.
The logs give virtually no info on this at all - the only thing I could tell from them in my test install was that it's loading 47 agents. History of Spaceflight defines 65 agents all by itself, so that's a problem.
I have no idea why it won't load some agents while others are fine - it's hard to tell which ones it doesn't load, only process of elimination works here.

HoSf has a lot of groups nested within other groups, and if any sub-nodes fail to parse, the entire lot ends up disabled.

I came to these conclusions after a lot of testing and moving around contract groups, with the help of severedsolo. Separating the main group from the sub-groups resulted in most of those groups loading, only some still fail - presumably the ones affected. Yet, even the groups that DID load had a warning added to them in the CC debug menu: "providing agent field for all contract_group nodes is highly recommended". Yet they all evidently have defined agent fields.

I hope this is sufficient information, you can have a look at the group and agent definitions here: https://github.com/Frylovespi/History-of-Spaceflight/blob/M_dev/Stock/GameData/ContractPacks/HistoryofSpaceflight/HistoryofSpaceflight.cfg

**Comment by jrossignol** [comment]
There's at least one error in the log where it didn't like the '-' in the agent name.  I've loosened the parsing restrictions and will release 1.28.2 with this fix soon.
