### ISSUE TITLE
Contract immediately starts with "No vessel currently matching parameters"

### ISSUE THREAD

**Issue by liamdennehy** [jrossignol/ContractConfigurator#697]
Browsing the available contracts, I'd like to bring one tourist to a station:
![CCPlus-NoVessel-Offer](https://user-images.githubusercontent.com/4996358/97203482-2871d400-17b5-11eb-90f9-ff14991177d2.png)

But once I accept, it can't find the vessel it just offered me a contract for:
![CCPlus-NoVessel-Active](https://user-images.githubusercontent.com/4996358/97203510-34f62c80-17b5-11eb-825d-19084cff5f09.png)

Note the screenshots are from a single scene - no renaming, docking or otherwise happened in the meantime.
[persistent.sfs zipped](https://github.com/jrossignol/ContractConfigurator/files/5440288/persistent.zip)

KSP: 1.9.1 Linux x64
ContractConfigurator: 1.30.5

**Comment by liamdennehy** [comment]
Focused views for forum issue:
![CCPlus-NoVessel-Offer-cropped](https://user-images.githubusercontent.com/4996358/97226658-94b00000-17d4-11eb-8a38-bd220f5adb8d.png)
![CCPlus-NoVessel-Active-cropped](https://user-images.githubusercontent.com/4996358/97226662-97aaf080-17d4-11eb-8723-38ba96e1c9a0.png)

**Comment by jrossignol** [comment]
This may be just a display issue in Mission Control.  I see there's another contract for Iota Station - does that one do the same thing?  If go to the station, does it say the same thing?  If you go to a vessel other than the station, what does it say then?

**Comment by liamdennehy** [comment]
Every existing and new contract targeting a station shows this. I am however getting mixed results on whether it actually does track the mission progress properly. Will keep testing and feed back.

**Comment by liamdennehy** [comment]
One contract does appear to successfully complete despite the above, testing a second now.
