### ISSUE TITLE
Is it possible to make it so once a contract is completed, I will not get that contract again for a set period of time?

### ISSUE THREAD

**Issue by iLikeGothMommys** [jrossignol/ContractConfigurator#734]
I have a contract I have made that I would only like to be available once every 5 years, is it possible to make it so once I complete it a 5 year timer starts before it appears in mission control again?

**Comment by jrossignol** [comment]
Yes, see the [CompleteContract requirement](https://github.com/jrossignol/ContractConfigurator/wiki/CompleteContract-Requirement).  There is a cooldownDuration that can be set so the contract is only available x years/days/hours after the last one was completed.

**Comment by iLikeGothMommys** [comment]
> Yes, see the [CompleteContract requirement](https://github.com/jrossignol/ContractConfigurator/wiki/CompleteContract-Requirement). There is a cooldownDuration that can be set so the contract is only available x years/days/hours after the last one was completed.

@jrossignol Thank you, but I thought that variable was only used to check if a different contract was completed at a specified interval period. I will mess with it some more though.

When I was experimenting with that variable once I completed my custom contract I still immediately got a repeat of that contract.

Also, is it possible to add a timer for if I declined / missed the acceptance deadline?

**Comment by iLikeGothMommys** [comment]
> Yes, see the [CompleteContract requirement](https://github.com/jrossignol/ContractConfigurator/wiki/CompleteContract-Requirement). There is a cooldownDuration that can be set so the contract is only available x years/days/hours after the last one was completed.

		REQUIREMENT
          {
			name = CompleteContract
                        type = CompleteContract
			invertRequirement = true
			contractType = DunaInvestor
			cooldownDuration = 200d
	    }


I tried doing it like that and after completing the contract it flashes between available and unavailable for a period of 200 days, after the 200 days it says that the requirement is unmet and no matter how long I wait this variable stays as unmet

**Comment by iLikeGothMommys** [comment]
> Yes, see the [CompleteContract requirement](https://github.com/jrossignol/ContractConfigurator/wiki/CompleteContract-Requirement). There is a cooldownDuration that can be set so the contract is only available x years/days/hours after the last one was completed.

Okay, I was able to get it using this:
	
        REQUIREMENT
        {
			name = CompleteContract
                        type = CompleteContract
			contractType = AgencyInvestor
			cooldownDuration = 200d
			minCount = 0
	    }

Is it also possible to make a timer start if the contract is declined / missed due to not being accepted?

**Comment by jrossignol** [comment]
Hard to say, as I don't really have access to a proper install to test
myself these days.

Here's a contact I found from a GitHub search that sets it for the current
contract, using minCount:
https://github.com/maculator/KerbalAircraftBuilders/blob/b7b565ab16057858ee68357cf18f0d2d50048dc1/Tourists.cfg#L40

(Basically it reads as must have complete 0 of this contract in the last 10
days).

I don't believe there is anything that can trigger based on contact
expiry/decline.
