### ISSUE TITLE
Is it possible to add reward modifiers to non-stock planets?

### ISSUE THREAD

**Issue by iLikeGothMommys** [jrossignol/ContractConfigurator#735]
I would like to be able to add reward modifiers to the planets from OPM, I looked through the source & the ContractConfigurator folder but did not see anything relating to modifiers.

**Comment by jrossignol** [comment]
I'm pretty sure that it happens in the stock code, and I would imagine as
part of Kopernicus (or whatever gets used for planet modding these days)
that the modifiers would be specified as part of the planet definition.

See
https://github.com/jrossignol/ContractConfigurator/wiki/Contract-Type#contract-reward-modifiers
(won't help you much, but supports the above)
