### ISSUE TITLE
How can I make it so targetBody will to randomize from all reached bodies except HomeWorld & its children?

### ISSUE THREAD

**Issue by iLikeGothMommys** [jrossignol/ContractConfigurator#739]
I'm almost complete with my contract mod, I am wrapping up the last contract right now. My only issue is I need the targetBody to select randomly from all reached bodies except HomeWorld & its children. I've tried using the .Where() method but was unable to filter the children out, I have also tried using expression requirements such as:

`expression = @targetBody != HomeWorld().Children().First() && @targetBody != HomeWorld().Children().ElementAt(2)
`
along with the targetBody
`targetBody = ReachedBodies().Where(b => !b.IsSun() && !b.IsHomeWorld()).Random()`

These should at least filter out the Mun & Minmus. The problem is though, when I use this requirement it will stop me from getting the contract at all (even though it shows all requirements are met in mission control)

Can you please give me assistance? I apologize if posting this as an issue is not the proper way to reach you, but it shows you haven't been on the KSP forums in a few months.

Thank you.

**Comment by jrossignol** [comment]
Try without the expression and add && b.Parent() != HomeWorld() to the target body Where clause.

**Comment by iLikeGothMommys** [comment]
Thank you so much, this worked perfectly. I spent an hour or two last night throwing stuff at the wall to see what would stick before I messaged here.
