### ISSUE TITLE
Parameter based on manufacturer / author

### ISSUE THREAD

**Issue by hakan42** [jrossignol/ContractConfigurator#76]
Copy&Paste from the forum so it does not get lost in the threads:

http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-5-0-2015-01-08?p=1643227&viewfull=1#post1643227

http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-5-0-2015-01-08?p=1643703&viewfull=1#post1643703

Quote Originally Posted by hakan  
Is there a way to indicate a vessel should have only parts from a certain manufacturer and / or author?

I would love to set up a contract where Professor Phineas Kerbenstein wants to show the world that the only way to space hegemony is via his vertical propulsion emporium and thereby requires satellite / mun base / whatever be created with only parts sanctioned by his empire 

Quote Originally Posted by nigtinhale

Neat idea, I like it! Right now the closest you could get is disallowing *specific* parts, which wouldn't work too well. Thinking about it has given me some ideas for how to handle it better, and I should be able to get it into my planned 0.5.0 roadmap. So wait a week or so and I'll have you covered. Some exciting stuff coming in 0.5.0...

**Comment by hakan42** [comment]
And now that I think more about it, a condition might also be "x% of the total vessel mass must be from a certain manufacturer"

That way, the Professor can still have his Steampunk Orbital Lair, but have it adorned with some surfacelights :smiling_imp:

**Comment by jrossignol** [comment]
The basic idea is supported, but now you're throwing too many wrenches in the mix!

This should be the basic one:

    // Every part is steampunk - no exceptions
    PARAMETER
    {
        name=PartValidation
        type=PartValidation

        manufacturer = Professor Kerbenstein's wonderous vertical propulsion emporium.

        allParts=True        
    }

See https://github.com/jrossignol/ContractConfigurator/wiki/Parameters#partvalidation for more.

Let me think about some other enhancements I can do to make it more flexible....  maybe do away with the restrictive allParts flag and have an extended mode:

    // All areo and engine parts must be steampunk
    PARAMETER
    {
        name=PartValidation
        type=PartValidation

        category=aero
        category=engine

        ALL_PARTS
        {
            manufacturer = Professor Kerbenstein's wonderous vertical propulsion emporium.
        }
    }

Would that be flexible enough to get the job done?

**Comment by hakan42** [comment]
Sorry, it's an occupational hazard to over-think and over-complicate things :blush: 

The second suggestion sounds pretty nice. I guess I can implement quite a few Steampunky Contracts with that...

* "Professors Steam-powered Carriages can reach the pole" (restriction on Engine and Fuel Tank)
* "Reach the Mun with Munshine only" (restriction on Fuel Tank, with a negated HasResource on LiquidFuel)
* ...
* and some other ideas I need to think through :smiling_imp:

**Comment by jrossignol** [comment]
Okay, this is done, have a look at the wiki:
https://github.com/jrossignol/ContractConfigurator/wiki/Parameters#partvalidation

...and play around with it a bit if you like (the latest .dll is checked in).  It's pretty close to what I described with a little bit more.  Should meet a good chunk of your fun scenarios.

**Comment by jrossignol** [comment]
RemoteTech forced my hand by releasing 1.6 in a non-backwards compatible way, so I had to do a release.  I wanted the outstanding changes to go soon anyway, so this is now in the wild.  Raise a new issue if the Professor needs yet more flexibility :laughing:

**Comment by hakan42** [comment]
The professor will show his gratitude in an appropriate way... By sending some of his minions your way :smile_imp:
