### ISSUE TITLE
SCANsat integration will be broken by the next update

### ISSUE THREAD

**Issue by DMagic1** [jrossignol/ContractConfigurator#80]
I'm in the middle of lots of internal code changes to SCANsat, which will break just about anything that doesn't rely only on the [SCANUtil methods](https://github.com/DMagic1/SCANsat/blob/dev/SCANsat/SCANutil.cs).

From what I can see the only thing that might be affected here is a namespace and location change for the [SCANtype Enum](https://github.com/DMagic1/SCANsat/blob/dev/SCANsat/SCAN_Data/SCANtype.cs). It has been moved into its own file since it really has no place being within the SCANdata class. I didn't look too much, but I think you might not really need to use the actual SCANtype, you can probably get away with only using the integer value for the desired SCANtype, since those public SCANUtil methods all rely on generic types.

If you want to follow along or look at the changes they can be found in the dev branch of [my own fork of SCANsat](https://github.com/DMagic1/SCANsat/tree/dev).

And if you have any suggestions or requests for more of those SCANUtil methods feel free to send them my way or submit a pull request.

**Comment by jrossignol** [comment]
Awesome, thanks for the heads up!  Basically I just need a way to have the modders supply a reasonable name in the config file (ie. the Enum values) and convert it to an int for use in the public methods.  Sent you a pull request with a method that does just that.  If you accept that, then I'll be more than happy staying within the SCANUtil methods. :+1:

**Comment by DMagic1** [comment]
OK, this should work fine: 
DMagic1/SCANsat@4aa1b626f3ec412256c0f557c7f8a6d5a4b24a39

**Comment by jrossignol** [comment]
Great, thanks.  I've got the changes for my side tucked away on a branch, ready to be released at pretty much a moment's notice.
