### ISSUE TITLE
Docking Parameter

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#86]
The parameter just says: "No situation report available". We may should write an own docking parameter.

**Comment by jrossignol** [comment]
I'm going to be working on #73 soon - which will deprecate the ReachSituation one, so this should no longer be an issue when that one's done.

**Comment by jrossignol** [comment]
Although....  given that when you dock your situation is still orbiting, I'm not sure how a ReachSituation = Docked even makes sense.  Unless the situation is very briefly "Docked" and we need to make sure to have disableOnStateChange = true?  I'll have to test.

**Comment by jrossignol** [comment]
So it looks like Docked simply isn't a valid situation, so I've removed it from the documentation.

So the question becomes, what do you need?

I'm thinking a Docking parameter that gets completed when Vessel A and Vessel B dock.  A & B can each be any of:
* Active Vessel
* Any Vessel
* A "defined" vessel defined using a VesselParameterGroup (or other ways like the upcoming VesselSpawner behaviour).

Would that meet your needs?

**Comment by SimonTheSourcerer** [comment]
Would be awesome! Just wanted to dock two specific vessels determind by VesselParameterGroup :)

**Comment by jrossignol** [comment]
Have a look at the Docking parameter under the master branch and let me know if there's issues.
