### ISSUE TITLE
ReachState is broken without a situation, will throw a NullPointer

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#90]
Fixed it already, adding a pull request soon.

**Comment by jrossignol** [comment]
Not planning another 0.5.x release, so I'm going to put this into 0.6.0.  Reminder to myself that if another 0.5.x release happens, to branch off this commit instead of 0.5.4 so as to include this fix.

**Comment by jrossignol** [comment]
Scratch that, just double checked and I see that 1.0.3 of your SCANsat contract pack will depend on this fix.  I'll get this out (and possibly other small fixes sometime today).

**Comment by SimonTheSourcerer** [comment]
I only changed the parameters to ReachState. 1.0.3 Got no real changes, just stops the error messages caused by deprecated parameters. I hope CKAN ignores prereleased releases :)

**Comment by jrossignol** [comment]
As far as I know it does. :)

**Comment by hakan42** [comment]
No problem, by default, we *do* ignore prereleases :smiling_imp:
