### ISSUE TITLE
Orbit Parameter should allow escaping orbits too. 

### ISSUE THREAD

**Issue by SimonTheSourcerer** [jrossignol/ContractConfigurator#93]
For example: Mun flyby with a periapsis between 20.000m and 50.000m should be covered by the OrbitParameter too.

**Comment by jrossignol** [comment]
Doesn't it? Try situation = escaping, then set only min/max periapsis.

**Comment by SimonTheSourcerer** [comment]
OrbitFactory doesn't check for situation and OrbitParameter adds just a filter for vessel.situation == situation.ORBITING so  I didn't tried.

**Comment by jrossignol** [comment]
Yup, I was thinking of ReachState.  I'll change this so that it will allow situations of Sub-Orbital, Orbital and Escaping (with Orbital being the default).

**Comment by jrossignol** [comment]
Done, let me know if there's issues.
