### ISSUE TITLE
completedMessage on Optional parameters

### ISSUE THREAD

**Issue by DBT85** [jrossignol/ContractConfigurator#98]
May not be possible, but the option to add custom completedMessage to optional parameters would be nice since it gives you a mission complete alert in game.

**Comment by jrossignol** [comment]
Unfortunately, as much as I'd like to do this, it would require changes to the stock contract system. :cry:

**Comment by DBT85** [comment]
:( damn them!

**Comment by jrossignol** [comment]
I wrote a system to pop up a message box.  Then I realized the message box was too annoying to the player (if say, they were trying to land), so I replaced it with a call to the stock messaging system.  Then I realized, that I had just solved this for you. :)

Have a look at the [Message Behaviour] (https://github.com/jrossignol/ContractConfigurator/wiki/Behaviours#message).
